// Code generated by go-vk from vk.xml at 2025-10-25 17:30:05.450235397 +0000 UTC m=+6.184569193. DO NOT EDIT.

package vk

// MacOSSurfaceCreateFlagsMVK: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMacOSSurfaceCreateFlagsMVK.html
type MacOSSurfaceCreateFlagsMVK Flags
