// Code generated by go-vk from vk.xml at 2025-10-26 13:04:52.894531277 +0000 UTC m=+12.302229565. DO NOT EDIT.

package vk

// DirectFBSurfaceCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDirectFBSurfaceCreateFlagsEXT.html
type DirectFBSurfaceCreateFlagsEXT Flags
