// Code generated by go-vk from vk.xml at 2025-10-26 13:04:53.265718166 +0000 UTC m=+12.673416444. DO NOT EDIT.

package vk

// MacOSSurfaceCreateFlagsMVK: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMacOSSurfaceCreateFlagsMVK.html
type MacOSSurfaceCreateFlagsMVK Flags
