// Code generated by go-vk from vk.xml at 2025-10-26 13:04:51.289248485 +0000 UTC m=+10.696946753. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
