// Code generated by go-vk from vk.xml at 2025-10-25 17:30:05.419938645 +0000 UTC m=+6.154272441. DO NOT EDIT.

package vk

// DirectFBSurfaceCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDirectFBSurfaceCreateFlagsEXT.html
type DirectFBSurfaceCreateFlagsEXT Flags
