// Code generated by go-vk from vk.xml at 2025-10-26 13:04:51.444069535 +0000 UTC m=+10.851767793. DO NOT EDIT.

package vk

// XlibSurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkXlibSurfaceCreateFlagsKHR.html
type XlibSurfaceCreateFlagsKHR Flags
