// Code generated by go-vk from vk.xml at 2025-10-25 17:30:05.707644166 +0000 UTC m=+6.441978002. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
