// Code generated by go-vk from vk.xml at 2025-10-26 13:04:52.616682004 +0000 UTC m=+12.024380283. DO NOT EDIT.

package vk

// XcbSurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkXcbSurfaceCreateFlagsKHR.html
type XcbSurfaceCreateFlagsKHR Flags
