// Code generated by go-vk from vk.xml at 2025-10-26 13:04:52.209229617 +0000 UTC m=+11.616927915. DO NOT EDIT.

package vk

// WaylandSurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWaylandSurfaceCreateFlagsKHR.html
type WaylandSurfaceCreateFlagsKHR Flags
