// Code generated by go-vk from vk.xml at 2025-10-25 17:30:04.908174735 +0000 UTC m=+5.642508531. DO NOT EDIT.

package vk

// XcbSurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkXcbSurfaceCreateFlagsKHR.html
type XcbSurfaceCreateFlagsKHR Flags
