// Code generated by go-vk from vk.xml at 2025-10-25 17:30:06.427898852 +0000 UTC m=+7.162232648. DO NOT EDIT.

package vk

// WaylandSurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWaylandSurfaceCreateFlagsKHR.html
type WaylandSurfaceCreateFlagsKHR Flags
