// Code generated by go-vk from vk.xml at 2025-10-25 17:30:04.677878866 +0000 UTC m=+5.412212662. DO NOT EDIT.

package vk

// XlibSurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkXlibSurfaceCreateFlagsKHR.html
type XlibSurfaceCreateFlagsKHR Flags
