//go:build darwin

// Code generated by go-vk from vk.xml at 2025-10-25 17:30:06.169574696 +0000 UTC m=+6.903908482. DO NOT EDIT.

package vk

import "unsafe"

// CreateMetalSurfaceEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateMetalSurfaceEXT.html
func CreateMetalSurfaceEXT(instance Instance, createInfo *MetalSurfaceCreateInfoEXT, allocator *AllocationCallbacks) (surface SurfaceKHR, r error) {
	// Parameter is a singular input, requires translation - createInfo
	var pCreateInfo *_vkMetalSurfaceCreateInfoEXT
	if createInfo != nil {
		pCreateInfo = createInfo.Vulkanize()
	}

	// Parameter is a singular input, pass direct - allocator
	var pAllocator unsafe.Pointer
	if allocator != nil {
		pAllocator = unsafe.Pointer(allocator)
	}

	// surface is a binding-allocated single return value and will be populated by Vulkan
	ptr_pSurface := &surface

	r = Result(execTrampoline(vkCreateMetalSurfaceEXT, uintptr(instance), uintptr(unsafe.Pointer(pCreateInfo)), uintptr(unsafe.Pointer(pAllocator)), uintptr(unsafe.Pointer(ptr_pSurface))))

	if r == Result(0) {
		r = SUCCESS
	}
	return
}

var vkCreateMetalSurfaceEXT = &vkCommand{"vkCreateMetalSurfaceEXT", 4, true, nil}

// ExportMetalObjectsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkExportMetalObjectsEXT.html
func ExportMetalObjectsEXT(device Device) (metalObjectsInfo ExportMetalObjectsInfoEXT) {
	// metalObjectsInfo is a binding-allocated single return value and will be populated by Vulkan, but requiring translation
	var pMetalObjectsInfo *_vkExportMetalObjectsInfoEXT = metalObjectsInfo.Vulkanize()

	execTrampoline(vkExportMetalObjectsEXT, uintptr(device), uintptr(unsafe.Pointer(pMetalObjectsInfo)))

	metalObjectsInfo = *(pMetalObjectsInfo.Goify())
	return
}

var vkExportMetalObjectsEXT = &vkCommand{"vkExportMetalObjectsEXT", 2, true, nil}

// GetMemoryMetalHandleEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetMemoryMetalHandleEXT.html
func GetMemoryMetalHandleEXT(device Device, getMetalHandleInfo *MemoryGetMetalHandleInfoEXT) (handle *byte, r error) {
	// Parameter is a singular input, requires translation - getMetalHandleInfo
	var pGetMetalHandleInfo *_vkMemoryGetMetalHandleInfoEXT
	if getMetalHandleInfo != nil {
		pGetMetalHandleInfo = getMetalHandleInfo.Vulkanize()
	}

	// handle is a binding-allocated single return value and will be populated by Vulkan
	ptr_pHandle := &handle

	r = Result(execTrampoline(vkGetMemoryMetalHandleEXT, uintptr(device), uintptr(unsafe.Pointer(pGetMetalHandleInfo)), uintptr(unsafe.Pointer(ptr_pHandle))))

	if r == Result(0) {
		r = SUCCESS
	}
	return
}

var vkGetMemoryMetalHandleEXT = &vkCommand{"vkGetMemoryMetalHandleEXT", 3, true, nil}

// GetMemoryMetalHandlePropertiesEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetMemoryMetalHandlePropertiesEXT.html
func GetMemoryMetalHandlePropertiesEXT(device Device, handleType ExternalMemoryHandleTypeFlagBits, handle *byte) (memoryMetalHandleProperties MemoryMetalHandlePropertiesEXT, r error) {
	// Parameter is a singular input, pass direct - handle
	var pHandle unsafe.Pointer
	if handle != nil {
		pHandle = unsafe.Pointer(handle)
	}

	// memoryMetalHandleProperties is a binding-allocated single return value and will be populated by Vulkan, but requiring translation
	var pMemoryMetalHandleProperties *_vkMemoryMetalHandlePropertiesEXT = memoryMetalHandleProperties.Vulkanize()

	r = Result(execTrampoline(vkGetMemoryMetalHandlePropertiesEXT, uintptr(device), uintptr(handleType), uintptr(unsafe.Pointer(pHandle)), uintptr(unsafe.Pointer(pMemoryMetalHandleProperties))))

	memoryMetalHandleProperties = *(pMemoryMetalHandleProperties.Goify())
	if r == Result(0) {
		r = SUCCESS
	}
	return
}

var vkGetMemoryMetalHandlePropertiesEXT = &vkCommand{"vkGetMemoryMetalHandlePropertiesEXT", 4, true, nil}
