// Code generated by go-vk from vk.xml at 2025-10-26 13:04:51.906488612 +0000 UTC m=+11.314186890. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR StructureType = 1000006000
)
