// Code generated by go-vk from vk.xml at 2025-10-26 13:04:53.252300706 +0000 UTC m=+12.659998995. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
