// Code generated by "stringer -output=enum_string_9.go -type=VideoEncodeFeedbackFlagBitsKHR,VideoEncodeFlagBitsKHR,VideoEncodeH264CapabilityFlagBitsKHR,VideoEncodeH264RateControlFlagBitsKHR,VideoEncodeH264StdFlagBitsKHR,VideoEncodeH265CapabilityFlagBitsKHR,VideoEncodeH265CtbSizeFlagBitsKHR,VideoEncodeH265RateControlFlagBitsKHR,VideoEncodeH265StdFlagBitsKHR,VideoEncodeH265TransformBlockSizeFlagBitsKHR,VideoEncodeIntraRefreshModeFlagBitsKHR,VideoEncodeRateControlModeFlagBitsKHR,VideoEncodeRgbChromaOffsetFlagBitsVALVE,VideoEncodeRgbModelConversionFlagBitsVALVE,VideoEncodeRgbRangeCompressionFlagBitsVALVE,VideoEncodeTuningModeKHR,VideoEncodeUsageFlagBitsKHR,VideoSessionCreateFlagBitsKHR,VideoSessionParametersCreateFlagBitsKHR,ViewportCoordinateSwizzleNV"; DO NOT EDIT.

package vk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_FEEDBACK_BITSTREAM_BUFFER_OFFSET_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_FEEDBACK_BITSTREAM_BYTES_WRITTEN_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_FEEDBACK_BITSTREAM_HAS_OVERRIDES_BIT_KHR-4]
}

const (
	_VideoEncodeFeedbackFlagBitsKHR_name_0 = "VIDEO_ENCODE_FEEDBACK_BITSTREAM_BUFFER_OFFSET_BIT_KHRVIDEO_ENCODE_FEEDBACK_BITSTREAM_BYTES_WRITTEN_BIT_KHR"
	_VideoEncodeFeedbackFlagBitsKHR_name_1 = "VIDEO_ENCODE_FEEDBACK_BITSTREAM_HAS_OVERRIDES_BIT_KHR"
)

var (
	_VideoEncodeFeedbackFlagBitsKHR_index_0 = [...]uint8{0, 53, 106}
)

func (i VideoEncodeFeedbackFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoEncodeFeedbackFlagBitsKHR_name_0[_VideoEncodeFeedbackFlagBitsKHR_index_0[i]:_VideoEncodeFeedbackFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeFeedbackFlagBitsKHR_name_1
	default:
		return "VideoEncodeFeedbackFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_WITH_QUANTIZATION_DELTA_MAP_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_WITH_EMPHASIS_MAP_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_INTRA_REFRESH_BIT_KHR-4]
}

const (
	_VideoEncodeFlagBitsKHR_name_0 = "VIDEO_ENCODE_WITH_QUANTIZATION_DELTA_MAP_BIT_KHRVIDEO_ENCODE_WITH_EMPHASIS_MAP_BIT_KHR"
	_VideoEncodeFlagBitsKHR_name_1 = "VIDEO_ENCODE_INTRA_REFRESH_BIT_KHR"
)

var (
	_VideoEncodeFlagBitsKHR_index_0 = [...]uint8{0, 48, 86}
)

func (i VideoEncodeFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoEncodeFlagBitsKHR_name_0[_VideoEncodeFlagBitsKHR_index_0[i]:_VideoEncodeFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeFlagBitsKHR_name_1
	default:
		return "VideoEncodeFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_H264_CAPABILITY_HRD_COMPLIANCE_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_H264_CAPABILITY_PREDICTION_WEIGHT_TABLE_GENERATED_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_H264_CAPABILITY_B_PICTURE_INTRA_REFRESH_BIT_KHR-1024]
	_ = x[VIDEO_ENCODE_H264_CAPABILITY_ROW_UNALIGNED_SLICE_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_H264_CAPABILITY_DIFFERENT_SLICE_TYPE_BIT_KHR-8]
	_ = x[VIDEO_ENCODE_H264_CAPABILITY_B_FRAME_IN_L0_LIST_BIT_KHR-16]
	_ = x[VIDEO_ENCODE_H264_CAPABILITY_B_FRAME_IN_L1_LIST_BIT_KHR-32]
	_ = x[VIDEO_ENCODE_H264_CAPABILITY_PER_PICTURE_TYPE_MIN_MAX_QP_BIT_KHR-64]
	_ = x[VIDEO_ENCODE_H264_CAPABILITY_PER_SLICE_CONSTANT_QP_BIT_KHR-128]
	_ = x[VIDEO_ENCODE_H264_CAPABILITY_GENERATE_PREFIX_NALU_BIT_KHR-256]
	_ = x[VIDEO_ENCODE_H264_CAPABILITY_MB_QP_DIFF_WRAPAROUND_BIT_KHR-512]
}

const (
	_VideoEncodeH264CapabilityFlagBitsKHR_name_0 = "VIDEO_ENCODE_H264_CAPABILITY_HRD_COMPLIANCE_BIT_KHRVIDEO_ENCODE_H264_CAPABILITY_PREDICTION_WEIGHT_TABLE_GENERATED_BIT_KHR"
	_VideoEncodeH264CapabilityFlagBitsKHR_name_1 = "VIDEO_ENCODE_H264_CAPABILITY_ROW_UNALIGNED_SLICE_BIT_KHR"
	_VideoEncodeH264CapabilityFlagBitsKHR_name_2 = "VIDEO_ENCODE_H264_CAPABILITY_DIFFERENT_SLICE_TYPE_BIT_KHR"
	_VideoEncodeH264CapabilityFlagBitsKHR_name_3 = "VIDEO_ENCODE_H264_CAPABILITY_B_FRAME_IN_L0_LIST_BIT_KHR"
	_VideoEncodeH264CapabilityFlagBitsKHR_name_4 = "VIDEO_ENCODE_H264_CAPABILITY_B_FRAME_IN_L1_LIST_BIT_KHR"
	_VideoEncodeH264CapabilityFlagBitsKHR_name_5 = "VIDEO_ENCODE_H264_CAPABILITY_PER_PICTURE_TYPE_MIN_MAX_QP_BIT_KHR"
	_VideoEncodeH264CapabilityFlagBitsKHR_name_6 = "VIDEO_ENCODE_H264_CAPABILITY_PER_SLICE_CONSTANT_QP_BIT_KHR"
	_VideoEncodeH264CapabilityFlagBitsKHR_name_7 = "VIDEO_ENCODE_H264_CAPABILITY_GENERATE_PREFIX_NALU_BIT_KHR"
	_VideoEncodeH264CapabilityFlagBitsKHR_name_8 = "VIDEO_ENCODE_H264_CAPABILITY_MB_QP_DIFF_WRAPAROUND_BIT_KHR"
	_VideoEncodeH264CapabilityFlagBitsKHR_name_9 = "VIDEO_ENCODE_H264_CAPABILITY_B_PICTURE_INTRA_REFRESH_BIT_KHR"
)

var (
	_VideoEncodeH264CapabilityFlagBitsKHR_index_0 = [...]uint8{0, 51, 121}
)

func (i VideoEncodeH264CapabilityFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoEncodeH264CapabilityFlagBitsKHR_name_0[_VideoEncodeH264CapabilityFlagBitsKHR_index_0[i]:_VideoEncodeH264CapabilityFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeH264CapabilityFlagBitsKHR_name_1
	case i == 8:
		return _VideoEncodeH264CapabilityFlagBitsKHR_name_2
	case i == 16:
		return _VideoEncodeH264CapabilityFlagBitsKHR_name_3
	case i == 32:
		return _VideoEncodeH264CapabilityFlagBitsKHR_name_4
	case i == 64:
		return _VideoEncodeH264CapabilityFlagBitsKHR_name_5
	case i == 128:
		return _VideoEncodeH264CapabilityFlagBitsKHR_name_6
	case i == 256:
		return _VideoEncodeH264CapabilityFlagBitsKHR_name_7
	case i == 512:
		return _VideoEncodeH264CapabilityFlagBitsKHR_name_8
	case i == 1024:
		return _VideoEncodeH264CapabilityFlagBitsKHR_name_9
	default:
		return "VideoEncodeH264CapabilityFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_H264_RATE_CONTROL_ATTEMPT_HRD_COMPLIANCE_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_H264_RATE_CONTROL_REGULAR_GOP_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_H264_RATE_CONTROL_REFERENCE_PATTERN_FLAT_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_H264_RATE_CONTROL_REFERENCE_PATTERN_DYADIC_BIT_KHR-8]
	_ = x[VIDEO_ENCODE_H264_RATE_CONTROL_TEMPORAL_LAYER_PATTERN_DYADIC_BIT_KHR-16]
}

const (
	_VideoEncodeH264RateControlFlagBitsKHR_name_0 = "VIDEO_ENCODE_H264_RATE_CONTROL_ATTEMPT_HRD_COMPLIANCE_BIT_KHRVIDEO_ENCODE_H264_RATE_CONTROL_REGULAR_GOP_BIT_KHR"
	_VideoEncodeH264RateControlFlagBitsKHR_name_1 = "VIDEO_ENCODE_H264_RATE_CONTROL_REFERENCE_PATTERN_FLAT_BIT_KHR"
	_VideoEncodeH264RateControlFlagBitsKHR_name_2 = "VIDEO_ENCODE_H264_RATE_CONTROL_REFERENCE_PATTERN_DYADIC_BIT_KHR"
	_VideoEncodeH264RateControlFlagBitsKHR_name_3 = "VIDEO_ENCODE_H264_RATE_CONTROL_TEMPORAL_LAYER_PATTERN_DYADIC_BIT_KHR"
)

var (
	_VideoEncodeH264RateControlFlagBitsKHR_index_0 = [...]uint8{0, 61, 111}
)

func (i VideoEncodeH264RateControlFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoEncodeH264RateControlFlagBitsKHR_name_0[_VideoEncodeH264RateControlFlagBitsKHR_index_0[i]:_VideoEncodeH264RateControlFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeH264RateControlFlagBitsKHR_name_1
	case i == 8:
		return _VideoEncodeH264RateControlFlagBitsKHR_name_2
	case i == 16:
		return _VideoEncodeH264RateControlFlagBitsKHR_name_3
	default:
		return "VideoEncodeH264RateControlFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_H264_STD_SEPARATE_COLOR_PLANE_FLAG_SET_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_H264_STD_QPPRIME_Y_ZERO_TRANSFORM_BYPASS_FLAG_SET_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_H264_STD_DIRECT_SPATIAL_MV_PRED_FLAG_UNSET_BIT_KHR-1024]
	_ = x[VIDEO_ENCODE_H264_STD_ENTROPY_CODING_MODE_FLAG_UNSET_BIT_KHR-2048]
	_ = x[VIDEO_ENCODE_H264_STD_ENTROPY_CODING_MODE_FLAG_SET_BIT_KHR-4096]
	_ = x[VIDEO_ENCODE_H264_STD_DIRECT_8X8_INFERENCE_FLAG_UNSET_BIT_KHR-8192]
	_ = x[VIDEO_ENCODE_H264_STD_CONSTRAINED_INTRA_PRED_FLAG_SET_BIT_KHR-16384]
	_ = x[VIDEO_ENCODE_H264_STD_DEBLOCKING_FILTER_DISABLED_BIT_KHR-32768]
	_ = x[VIDEO_ENCODE_H264_STD_DEBLOCKING_FILTER_ENABLED_BIT_KHR-65536]
	_ = x[VIDEO_ENCODE_H264_STD_DEBLOCKING_FILTER_PARTIAL_BIT_KHR-131072]
	_ = x[VIDEO_ENCODE_H264_STD_SLICE_QP_DELTA_BIT_KHR-524288]
	_ = x[VIDEO_ENCODE_H264_STD_SCALING_MATRIX_PRESENT_FLAG_SET_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_H264_STD_DIFFERENT_SLICE_QP_DELTA_BIT_KHR-1048576]
	_ = x[VIDEO_ENCODE_H264_STD_CHROMA_QP_INDEX_OFFSET_BIT_KHR-8]
	_ = x[VIDEO_ENCODE_H264_STD_SECOND_CHROMA_QP_INDEX_OFFSET_BIT_KHR-16]
	_ = x[VIDEO_ENCODE_H264_STD_PIC_INIT_QP_MINUS26_BIT_KHR-32]
	_ = x[VIDEO_ENCODE_H264_STD_WEIGHTED_PRED_FLAG_SET_BIT_KHR-64]
	_ = x[VIDEO_ENCODE_H264_STD_WEIGHTED_BIPRED_IDC_EXPLICIT_BIT_KHR-128]
	_ = x[VIDEO_ENCODE_H264_STD_WEIGHTED_BIPRED_IDC_IMPLICIT_BIT_KHR-256]
	_ = x[VIDEO_ENCODE_H264_STD_TRANSFORM_8X8_MODE_FLAG_SET_BIT_KHR-512]
}

const _VideoEncodeH264StdFlagBitsKHR_name = "VIDEO_ENCODE_H264_STD_SEPARATE_COLOR_PLANE_FLAG_SET_BIT_KHRVIDEO_ENCODE_H264_STD_QPPRIME_Y_ZERO_TRANSFORM_BYPASS_FLAG_SET_BIT_KHRVIDEO_ENCODE_H264_STD_SCALING_MATRIX_PRESENT_FLAG_SET_BIT_KHRVIDEO_ENCODE_H264_STD_CHROMA_QP_INDEX_OFFSET_BIT_KHRVIDEO_ENCODE_H264_STD_SECOND_CHROMA_QP_INDEX_OFFSET_BIT_KHRVIDEO_ENCODE_H264_STD_PIC_INIT_QP_MINUS26_BIT_KHRVIDEO_ENCODE_H264_STD_WEIGHTED_PRED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H264_STD_WEIGHTED_BIPRED_IDC_EXPLICIT_BIT_KHRVIDEO_ENCODE_H264_STD_WEIGHTED_BIPRED_IDC_IMPLICIT_BIT_KHRVIDEO_ENCODE_H264_STD_TRANSFORM_8X8_MODE_FLAG_SET_BIT_KHRVIDEO_ENCODE_H264_STD_DIRECT_SPATIAL_MV_PRED_FLAG_UNSET_BIT_KHRVIDEO_ENCODE_H264_STD_ENTROPY_CODING_MODE_FLAG_UNSET_BIT_KHRVIDEO_ENCODE_H264_STD_ENTROPY_CODING_MODE_FLAG_SET_BIT_KHRVIDEO_ENCODE_H264_STD_DIRECT_8X8_INFERENCE_FLAG_UNSET_BIT_KHRVIDEO_ENCODE_H264_STD_CONSTRAINED_INTRA_PRED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H264_STD_DEBLOCKING_FILTER_DISABLED_BIT_KHRVIDEO_ENCODE_H264_STD_DEBLOCKING_FILTER_ENABLED_BIT_KHRVIDEO_ENCODE_H264_STD_DEBLOCKING_FILTER_PARTIAL_BIT_KHRVIDEO_ENCODE_H264_STD_SLICE_QP_DELTA_BIT_KHRVIDEO_ENCODE_H264_STD_DIFFERENT_SLICE_QP_DELTA_BIT_KHR"

var _VideoEncodeH264StdFlagBitsKHR_map = map[VideoEncodeH264StdFlagBitsKHR]string{
	1:       _VideoEncodeH264StdFlagBitsKHR_name[0:59],
	2:       _VideoEncodeH264StdFlagBitsKHR_name[59:129],
	4:       _VideoEncodeH264StdFlagBitsKHR_name[129:190],
	8:       _VideoEncodeH264StdFlagBitsKHR_name[190:242],
	16:      _VideoEncodeH264StdFlagBitsKHR_name[242:301],
	32:      _VideoEncodeH264StdFlagBitsKHR_name[301:350],
	64:      _VideoEncodeH264StdFlagBitsKHR_name[350:402],
	128:     _VideoEncodeH264StdFlagBitsKHR_name[402:460],
	256:     _VideoEncodeH264StdFlagBitsKHR_name[460:518],
	512:     _VideoEncodeH264StdFlagBitsKHR_name[518:575],
	1024:    _VideoEncodeH264StdFlagBitsKHR_name[575:638],
	2048:    _VideoEncodeH264StdFlagBitsKHR_name[638:698],
	4096:    _VideoEncodeH264StdFlagBitsKHR_name[698:756],
	8192:    _VideoEncodeH264StdFlagBitsKHR_name[756:817],
	16384:   _VideoEncodeH264StdFlagBitsKHR_name[817:878],
	32768:   _VideoEncodeH264StdFlagBitsKHR_name[878:934],
	65536:   _VideoEncodeH264StdFlagBitsKHR_name[934:989],
	131072:  _VideoEncodeH264StdFlagBitsKHR_name[989:1044],
	524288:  _VideoEncodeH264StdFlagBitsKHR_name[1044:1088],
	1048576: _VideoEncodeH264StdFlagBitsKHR_name[1088:1142],
}

func (i VideoEncodeH264StdFlagBitsKHR) String() string {
	if str, ok := _VideoEncodeH264StdFlagBitsKHR_map[i]; ok {
		return str
	}
	return "VideoEncodeH264StdFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_H265_CAPABILITY_HRD_COMPLIANCE_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_H265_CAPABILITY_PREDICTION_WEIGHT_TABLE_GENERATED_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_H265_CAPABILITY_CU_QP_DIFF_WRAPAROUND_BIT_KHR-1024]
	_ = x[VIDEO_ENCODE_H265_CAPABILITY_B_PICTURE_INTRA_REFRESH_BIT_KHR-2048]
	_ = x[VIDEO_ENCODE_H265_CAPABILITY_ROW_UNALIGNED_SLICE_SEGMENT_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_H265_CAPABILITY_DIFFERENT_SLICE_SEGMENT_TYPE_BIT_KHR-8]
	_ = x[VIDEO_ENCODE_H265_CAPABILITY_B_FRAME_IN_L0_LIST_BIT_KHR-16]
	_ = x[VIDEO_ENCODE_H265_CAPABILITY_B_FRAME_IN_L1_LIST_BIT_KHR-32]
	_ = x[VIDEO_ENCODE_H265_CAPABILITY_PER_PICTURE_TYPE_MIN_MAX_QP_BIT_KHR-64]
	_ = x[VIDEO_ENCODE_H265_CAPABILITY_PER_SLICE_SEGMENT_CONSTANT_QP_BIT_KHR-128]
	_ = x[VIDEO_ENCODE_H265_CAPABILITY_MULTIPLE_TILES_PER_SLICE_SEGMENT_BIT_KHR-256]
	_ = x[VIDEO_ENCODE_H265_CAPABILITY_MULTIPLE_SLICE_SEGMENTS_PER_TILE_BIT_KHR-512]
}

const _VideoEncodeH265CapabilityFlagBitsKHR_name = "VIDEO_ENCODE_H265_CAPABILITY_HRD_COMPLIANCE_BIT_KHRVIDEO_ENCODE_H265_CAPABILITY_PREDICTION_WEIGHT_TABLE_GENERATED_BIT_KHRVIDEO_ENCODE_H265_CAPABILITY_ROW_UNALIGNED_SLICE_SEGMENT_BIT_KHRVIDEO_ENCODE_H265_CAPABILITY_DIFFERENT_SLICE_SEGMENT_TYPE_BIT_KHRVIDEO_ENCODE_H265_CAPABILITY_B_FRAME_IN_L0_LIST_BIT_KHRVIDEO_ENCODE_H265_CAPABILITY_B_FRAME_IN_L1_LIST_BIT_KHRVIDEO_ENCODE_H265_CAPABILITY_PER_PICTURE_TYPE_MIN_MAX_QP_BIT_KHRVIDEO_ENCODE_H265_CAPABILITY_PER_SLICE_SEGMENT_CONSTANT_QP_BIT_KHRVIDEO_ENCODE_H265_CAPABILITY_MULTIPLE_TILES_PER_SLICE_SEGMENT_BIT_KHRVIDEO_ENCODE_H265_CAPABILITY_MULTIPLE_SLICE_SEGMENTS_PER_TILE_BIT_KHRVIDEO_ENCODE_H265_CAPABILITY_CU_QP_DIFF_WRAPAROUND_BIT_KHRVIDEO_ENCODE_H265_CAPABILITY_B_PICTURE_INTRA_REFRESH_BIT_KHR"

var _VideoEncodeH265CapabilityFlagBitsKHR_map = map[VideoEncodeH265CapabilityFlagBitsKHR]string{
	1:    _VideoEncodeH265CapabilityFlagBitsKHR_name[0:51],
	2:    _VideoEncodeH265CapabilityFlagBitsKHR_name[51:121],
	4:    _VideoEncodeH265CapabilityFlagBitsKHR_name[121:185],
	8:    _VideoEncodeH265CapabilityFlagBitsKHR_name[185:250],
	16:   _VideoEncodeH265CapabilityFlagBitsKHR_name[250:305],
	32:   _VideoEncodeH265CapabilityFlagBitsKHR_name[305:360],
	64:   _VideoEncodeH265CapabilityFlagBitsKHR_name[360:424],
	128:  _VideoEncodeH265CapabilityFlagBitsKHR_name[424:490],
	256:  _VideoEncodeH265CapabilityFlagBitsKHR_name[490:559],
	512:  _VideoEncodeH265CapabilityFlagBitsKHR_name[559:628],
	1024: _VideoEncodeH265CapabilityFlagBitsKHR_name[628:686],
	2048: _VideoEncodeH265CapabilityFlagBitsKHR_name[686:746],
}

func (i VideoEncodeH265CapabilityFlagBitsKHR) String() string {
	if str, ok := _VideoEncodeH265CapabilityFlagBitsKHR_map[i]; ok {
		return str
	}
	return "VideoEncodeH265CapabilityFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_H265_CTB_SIZE_16_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_H265_CTB_SIZE_32_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_H265_CTB_SIZE_64_BIT_KHR-4]
}

const (
	_VideoEncodeH265CtbSizeFlagBitsKHR_name_0 = "VIDEO_ENCODE_H265_CTB_SIZE_16_BIT_KHRVIDEO_ENCODE_H265_CTB_SIZE_32_BIT_KHR"
	_VideoEncodeH265CtbSizeFlagBitsKHR_name_1 = "VIDEO_ENCODE_H265_CTB_SIZE_64_BIT_KHR"
)

var (
	_VideoEncodeH265CtbSizeFlagBitsKHR_index_0 = [...]uint8{0, 37, 74}
)

func (i VideoEncodeH265CtbSizeFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoEncodeH265CtbSizeFlagBitsKHR_name_0[_VideoEncodeH265CtbSizeFlagBitsKHR_index_0[i]:_VideoEncodeH265CtbSizeFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeH265CtbSizeFlagBitsKHR_name_1
	default:
		return "VideoEncodeH265CtbSizeFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_H265_RATE_CONTROL_ATTEMPT_HRD_COMPLIANCE_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_H265_RATE_CONTROL_REGULAR_GOP_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_H265_RATE_CONTROL_REFERENCE_PATTERN_FLAT_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_H265_RATE_CONTROL_REFERENCE_PATTERN_DYADIC_BIT_KHR-8]
	_ = x[VIDEO_ENCODE_H265_RATE_CONTROL_TEMPORAL_SUB_LAYER_PATTERN_DYADIC_BIT_KHR-16]
}

const (
	_VideoEncodeH265RateControlFlagBitsKHR_name_0 = "VIDEO_ENCODE_H265_RATE_CONTROL_ATTEMPT_HRD_COMPLIANCE_BIT_KHRVIDEO_ENCODE_H265_RATE_CONTROL_REGULAR_GOP_BIT_KHR"
	_VideoEncodeH265RateControlFlagBitsKHR_name_1 = "VIDEO_ENCODE_H265_RATE_CONTROL_REFERENCE_PATTERN_FLAT_BIT_KHR"
	_VideoEncodeH265RateControlFlagBitsKHR_name_2 = "VIDEO_ENCODE_H265_RATE_CONTROL_REFERENCE_PATTERN_DYADIC_BIT_KHR"
	_VideoEncodeH265RateControlFlagBitsKHR_name_3 = "VIDEO_ENCODE_H265_RATE_CONTROL_TEMPORAL_SUB_LAYER_PATTERN_DYADIC_BIT_KHR"
)

var (
	_VideoEncodeH265RateControlFlagBitsKHR_index_0 = [...]uint8{0, 61, 111}
)

func (i VideoEncodeH265RateControlFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoEncodeH265RateControlFlagBitsKHR_name_0[_VideoEncodeH265RateControlFlagBitsKHR_index_0[i]:_VideoEncodeH265RateControlFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeH265RateControlFlagBitsKHR_name_1
	case i == 8:
		return _VideoEncodeH265RateControlFlagBitsKHR_name_2
	case i == 16:
		return _VideoEncodeH265RateControlFlagBitsKHR_name_3
	default:
		return "VideoEncodeH265RateControlFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_H265_STD_SEPARATE_COLOR_PLANE_FLAG_SET_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_H265_STD_SAMPLE_ADAPTIVE_OFFSET_ENABLED_FLAG_SET_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_H265_STD_TRANSFORM_SKIP_ENABLED_FLAG_SET_BIT_KHR-1024]
	_ = x[VIDEO_ENCODE_H265_STD_TRANSFORM_SKIP_ENABLED_FLAG_UNSET_BIT_KHR-2048]
	_ = x[VIDEO_ENCODE_H265_STD_PPS_SLICE_CHROMA_QP_OFFSETS_PRESENT_FLAG_SET_BIT_KHR-4096]
	_ = x[VIDEO_ENCODE_H265_STD_TRANSQUANT_BYPASS_ENABLED_FLAG_SET_BIT_KHR-8192]
	_ = x[VIDEO_ENCODE_H265_STD_CONSTRAINED_INTRA_PRED_FLAG_SET_BIT_KHR-16384]
	_ = x[VIDEO_ENCODE_H265_STD_ENTROPY_CODING_SYNC_ENABLED_FLAG_SET_BIT_KHR-32768]
	_ = x[VIDEO_ENCODE_H265_STD_DEBLOCKING_FILTER_OVERRIDE_ENABLED_FLAG_SET_BIT_KHR-65536]
	_ = x[VIDEO_ENCODE_H265_STD_DEPENDENT_SLICE_SEGMENTS_ENABLED_FLAG_SET_BIT_KHR-131072]
	_ = x[VIDEO_ENCODE_H265_STD_DEPENDENT_SLICE_SEGMENT_FLAG_SET_BIT_KHR-262144]
	_ = x[VIDEO_ENCODE_H265_STD_SLICE_QP_DELTA_BIT_KHR-524288]
	_ = x[VIDEO_ENCODE_H265_STD_SCALING_LIST_DATA_PRESENT_FLAG_SET_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_H265_STD_DIFFERENT_SLICE_QP_DELTA_BIT_KHR-1048576]
	_ = x[VIDEO_ENCODE_H265_STD_PCM_ENABLED_FLAG_SET_BIT_KHR-8]
	_ = x[VIDEO_ENCODE_H265_STD_SPS_TEMPORAL_MVP_ENABLED_FLAG_SET_BIT_KHR-16]
	_ = x[VIDEO_ENCODE_H265_STD_INIT_QP_MINUS26_BIT_KHR-32]
	_ = x[VIDEO_ENCODE_H265_STD_WEIGHTED_PRED_FLAG_SET_BIT_KHR-64]
	_ = x[VIDEO_ENCODE_H265_STD_WEIGHTED_BIPRED_FLAG_SET_BIT_KHR-128]
	_ = x[VIDEO_ENCODE_H265_STD_LOG2_PARALLEL_MERGE_LEVEL_MINUS2_BIT_KHR-256]
	_ = x[VIDEO_ENCODE_H265_STD_SIGN_DATA_HIDING_ENABLED_FLAG_SET_BIT_KHR-512]
}

const _VideoEncodeH265StdFlagBitsKHR_name = "VIDEO_ENCODE_H265_STD_SEPARATE_COLOR_PLANE_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_SAMPLE_ADAPTIVE_OFFSET_ENABLED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_SCALING_LIST_DATA_PRESENT_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_PCM_ENABLED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_SPS_TEMPORAL_MVP_ENABLED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_INIT_QP_MINUS26_BIT_KHRVIDEO_ENCODE_H265_STD_WEIGHTED_PRED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_WEIGHTED_BIPRED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_LOG2_PARALLEL_MERGE_LEVEL_MINUS2_BIT_KHRVIDEO_ENCODE_H265_STD_SIGN_DATA_HIDING_ENABLED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_TRANSFORM_SKIP_ENABLED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_TRANSFORM_SKIP_ENABLED_FLAG_UNSET_BIT_KHRVIDEO_ENCODE_H265_STD_PPS_SLICE_CHROMA_QP_OFFSETS_PRESENT_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_TRANSQUANT_BYPASS_ENABLED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_CONSTRAINED_INTRA_PRED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_ENTROPY_CODING_SYNC_ENABLED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_DEBLOCKING_FILTER_OVERRIDE_ENABLED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_DEPENDENT_SLICE_SEGMENTS_ENABLED_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_DEPENDENT_SLICE_SEGMENT_FLAG_SET_BIT_KHRVIDEO_ENCODE_H265_STD_SLICE_QP_DELTA_BIT_KHRVIDEO_ENCODE_H265_STD_DIFFERENT_SLICE_QP_DELTA_BIT_KHR"

var _VideoEncodeH265StdFlagBitsKHR_map = map[VideoEncodeH265StdFlagBitsKHR]string{
	1:       _VideoEncodeH265StdFlagBitsKHR_name[0:59],
	2:       _VideoEncodeH265StdFlagBitsKHR_name[59:128],
	4:       _VideoEncodeH265StdFlagBitsKHR_name[128:192],
	8:       _VideoEncodeH265StdFlagBitsKHR_name[192:242],
	16:      _VideoEncodeH265StdFlagBitsKHR_name[242:305],
	32:      _VideoEncodeH265StdFlagBitsKHR_name[305:350],
	64:      _VideoEncodeH265StdFlagBitsKHR_name[350:402],
	128:     _VideoEncodeH265StdFlagBitsKHR_name[402:456],
	256:     _VideoEncodeH265StdFlagBitsKHR_name[456:518],
	512:     _VideoEncodeH265StdFlagBitsKHR_name[518:581],
	1024:    _VideoEncodeH265StdFlagBitsKHR_name[581:642],
	2048:    _VideoEncodeH265StdFlagBitsKHR_name[642:705],
	4096:    _VideoEncodeH265StdFlagBitsKHR_name[705:779],
	8192:    _VideoEncodeH265StdFlagBitsKHR_name[779:843],
	16384:   _VideoEncodeH265StdFlagBitsKHR_name[843:904],
	32768:   _VideoEncodeH265StdFlagBitsKHR_name[904:970],
	65536:   _VideoEncodeH265StdFlagBitsKHR_name[970:1043],
	131072:  _VideoEncodeH265StdFlagBitsKHR_name[1043:1114],
	262144:  _VideoEncodeH265StdFlagBitsKHR_name[1114:1176],
	524288:  _VideoEncodeH265StdFlagBitsKHR_name[1176:1220],
	1048576: _VideoEncodeH265StdFlagBitsKHR_name[1220:1274],
}

func (i VideoEncodeH265StdFlagBitsKHR) String() string {
	if str, ok := _VideoEncodeH265StdFlagBitsKHR_map[i]; ok {
		return str
	}
	return "VideoEncodeH265StdFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_H265_TRANSFORM_BLOCK_SIZE_4_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_H265_TRANSFORM_BLOCK_SIZE_8_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_H265_TRANSFORM_BLOCK_SIZE_16_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_H265_TRANSFORM_BLOCK_SIZE_32_BIT_KHR-8]
}

const (
	_VideoEncodeH265TransformBlockSizeFlagBitsKHR_name_0 = "VIDEO_ENCODE_H265_TRANSFORM_BLOCK_SIZE_4_BIT_KHRVIDEO_ENCODE_H265_TRANSFORM_BLOCK_SIZE_8_BIT_KHR"
	_VideoEncodeH265TransformBlockSizeFlagBitsKHR_name_1 = "VIDEO_ENCODE_H265_TRANSFORM_BLOCK_SIZE_16_BIT_KHR"
	_VideoEncodeH265TransformBlockSizeFlagBitsKHR_name_2 = "VIDEO_ENCODE_H265_TRANSFORM_BLOCK_SIZE_32_BIT_KHR"
)

var (
	_VideoEncodeH265TransformBlockSizeFlagBitsKHR_index_0 = [...]uint8{0, 48, 96}
)

func (i VideoEncodeH265TransformBlockSizeFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoEncodeH265TransformBlockSizeFlagBitsKHR_name_0[_VideoEncodeH265TransformBlockSizeFlagBitsKHR_index_0[i]:_VideoEncodeH265TransformBlockSizeFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeH265TransformBlockSizeFlagBitsKHR_name_1
	case i == 8:
		return _VideoEncodeH265TransformBlockSizeFlagBitsKHR_name_2
	default:
		return "VideoEncodeH265TransformBlockSizeFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_INTRA_REFRESH_MODE_NONE_KHR-0]
	_ = x[VIDEO_ENCODE_INTRA_REFRESH_MODE_PER_PICTURE_PARTITION_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_INTRA_REFRESH_MODE_BLOCK_BASED_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_INTRA_REFRESH_MODE_BLOCK_ROW_BASED_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_INTRA_REFRESH_MODE_BLOCK_COLUMN_BASED_BIT_KHR-8]
}

const (
	_VideoEncodeIntraRefreshModeFlagBitsKHR_name_0 = "VIDEO_ENCODE_INTRA_REFRESH_MODE_NONE_KHRVIDEO_ENCODE_INTRA_REFRESH_MODE_PER_PICTURE_PARTITION_BIT_KHRVIDEO_ENCODE_INTRA_REFRESH_MODE_BLOCK_BASED_BIT_KHR"
	_VideoEncodeIntraRefreshModeFlagBitsKHR_name_1 = "VIDEO_ENCODE_INTRA_REFRESH_MODE_BLOCK_ROW_BASED_BIT_KHR"
	_VideoEncodeIntraRefreshModeFlagBitsKHR_name_2 = "VIDEO_ENCODE_INTRA_REFRESH_MODE_BLOCK_COLUMN_BASED_BIT_KHR"
)

var (
	_VideoEncodeIntraRefreshModeFlagBitsKHR_index_0 = [...]uint8{0, 40, 101, 152}
)

func (i VideoEncodeIntraRefreshModeFlagBitsKHR) String() string {
	switch {
	case i <= 2:
		return _VideoEncodeIntraRefreshModeFlagBitsKHR_name_0[_VideoEncodeIntraRefreshModeFlagBitsKHR_index_0[i]:_VideoEncodeIntraRefreshModeFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeIntraRefreshModeFlagBitsKHR_name_1
	case i == 8:
		return _VideoEncodeIntraRefreshModeFlagBitsKHR_name_2
	default:
		return "VideoEncodeIntraRefreshModeFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_RATE_CONTROL_MODE_DEFAULT_KHR-0]
	_ = x[VIDEO_ENCODE_RATE_CONTROL_MODE_DISABLED_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_RATE_CONTROL_MODE_CBR_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_RATE_CONTROL_MODE_VBR_BIT_KHR-4]
}

const (
	_VideoEncodeRateControlModeFlagBitsKHR_name_0 = "VIDEO_ENCODE_RATE_CONTROL_MODE_DEFAULT_KHRVIDEO_ENCODE_RATE_CONTROL_MODE_DISABLED_BIT_KHRVIDEO_ENCODE_RATE_CONTROL_MODE_CBR_BIT_KHR"
	_VideoEncodeRateControlModeFlagBitsKHR_name_1 = "VIDEO_ENCODE_RATE_CONTROL_MODE_VBR_BIT_KHR"
)

var (
	_VideoEncodeRateControlModeFlagBitsKHR_index_0 = [...]uint8{0, 42, 89, 131}
)

func (i VideoEncodeRateControlModeFlagBitsKHR) String() string {
	switch {
	case i <= 2:
		return _VideoEncodeRateControlModeFlagBitsKHR_name_0[_VideoEncodeRateControlModeFlagBitsKHR_index_0[i]:_VideoEncodeRateControlModeFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeRateControlModeFlagBitsKHR_name_1
	default:
		return "VideoEncodeRateControlModeFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_RGB_CHROMA_OFFSET_COSITED_EVEN_BIT_VALVE-1]
	_ = x[VIDEO_ENCODE_RGB_CHROMA_OFFSET_MIDPOINT_BIT_VALVE-2]
}

const _VideoEncodeRgbChromaOffsetFlagBitsVALVE_name = "VIDEO_ENCODE_RGB_CHROMA_OFFSET_COSITED_EVEN_BIT_VALVEVIDEO_ENCODE_RGB_CHROMA_OFFSET_MIDPOINT_BIT_VALVE"

var _VideoEncodeRgbChromaOffsetFlagBitsVALVE_index = [...]uint8{0, 53, 102}

func (i VideoEncodeRgbChromaOffsetFlagBitsVALVE) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_VideoEncodeRgbChromaOffsetFlagBitsVALVE_index)-1 {
		return "VideoEncodeRgbChromaOffsetFlagBitsVALVE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoEncodeRgbChromaOffsetFlagBitsVALVE_name[_VideoEncodeRgbChromaOffsetFlagBitsVALVE_index[idx]:_VideoEncodeRgbChromaOffsetFlagBitsVALVE_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_RGB_MODEL_CONVERSION_RGB_IDENTITY_BIT_VALVE-1]
	_ = x[VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_IDENTITY_BIT_VALVE-2]
	_ = x[VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_709_BIT_VALVE-4]
	_ = x[VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_601_BIT_VALVE-8]
	_ = x[VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_2020_BIT_VALVE-16]
}

const (
	_VideoEncodeRgbModelConversionFlagBitsVALVE_name_0 = "VIDEO_ENCODE_RGB_MODEL_CONVERSION_RGB_IDENTITY_BIT_VALVEVIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_IDENTITY_BIT_VALVE"
	_VideoEncodeRgbModelConversionFlagBitsVALVE_name_1 = "VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_709_BIT_VALVE"
	_VideoEncodeRgbModelConversionFlagBitsVALVE_name_2 = "VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_601_BIT_VALVE"
	_VideoEncodeRgbModelConversionFlagBitsVALVE_name_3 = "VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_2020_BIT_VALVE"
)

var (
	_VideoEncodeRgbModelConversionFlagBitsVALVE_index_0 = [...]uint8{0, 56, 114}
)

func (i VideoEncodeRgbModelConversionFlagBitsVALVE) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoEncodeRgbModelConversionFlagBitsVALVE_name_0[_VideoEncodeRgbModelConversionFlagBitsVALVE_index_0[i]:_VideoEncodeRgbModelConversionFlagBitsVALVE_index_0[i+1]]
	case i == 4:
		return _VideoEncodeRgbModelConversionFlagBitsVALVE_name_1
	case i == 8:
		return _VideoEncodeRgbModelConversionFlagBitsVALVE_name_2
	case i == 16:
		return _VideoEncodeRgbModelConversionFlagBitsVALVE_name_3
	default:
		return "VideoEncodeRgbModelConversionFlagBitsVALVE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_RGB_RANGE_COMPRESSION_FULL_RANGE_BIT_VALVE-1]
	_ = x[VIDEO_ENCODE_RGB_RANGE_COMPRESSION_NARROW_RANGE_BIT_VALVE-2]
}

const _VideoEncodeRgbRangeCompressionFlagBitsVALVE_name = "VIDEO_ENCODE_RGB_RANGE_COMPRESSION_FULL_RANGE_BIT_VALVEVIDEO_ENCODE_RGB_RANGE_COMPRESSION_NARROW_RANGE_BIT_VALVE"

var _VideoEncodeRgbRangeCompressionFlagBitsVALVE_index = [...]uint8{0, 55, 112}

func (i VideoEncodeRgbRangeCompressionFlagBitsVALVE) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_VideoEncodeRgbRangeCompressionFlagBitsVALVE_index)-1 {
		return "VideoEncodeRgbRangeCompressionFlagBitsVALVE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoEncodeRgbRangeCompressionFlagBitsVALVE_name[_VideoEncodeRgbRangeCompressionFlagBitsVALVE_index[idx]:_VideoEncodeRgbRangeCompressionFlagBitsVALVE_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_TUNING_MODE_DEFAULT_KHR-0]
	_ = x[VIDEO_ENCODE_TUNING_MODE_HIGH_QUALITY_KHR-1]
	_ = x[VIDEO_ENCODE_TUNING_MODE_LOW_LATENCY_KHR-2]
	_ = x[VIDEO_ENCODE_TUNING_MODE_ULTRA_LOW_LATENCY_KHR-3]
	_ = x[VIDEO_ENCODE_TUNING_MODE_LOSSLESS_KHR-4]
}

const _VideoEncodeTuningModeKHR_name = "VIDEO_ENCODE_TUNING_MODE_DEFAULT_KHRVIDEO_ENCODE_TUNING_MODE_HIGH_QUALITY_KHRVIDEO_ENCODE_TUNING_MODE_LOW_LATENCY_KHRVIDEO_ENCODE_TUNING_MODE_ULTRA_LOW_LATENCY_KHRVIDEO_ENCODE_TUNING_MODE_LOSSLESS_KHR"

var _VideoEncodeTuningModeKHR_index = [...]uint8{0, 36, 77, 117, 163, 200}

func (i VideoEncodeTuningModeKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_VideoEncodeTuningModeKHR_index)-1 {
		return "VideoEncodeTuningModeKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoEncodeTuningModeKHR_name[_VideoEncodeTuningModeKHR_index[idx]:_VideoEncodeTuningModeKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_USAGE_DEFAULT_KHR-0]
	_ = x[VIDEO_ENCODE_USAGE_TRANSCODING_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_USAGE_STREAMING_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_USAGE_RECORDING_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_USAGE_CONFERENCING_BIT_KHR-8]
}

const (
	_VideoEncodeUsageFlagBitsKHR_name_0 = "VIDEO_ENCODE_USAGE_DEFAULT_KHRVIDEO_ENCODE_USAGE_TRANSCODING_BIT_KHRVIDEO_ENCODE_USAGE_STREAMING_BIT_KHR"
	_VideoEncodeUsageFlagBitsKHR_name_1 = "VIDEO_ENCODE_USAGE_RECORDING_BIT_KHR"
	_VideoEncodeUsageFlagBitsKHR_name_2 = "VIDEO_ENCODE_USAGE_CONFERENCING_BIT_KHR"
)

var (
	_VideoEncodeUsageFlagBitsKHR_index_0 = [...]uint8{0, 30, 68, 104}
)

func (i VideoEncodeUsageFlagBitsKHR) String() string {
	switch {
	case i <= 2:
		return _VideoEncodeUsageFlagBitsKHR_name_0[_VideoEncodeUsageFlagBitsKHR_index_0[i]:_VideoEncodeUsageFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeUsageFlagBitsKHR_name_1
	case i == 8:
		return _VideoEncodeUsageFlagBitsKHR_name_2
	default:
		return "VideoEncodeUsageFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_SESSION_CREATE_PROTECTED_CONTENT_BIT_KHR-1]
	_ = x[VIDEO_SESSION_CREATE_ALLOW_ENCODE_PARAMETER_OPTIMIZATIONS_BIT_KHR-2]
	_ = x[VIDEO_SESSION_CREATE_INLINE_QUERIES_BIT_KHR-4]
	_ = x[VIDEO_SESSION_CREATE_ALLOW_ENCODE_QUANTIZATION_DELTA_MAP_BIT_KHR-8]
	_ = x[VIDEO_SESSION_CREATE_ALLOW_ENCODE_EMPHASIS_MAP_BIT_KHR-16]
	_ = x[VIDEO_SESSION_CREATE_INLINE_SESSION_PARAMETERS_BIT_KHR-32]
}

const (
	_VideoSessionCreateFlagBitsKHR_name_0 = "VIDEO_SESSION_CREATE_PROTECTED_CONTENT_BIT_KHRVIDEO_SESSION_CREATE_ALLOW_ENCODE_PARAMETER_OPTIMIZATIONS_BIT_KHR"
	_VideoSessionCreateFlagBitsKHR_name_1 = "VIDEO_SESSION_CREATE_INLINE_QUERIES_BIT_KHR"
	_VideoSessionCreateFlagBitsKHR_name_2 = "VIDEO_SESSION_CREATE_ALLOW_ENCODE_QUANTIZATION_DELTA_MAP_BIT_KHR"
	_VideoSessionCreateFlagBitsKHR_name_3 = "VIDEO_SESSION_CREATE_ALLOW_ENCODE_EMPHASIS_MAP_BIT_KHR"
	_VideoSessionCreateFlagBitsKHR_name_4 = "VIDEO_SESSION_CREATE_INLINE_SESSION_PARAMETERS_BIT_KHR"
)

var (
	_VideoSessionCreateFlagBitsKHR_index_0 = [...]uint8{0, 46, 111}
)

func (i VideoSessionCreateFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoSessionCreateFlagBitsKHR_name_0[_VideoSessionCreateFlagBitsKHR_index_0[i]:_VideoSessionCreateFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoSessionCreateFlagBitsKHR_name_1
	case i == 8:
		return _VideoSessionCreateFlagBitsKHR_name_2
	case i == 16:
		return _VideoSessionCreateFlagBitsKHR_name_3
	case i == 32:
		return _VideoSessionCreateFlagBitsKHR_name_4
	default:
		return "VideoSessionCreateFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_SESSION_PARAMETERS_CREATE_QUANTIZATION_MAP_COMPATIBLE_BIT_KHR-1]
}

const _VideoSessionParametersCreateFlagBitsKHR_name = "VIDEO_SESSION_PARAMETERS_CREATE_QUANTIZATION_MAP_COMPATIBLE_BIT_KHR"

var _VideoSessionParametersCreateFlagBitsKHR_index = [...]uint8{0, 67}

func (i VideoSessionParametersCreateFlagBitsKHR) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_VideoSessionParametersCreateFlagBitsKHR_index)-1 {
		return "VideoSessionParametersCreateFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoSessionParametersCreateFlagBitsKHR_name[_VideoSessionParametersCreateFlagBitsKHR_index[idx]:_VideoSessionParametersCreateFlagBitsKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NV-0]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NV-1]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NV-2]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NV-3]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NV-4]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NV-5]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NV-6]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV-7]
}

const _ViewportCoordinateSwizzleNV_name = "VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NVVIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NVVIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NVVIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV"

var _ViewportCoordinateSwizzleNV_index = [...]uint16{0, 41, 82, 123, 164, 205, 246, 287, 328}

func (i ViewportCoordinateSwizzleNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ViewportCoordinateSwizzleNV_index)-1 {
		return "ViewportCoordinateSwizzleNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ViewportCoordinateSwizzleNV_name[_ViewportCoordinateSwizzleNV_index[idx]:_ViewportCoordinateSwizzleNV_index[idx+1]]
}
