// Code generated by "stringer -output=enum_string_0.go -type=AccelerationStructureBuildTypeKHR,AccelerationStructureCompatibilityKHR,AccelerationStructureCreateFlagBitsKHR,AccelerationStructureMemoryRequirementsTypeNV,AccelerationStructureMotionInstanceTypeNV,AccelerationStructureTypeKHR,AccessFlagBits,AccessFlagBits2,AccessFlagBits3KHR,AddressCopyFlagBitsKHR,AntiLagModeAMD,AntiLagStageAMD,AttachmentDescriptionFlagBits,AttachmentLoadOp,AttachmentStoreOp,BlendFactor,BlendOp,BlendOverlapEXT,BlockMatchWindowCompareModeQCOM,BorderColor,BufferCreateFlagBits,BufferUsageFlagBits,BufferUsageFlagBits2,BuildAccelerationStructureFlagBitsKHR,BuildAccelerationStructureModeKHR,BuildMicromapFlagBitsEXT,BuildMicromapModeEXT,ChromaLocation,ClusterAccelerationStructureAddressResolutionFlagBitsNV,ClusterAccelerationStructureClusterFlagBitsNV,ClusterAccelerationStructureGeometryFlagBitsNV"; DO NOT EDIT.

package vk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACCELERATION_STRUCTURE_BUILD_TYPE_HOST_KHR-0]
	_ = x[ACCELERATION_STRUCTURE_BUILD_TYPE_DEVICE_KHR-1]
	_ = x[ACCELERATION_STRUCTURE_BUILD_TYPE_HOST_OR_DEVICE_KHR-2]
}

const _AccelerationStructureBuildTypeKHR_name = "ACCELERATION_STRUCTURE_BUILD_TYPE_HOST_KHRACCELERATION_STRUCTURE_BUILD_TYPE_DEVICE_KHRACCELERATION_STRUCTURE_BUILD_TYPE_HOST_OR_DEVICE_KHR"

var _AccelerationStructureBuildTypeKHR_index = [...]uint8{0, 42, 86, 138}

func (i AccelerationStructureBuildTypeKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AccelerationStructureBuildTypeKHR_index)-1 {
		return "AccelerationStructureBuildTypeKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccelerationStructureBuildTypeKHR_name[_AccelerationStructureBuildTypeKHR_index[idx]:_AccelerationStructureBuildTypeKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACCELERATION_STRUCTURE_COMPATIBILITY_COMPATIBLE_KHR-0]
	_ = x[ACCELERATION_STRUCTURE_COMPATIBILITY_INCOMPATIBLE_KHR-1]
}

const _AccelerationStructureCompatibilityKHR_name = "ACCELERATION_STRUCTURE_COMPATIBILITY_COMPATIBLE_KHRACCELERATION_STRUCTURE_COMPATIBILITY_INCOMPATIBLE_KHR"

var _AccelerationStructureCompatibilityKHR_index = [...]uint8{0, 51, 104}

func (i AccelerationStructureCompatibilityKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AccelerationStructureCompatibilityKHR_index)-1 {
		return "AccelerationStructureCompatibilityKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccelerationStructureCompatibilityKHR_name[_AccelerationStructureCompatibilityKHR_index[idx]:_AccelerationStructureCompatibilityKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACCELERATION_STRUCTURE_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_KHR-1]
	_ = x[ACCELERATION_STRUCTURE_CREATE_MOTION_BIT_NV-4]
	_ = x[ACCELERATION_STRUCTURE_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT-8]
}

const (
	_AccelerationStructureCreateFlagBitsKHR_name_0 = "ACCELERATION_STRUCTURE_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_KHR"
	_AccelerationStructureCreateFlagBitsKHR_name_1 = "ACCELERATION_STRUCTURE_CREATE_MOTION_BIT_NV"
	_AccelerationStructureCreateFlagBitsKHR_name_2 = "ACCELERATION_STRUCTURE_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT"
)

func (i AccelerationStructureCreateFlagBitsKHR) String() string {
	switch {
	case i == 1:
		return _AccelerationStructureCreateFlagBitsKHR_name_0
	case i == 4:
		return _AccelerationStructureCreateFlagBitsKHR_name_1
	case i == 8:
		return _AccelerationStructureCreateFlagBitsKHR_name_2
	default:
		return "AccelerationStructureCreateFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_OBJECT_NV-0]
	_ = x[ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_BUILD_SCRATCH_NV-1]
	_ = x[ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_UPDATE_SCRATCH_NV-2]
}

const _AccelerationStructureMemoryRequirementsTypeNV_name = "ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_OBJECT_NVACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_BUILD_SCRATCH_NVACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_UPDATE_SCRATCH_NV"

var _AccelerationStructureMemoryRequirementsTypeNV_index = [...]uint8{0, 57, 121, 186}

func (i AccelerationStructureMemoryRequirementsTypeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AccelerationStructureMemoryRequirementsTypeNV_index)-1 {
		return "AccelerationStructureMemoryRequirementsTypeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccelerationStructureMemoryRequirementsTypeNV_name[_AccelerationStructureMemoryRequirementsTypeNV_index[idx]:_AccelerationStructureMemoryRequirementsTypeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACCELERATION_STRUCTURE_MOTION_INSTANCE_TYPE_STATIC_NV-0]
	_ = x[ACCELERATION_STRUCTURE_MOTION_INSTANCE_TYPE_MATRIX_MOTION_NV-1]
	_ = x[ACCELERATION_STRUCTURE_MOTION_INSTANCE_TYPE_SRT_MOTION_NV-2]
}

const _AccelerationStructureMotionInstanceTypeNV_name = "ACCELERATION_STRUCTURE_MOTION_INSTANCE_TYPE_STATIC_NVACCELERATION_STRUCTURE_MOTION_INSTANCE_TYPE_MATRIX_MOTION_NVACCELERATION_STRUCTURE_MOTION_INSTANCE_TYPE_SRT_MOTION_NV"

var _AccelerationStructureMotionInstanceTypeNV_index = [...]uint8{0, 53, 113, 170}

func (i AccelerationStructureMotionInstanceTypeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AccelerationStructureMotionInstanceTypeNV_index)-1 {
		return "AccelerationStructureMotionInstanceTypeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccelerationStructureMotionInstanceTypeNV_name[_AccelerationStructureMotionInstanceTypeNV_index[idx]:_AccelerationStructureMotionInstanceTypeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR-0]
	_ = x[ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR-1]
	_ = x[ACCELERATION_STRUCTURE_TYPE_GENERIC_KHR-2]
	_ = x[ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_NV-1]
	_ = x[ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_NV-0]
}

const _AccelerationStructureTypeKHR_name = "ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHRACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHRACCELERATION_STRUCTURE_TYPE_GENERIC_KHR"

var _AccelerationStructureTypeKHR_index = [...]uint8{0, 41, 85, 124}

func (i AccelerationStructureTypeKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AccelerationStructureTypeKHR_index)-1 {
		return "AccelerationStructureTypeKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccelerationStructureTypeKHR_name[_AccelerationStructureTypeKHR_index[idx]:_AccelerationStructureTypeKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACCESS_NONE-0]
	_ = x[ACCESS_INDIRECT_COMMAND_READ_BIT-1]
	_ = x[ACCESS_INDEX_READ_BIT-2]
	_ = x[ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT-1024]
	_ = x[ACCESS_TRANSFER_READ_BIT-2048]
	_ = x[ACCESS_TRANSFER_WRITE_BIT-4096]
	_ = x[ACCESS_HOST_READ_BIT-8192]
	_ = x[ACCESS_HOST_WRITE_BIT-16384]
	_ = x[ACCESS_MEMORY_READ_BIT-32768]
	_ = x[ACCESS_MEMORY_WRITE_BIT-65536]
	_ = x[ACCESS_COMMAND_PREPROCESS_READ_BIT_EXT-131072]
	_ = x[ACCESS_COMMAND_PREPROCESS_WRITE_BIT_EXT-262144]
	_ = x[ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT-524288]
	_ = x[ACCESS_VERTEX_ATTRIBUTE_READ_BIT-4]
	_ = x[ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT-1048576]
	_ = x[ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR-2097152]
	_ = x[ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR-4194304]
	_ = x[ACCESS_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR-8388608]
	_ = x[ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT-16777216]
	_ = x[ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT-33554432]
	_ = x[ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT-67108864]
	_ = x[ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT-134217728]
	_ = x[ACCESS_UNIFORM_READ_BIT-8]
	_ = x[ACCESS_INPUT_ATTACHMENT_READ_BIT-16]
	_ = x[ACCESS_SHADER_READ_BIT-32]
	_ = x[ACCESS_SHADER_WRITE_BIT-64]
	_ = x[ACCESS_COLOR_ATTACHMENT_READ_BIT-128]
	_ = x[ACCESS_COLOR_ATTACHMENT_WRITE_BIT-256]
	_ = x[ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT-512]
	_ = x[ACCESS_ACCELERATION_STRUCTURE_READ_BIT_NV-2097152]
	_ = x[ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_NV-4194304]
	_ = x[ACCESS_COMMAND_PREPROCESS_READ_BIT_NV-131072]
	_ = x[ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV-262144]
	_ = x[ACCESS_SHADING_RATE_IMAGE_READ_BIT_NV-8388608]
	_ = x[ACCESS_NONE_KHR-0]
}

const _AccessFlagBits_name = "ACCESS_NONEACCESS_INDIRECT_COMMAND_READ_BITACCESS_INDEX_READ_BITACCESS_VERTEX_ATTRIBUTE_READ_BITACCESS_UNIFORM_READ_BITACCESS_INPUT_ATTACHMENT_READ_BITACCESS_SHADER_READ_BITACCESS_SHADER_WRITE_BITACCESS_COLOR_ATTACHMENT_READ_BITACCESS_COLOR_ATTACHMENT_WRITE_BITACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BITACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BITACCESS_TRANSFER_READ_BITACCESS_TRANSFER_WRITE_BITACCESS_HOST_READ_BITACCESS_HOST_WRITE_BITACCESS_MEMORY_READ_BITACCESS_MEMORY_WRITE_BITACCESS_COMMAND_PREPROCESS_READ_BIT_EXTACCESS_COMMAND_PREPROCESS_WRITE_BIT_EXTACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXTACCESS_CONDITIONAL_RENDERING_READ_BIT_EXTACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHRACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHRACCESS_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHRACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXTACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXTACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXTACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT"

var _AccessFlagBits_map = map[AccessFlagBits]string{
	0:         _AccessFlagBits_name[0:11],
	1:         _AccessFlagBits_name[11:43],
	2:         _AccessFlagBits_name[43:64],
	4:         _AccessFlagBits_name[64:96],
	8:         _AccessFlagBits_name[96:119],
	16:        _AccessFlagBits_name[119:151],
	32:        _AccessFlagBits_name[151:173],
	64:        _AccessFlagBits_name[173:196],
	128:       _AccessFlagBits_name[196:228],
	256:       _AccessFlagBits_name[228:261],
	512:       _AccessFlagBits_name[261:301],
	1024:      _AccessFlagBits_name[301:342],
	2048:      _AccessFlagBits_name[342:366],
	4096:      _AccessFlagBits_name[366:391],
	8192:      _AccessFlagBits_name[391:411],
	16384:     _AccessFlagBits_name[411:432],
	32768:     _AccessFlagBits_name[432:454],
	65536:     _AccessFlagBits_name[454:477],
	131072:    _AccessFlagBits_name[477:515],
	262144:    _AccessFlagBits_name[515:554],
	524288:    _AccessFlagBits_name[554:602],
	1048576:   _AccessFlagBits_name[602:643],
	2097152:   _AccessFlagBits_name[643:685],
	4194304:   _AccessFlagBits_name[685:728],
	8388608:   _AccessFlagBits_name[728:780],
	16777216:  _AccessFlagBits_name[780:820],
	33554432:  _AccessFlagBits_name[820:859],
	67108864:  _AccessFlagBits_name[859:905],
	134217728: _AccessFlagBits_name[905:952],
}

func (i AccessFlagBits) String() string {
	if str, ok := _AccessFlagBits_map[i]; ok {
		return str
	}
	return "AccessFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACCESS_2_NONE-0]
	_ = x[ACCESS_2_INDIRECT_COMMAND_READ_BIT-1]
	_ = x[ACCESS_2_INDEX_READ_BIT-2]
	_ = x[ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT-1024]
	_ = x[ACCESS_2_TRANSFER_READ_BIT-2048]
	_ = x[ACCESS_2_TRANSFER_WRITE_BIT-4096]
	_ = x[ACCESS_2_HOST_READ_BIT-8192]
	_ = x[ACCESS_2_HOST_WRITE_BIT-16384]
	_ = x[ACCESS_2_MEMORY_READ_BIT-32768]
	_ = x[ACCESS_2_MEMORY_WRITE_BIT-65536]
	_ = x[ACCESS_2_COMMAND_PREPROCESS_READ_BIT_EXT-131072]
	_ = x[ACCESS_2_COMMAND_PREPROCESS_WRITE_BIT_EXT-262144]
	_ = x[ACCESS_2_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT-524288]
	_ = x[ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT-4]
	_ = x[ACCESS_2_CONDITIONAL_RENDERING_READ_BIT_EXT-1048576]
	_ = x[ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHR-2097152]
	_ = x[ACCESS_2_ACCELERATION_STRUCTURE_WRITE_BIT_KHR-4194304]
	_ = x[ACCESS_2_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR-8388608]
	_ = x[ACCESS_2_FRAGMENT_DENSITY_MAP_READ_BIT_EXT-16777216]
	_ = x[ACCESS_2_TRANSFORM_FEEDBACK_WRITE_BIT_EXT-33554432]
	_ = x[ACCESS_2_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT-67108864]
	_ = x[ACCESS_2_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT-134217728]
	_ = x[ACCESS_2_UNIFORM_READ_BIT-8]
	_ = x[ACCESS_2_SHADER_SAMPLED_READ_BIT-4294967296]
	_ = x[ACCESS_2_SHADER_STORAGE_READ_BIT-8589934592]
	_ = x[ACCESS_2_SHADER_STORAGE_WRITE_BIT-17179869184]
	_ = x[ACCESS_2_VIDEO_DECODE_READ_BIT_KHR-34359738368]
	_ = x[ACCESS_2_VIDEO_DECODE_WRITE_BIT_KHR-68719476736]
	_ = x[ACCESS_2_VIDEO_ENCODE_READ_BIT_KHR-137438953472]
	_ = x[ACCESS_2_VIDEO_ENCODE_WRITE_BIT_KHR-274877906944]
	_ = x[ACCESS_2_INVOCATION_MASK_READ_BIT_HUAWEI-549755813888]
	_ = x[ACCESS_2_INPUT_ATTACHMENT_READ_BIT-16]
	_ = x[ACCESS_2_SHADER_BINDING_TABLE_READ_BIT_KHR-1099511627776]
	_ = x[ACCESS_2_DESCRIPTOR_BUFFER_READ_BIT_EXT-2199023255552]
	_ = x[ACCESS_2_OPTICAL_FLOW_READ_BIT_NV-4398046511104]
	_ = x[ACCESS_2_OPTICAL_FLOW_WRITE_BIT_NV-8796093022208]
	_ = x[ACCESS_2_MICROMAP_READ_BIT_EXT-17592186044416]
	_ = x[ACCESS_2_MICROMAP_WRITE_BIT_EXT-35184372088832]
	_ = x[ACCESS_2_DATA_GRAPH_READ_BIT_ARM-140737488355328]
	_ = x[ACCESS_2_DATA_GRAPH_WRITE_BIT_ARM-281474976710656]
	_ = x[ACCESS_2_SHADER_READ_BIT-32]
	_ = x[ACCESS_2_SHADER_TILE_ATTACHMENT_READ_BIT_QCOM-2251799813685248]
	_ = x[ACCESS_2_SHADER_TILE_ATTACHMENT_WRITE_BIT_QCOM-4503599627370496]
	_ = x[ACCESS_2_SHADER_WRITE_BIT-64]
	_ = x[ACCESS_2_COLOR_ATTACHMENT_READ_BIT-128]
	_ = x[ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT-256]
	_ = x[ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT-512]
	_ = x[ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_NV-2097152]
	_ = x[ACCESS_2_ACCELERATION_STRUCTURE_WRITE_BIT_NV-4194304]
	_ = x[ACCESS_2_COLOR_ATTACHMENT_READ_BIT_KHR-128]
	_ = x[ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT_KHR-256]
	_ = x[ACCESS_2_COMMAND_PREPROCESS_READ_BIT_NV-131072]
	_ = x[ACCESS_2_COMMAND_PREPROCESS_WRITE_BIT_NV-262144]
	_ = x[ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT_KHR-512]
	_ = x[ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT_KHR-1024]
	_ = x[ACCESS_2_SHADING_RATE_IMAGE_READ_BIT_NV-8388608]
	_ = x[ACCESS_2_HOST_READ_BIT_KHR-8192]
	_ = x[ACCESS_2_HOST_WRITE_BIT_KHR-16384]
	_ = x[ACCESS_2_INDEX_READ_BIT_KHR-2]
	_ = x[ACCESS_2_INDIRECT_COMMAND_READ_BIT_KHR-1]
	_ = x[ACCESS_2_INPUT_ATTACHMENT_READ_BIT_KHR-16]
	_ = x[ACCESS_2_MEMORY_READ_BIT_KHR-32768]
	_ = x[ACCESS_2_MEMORY_WRITE_BIT_KHR-65536]
	_ = x[ACCESS_2_NONE_KHR-0]
	_ = x[ACCESS_2_SHADER_READ_BIT_KHR-32]
	_ = x[ACCESS_2_SHADER_SAMPLED_READ_BIT_KHR-4294967296]
	_ = x[ACCESS_2_SHADER_STORAGE_READ_BIT_KHR-8589934592]
	_ = x[ACCESS_2_SHADER_STORAGE_WRITE_BIT_KHR-17179869184]
	_ = x[ACCESS_2_SHADER_WRITE_BIT_KHR-64]
	_ = x[ACCESS_2_TRANSFER_READ_BIT_KHR-2048]
	_ = x[ACCESS_2_TRANSFER_WRITE_BIT_KHR-4096]
	_ = x[ACCESS_2_UNIFORM_READ_BIT_KHR-8]
	_ = x[ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT_KHR-4]
}

const _AccessFlagBits2_name = "ACCESS_2_NONEACCESS_2_INDIRECT_COMMAND_READ_BITACCESS_2_INDEX_READ_BITACCESS_2_VERTEX_ATTRIBUTE_READ_BITACCESS_2_UNIFORM_READ_BITACCESS_2_INPUT_ATTACHMENT_READ_BITACCESS_2_SHADER_READ_BITACCESS_2_SHADER_WRITE_BITACCESS_2_COLOR_ATTACHMENT_READ_BITACCESS_2_COLOR_ATTACHMENT_WRITE_BITACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BITACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BITACCESS_2_TRANSFER_READ_BITACCESS_2_TRANSFER_WRITE_BITACCESS_2_HOST_READ_BITACCESS_2_HOST_WRITE_BITACCESS_2_MEMORY_READ_BITACCESS_2_MEMORY_WRITE_BITACCESS_2_COMMAND_PREPROCESS_READ_BIT_EXTACCESS_2_COMMAND_PREPROCESS_WRITE_BIT_EXTACCESS_2_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXTACCESS_2_CONDITIONAL_RENDERING_READ_BIT_EXTACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHRACCESS_2_ACCELERATION_STRUCTURE_WRITE_BIT_KHRACCESS_2_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHRACCESS_2_FRAGMENT_DENSITY_MAP_READ_BIT_EXTACCESS_2_TRANSFORM_FEEDBACK_WRITE_BIT_EXTACCESS_2_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXTACCESS_2_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXTACCESS_2_SHADER_SAMPLED_READ_BITACCESS_2_SHADER_STORAGE_READ_BITACCESS_2_SHADER_STORAGE_WRITE_BITACCESS_2_VIDEO_DECODE_READ_BIT_KHRACCESS_2_VIDEO_DECODE_WRITE_BIT_KHRACCESS_2_VIDEO_ENCODE_READ_BIT_KHRACCESS_2_VIDEO_ENCODE_WRITE_BIT_KHRACCESS_2_INVOCATION_MASK_READ_BIT_HUAWEIACCESS_2_SHADER_BINDING_TABLE_READ_BIT_KHRACCESS_2_DESCRIPTOR_BUFFER_READ_BIT_EXTACCESS_2_OPTICAL_FLOW_READ_BIT_NVACCESS_2_OPTICAL_FLOW_WRITE_BIT_NVACCESS_2_MICROMAP_READ_BIT_EXTACCESS_2_MICROMAP_WRITE_BIT_EXTACCESS_2_DATA_GRAPH_READ_BIT_ARMACCESS_2_DATA_GRAPH_WRITE_BIT_ARMACCESS_2_SHADER_TILE_ATTACHMENT_READ_BIT_QCOMACCESS_2_SHADER_TILE_ATTACHMENT_WRITE_BIT_QCOM"

var _AccessFlagBits2_map = map[AccessFlagBits2]string{
	0:                _AccessFlagBits2_name[0:13],
	1:                _AccessFlagBits2_name[13:47],
	2:                _AccessFlagBits2_name[47:70],
	4:                _AccessFlagBits2_name[70:104],
	8:                _AccessFlagBits2_name[104:129],
	16:               _AccessFlagBits2_name[129:163],
	32:               _AccessFlagBits2_name[163:187],
	64:               _AccessFlagBits2_name[187:212],
	128:              _AccessFlagBits2_name[212:246],
	256:              _AccessFlagBits2_name[246:281],
	512:              _AccessFlagBits2_name[281:323],
	1024:             _AccessFlagBits2_name[323:366],
	2048:             _AccessFlagBits2_name[366:392],
	4096:             _AccessFlagBits2_name[392:419],
	8192:             _AccessFlagBits2_name[419:441],
	16384:            _AccessFlagBits2_name[441:464],
	32768:            _AccessFlagBits2_name[464:488],
	65536:            _AccessFlagBits2_name[488:513],
	131072:           _AccessFlagBits2_name[513:553],
	262144:           _AccessFlagBits2_name[553:594],
	524288:           _AccessFlagBits2_name[594:644],
	1048576:          _AccessFlagBits2_name[644:687],
	2097152:          _AccessFlagBits2_name[687:731],
	4194304:          _AccessFlagBits2_name[731:776],
	8388608:          _AccessFlagBits2_name[776:830],
	16777216:         _AccessFlagBits2_name[830:872],
	33554432:         _AccessFlagBits2_name[872:913],
	67108864:         _AccessFlagBits2_name[913:961],
	134217728:        _AccessFlagBits2_name[961:1010],
	4294967296:       _AccessFlagBits2_name[1010:1042],
	8589934592:       _AccessFlagBits2_name[1042:1074],
	17179869184:      _AccessFlagBits2_name[1074:1107],
	34359738368:      _AccessFlagBits2_name[1107:1141],
	68719476736:      _AccessFlagBits2_name[1141:1176],
	137438953472:     _AccessFlagBits2_name[1176:1210],
	274877906944:     _AccessFlagBits2_name[1210:1245],
	549755813888:     _AccessFlagBits2_name[1245:1285],
	1099511627776:    _AccessFlagBits2_name[1285:1327],
	2199023255552:    _AccessFlagBits2_name[1327:1366],
	4398046511104:    _AccessFlagBits2_name[1366:1399],
	8796093022208:    _AccessFlagBits2_name[1399:1433],
	17592186044416:   _AccessFlagBits2_name[1433:1463],
	35184372088832:   _AccessFlagBits2_name[1463:1494],
	140737488355328:  _AccessFlagBits2_name[1494:1526],
	281474976710656:  _AccessFlagBits2_name[1526:1559],
	2251799813685248: _AccessFlagBits2_name[1559:1604],
	4503599627370496: _AccessFlagBits2_name[1604:1650],
}

func (i AccessFlagBits2) String() string {
	if str, ok := _AccessFlagBits2_map[i]; ok {
		return str
	}
	return "AccessFlagBits2(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACCESS_3_NONE_KHR-0]
}

const _AccessFlagBits3KHR_name = "ACCESS_3_NONE_KHR"

var _AccessFlagBits3KHR_index = [...]uint8{0, 17}

func (i AccessFlagBits3KHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AccessFlagBits3KHR_index)-1 {
		return "AccessFlagBits3KHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccessFlagBits3KHR_name[_AccessFlagBits3KHR_index[idx]:_AccessFlagBits3KHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ADDRESS_COPY_DEVICE_LOCAL_BIT_KHR-1]
	_ = x[ADDRESS_COPY_SPARSE_BIT_KHR-2]
	_ = x[ADDRESS_COPY_PROTECTED_BIT_KHR-4]
}

const (
	_AddressCopyFlagBitsKHR_name_0 = "ADDRESS_COPY_DEVICE_LOCAL_BIT_KHRADDRESS_COPY_SPARSE_BIT_KHR"
	_AddressCopyFlagBitsKHR_name_1 = "ADDRESS_COPY_PROTECTED_BIT_KHR"
)

var (
	_AddressCopyFlagBitsKHR_index_0 = [...]uint8{0, 33, 60}
)

func (i AddressCopyFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _AddressCopyFlagBitsKHR_name_0[_AddressCopyFlagBitsKHR_index_0[i]:_AddressCopyFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _AddressCopyFlagBitsKHR_name_1
	default:
		return "AddressCopyFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ANTI_LAG_MODE_DRIVER_CONTROL_AMD-0]
	_ = x[ANTI_LAG_MODE_ON_AMD-1]
	_ = x[ANTI_LAG_MODE_OFF_AMD-2]
}

const _AntiLagModeAMD_name = "ANTI_LAG_MODE_DRIVER_CONTROL_AMDANTI_LAG_MODE_ON_AMDANTI_LAG_MODE_OFF_AMD"

var _AntiLagModeAMD_index = [...]uint8{0, 32, 52, 73}

func (i AntiLagModeAMD) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AntiLagModeAMD_index)-1 {
		return "AntiLagModeAMD(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AntiLagModeAMD_name[_AntiLagModeAMD_index[idx]:_AntiLagModeAMD_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ANTI_LAG_STAGE_INPUT_AMD-0]
	_ = x[ANTI_LAG_STAGE_PRESENT_AMD-1]
}

const _AntiLagStageAMD_name = "ANTI_LAG_STAGE_INPUT_AMDANTI_LAG_STAGE_PRESENT_AMD"

var _AntiLagStageAMD_index = [...]uint8{0, 24, 50}

func (i AntiLagStageAMD) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AntiLagStageAMD_index)-1 {
		return "AntiLagStageAMD(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AntiLagStageAMD_name[_AntiLagStageAMD_index[idx]:_AntiLagStageAMD_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT-1]
}

const _AttachmentDescriptionFlagBits_name = "ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT"

var _AttachmentDescriptionFlagBits_index = [...]uint8{0, 36}

func (i AttachmentDescriptionFlagBits) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_AttachmentDescriptionFlagBits_index)-1 {
		return "AttachmentDescriptionFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AttachmentDescriptionFlagBits_name[_AttachmentDescriptionFlagBits_index[idx]:_AttachmentDescriptionFlagBits_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ATTACHMENT_LOAD_OP_LOAD-0]
	_ = x[ATTACHMENT_LOAD_OP_CLEAR-1]
	_ = x[ATTACHMENT_LOAD_OP_DONT_CARE-2]
	_ = x[ATTACHMENT_LOAD_OP_NONE-1000400000]
	_ = x[ATTACHMENT_LOAD_OP_NONE_KHR-1000400000]
	_ = x[ATTACHMENT_LOAD_OP_NONE_EXT-1000400000]
}

const (
	_AttachmentLoadOp_name_0 = "ATTACHMENT_LOAD_OP_LOADATTACHMENT_LOAD_OP_CLEARATTACHMENT_LOAD_OP_DONT_CARE"
	_AttachmentLoadOp_name_1 = "ATTACHMENT_LOAD_OP_NONE"
)

var (
	_AttachmentLoadOp_index_0 = [...]uint8{0, 23, 47, 75}
)

func (i AttachmentLoadOp) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _AttachmentLoadOp_name_0[_AttachmentLoadOp_index_0[i]:_AttachmentLoadOp_index_0[i+1]]
	case i == 1000400000:
		return _AttachmentLoadOp_name_1
	default:
		return "AttachmentLoadOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ATTACHMENT_STORE_OP_STORE-0]
	_ = x[ATTACHMENT_STORE_OP_DONT_CARE-1]
	_ = x[ATTACHMENT_STORE_OP_NONE-1000301000]
	_ = x[ATTACHMENT_STORE_OP_NONE_EXT-1000301000]
	_ = x[ATTACHMENT_STORE_OP_NONE_QCOM-1000301000]
	_ = x[ATTACHMENT_STORE_OP_NONE_KHR-1000301000]
}

const (
	_AttachmentStoreOp_name_0 = "ATTACHMENT_STORE_OP_STOREATTACHMENT_STORE_OP_DONT_CARE"
	_AttachmentStoreOp_name_1 = "ATTACHMENT_STORE_OP_NONE"
)

var (
	_AttachmentStoreOp_index_0 = [...]uint8{0, 25, 54}
)

func (i AttachmentStoreOp) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _AttachmentStoreOp_name_0[_AttachmentStoreOp_index_0[i]:_AttachmentStoreOp_index_0[i+1]]
	case i == 1000301000:
		return _AttachmentStoreOp_name_1
	default:
		return "AttachmentStoreOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BLEND_FACTOR_ZERO-0]
	_ = x[BLEND_FACTOR_ONE-1]
	_ = x[BLEND_FACTOR_SRC_COLOR-2]
	_ = x[BLEND_FACTOR_ONE_MINUS_SRC_COLOR-3]
	_ = x[BLEND_FACTOR_DST_COLOR-4]
	_ = x[BLEND_FACTOR_ONE_MINUS_DST_COLOR-5]
	_ = x[BLEND_FACTOR_SRC_ALPHA-6]
	_ = x[BLEND_FACTOR_ONE_MINUS_SRC_ALPHA-7]
	_ = x[BLEND_FACTOR_DST_ALPHA-8]
	_ = x[BLEND_FACTOR_ONE_MINUS_DST_ALPHA-9]
	_ = x[BLEND_FACTOR_CONSTANT_COLOR-10]
	_ = x[BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR-11]
	_ = x[BLEND_FACTOR_CONSTANT_ALPHA-12]
	_ = x[BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA-13]
	_ = x[BLEND_FACTOR_SRC_ALPHA_SATURATE-14]
	_ = x[BLEND_FACTOR_SRC1_COLOR-15]
	_ = x[BLEND_FACTOR_ONE_MINUS_SRC1_COLOR-16]
	_ = x[BLEND_FACTOR_SRC1_ALPHA-17]
	_ = x[BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA-18]
}

const _BlendFactor_name = "BLEND_FACTOR_ZEROBLEND_FACTOR_ONEBLEND_FACTOR_SRC_COLORBLEND_FACTOR_ONE_MINUS_SRC_COLORBLEND_FACTOR_DST_COLORBLEND_FACTOR_ONE_MINUS_DST_COLORBLEND_FACTOR_SRC_ALPHABLEND_FACTOR_ONE_MINUS_SRC_ALPHABLEND_FACTOR_DST_ALPHABLEND_FACTOR_ONE_MINUS_DST_ALPHABLEND_FACTOR_CONSTANT_COLORBLEND_FACTOR_ONE_MINUS_CONSTANT_COLORBLEND_FACTOR_CONSTANT_ALPHABLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHABLEND_FACTOR_SRC_ALPHA_SATURATEBLEND_FACTOR_SRC1_COLORBLEND_FACTOR_ONE_MINUS_SRC1_COLORBLEND_FACTOR_SRC1_ALPHABLEND_FACTOR_ONE_MINUS_SRC1_ALPHA"

var _BlendFactor_index = [...]uint16{0, 17, 33, 55, 87, 109, 141, 163, 195, 217, 249, 276, 313, 340, 377, 408, 431, 464, 487, 520}

func (i BlendFactor) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BlendFactor_index)-1 {
		return "BlendFactor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BlendFactor_name[_BlendFactor_index[idx]:_BlendFactor_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BLEND_OP_ADD-0]
	_ = x[BLEND_OP_SUBTRACT-1]
	_ = x[BLEND_OP_REVERSE_SUBTRACT-2]
	_ = x[BLEND_OP_MIN-3]
	_ = x[BLEND_OP_MAX-4]
	_ = x[BLEND_OP_ZERO_EXT-1000148000]
	_ = x[BLEND_OP_SRC_EXT-1000148001]
	_ = x[BLEND_OP_DST_EXT-1000148002]
	_ = x[BLEND_OP_SRC_OVER_EXT-1000148003]
	_ = x[BLEND_OP_DST_OVER_EXT-1000148004]
	_ = x[BLEND_OP_SRC_IN_EXT-1000148005]
	_ = x[BLEND_OP_DST_IN_EXT-1000148006]
	_ = x[BLEND_OP_SRC_OUT_EXT-1000148007]
	_ = x[BLEND_OP_DST_OUT_EXT-1000148008]
	_ = x[BLEND_OP_SRC_ATOP_EXT-1000148009]
	_ = x[BLEND_OP_DST_ATOP_EXT-1000148010]
	_ = x[BLEND_OP_XOR_EXT-1000148011]
	_ = x[BLEND_OP_MULTIPLY_EXT-1000148012]
	_ = x[BLEND_OP_SCREEN_EXT-1000148013]
	_ = x[BLEND_OP_OVERLAY_EXT-1000148014]
	_ = x[BLEND_OP_DARKEN_EXT-1000148015]
	_ = x[BLEND_OP_LIGHTEN_EXT-1000148016]
	_ = x[BLEND_OP_COLORDODGE_EXT-1000148017]
	_ = x[BLEND_OP_COLORBURN_EXT-1000148018]
	_ = x[BLEND_OP_HARDLIGHT_EXT-1000148019]
	_ = x[BLEND_OP_SOFTLIGHT_EXT-1000148020]
	_ = x[BLEND_OP_DIFFERENCE_EXT-1000148021]
	_ = x[BLEND_OP_EXCLUSION_EXT-1000148022]
	_ = x[BLEND_OP_INVERT_EXT-1000148023]
	_ = x[BLEND_OP_INVERT_RGB_EXT-1000148024]
	_ = x[BLEND_OP_LINEARDODGE_EXT-1000148025]
	_ = x[BLEND_OP_LINEARBURN_EXT-1000148026]
	_ = x[BLEND_OP_VIVIDLIGHT_EXT-1000148027]
	_ = x[BLEND_OP_LINEARLIGHT_EXT-1000148028]
	_ = x[BLEND_OP_PINLIGHT_EXT-1000148029]
	_ = x[BLEND_OP_HARDMIX_EXT-1000148030]
	_ = x[BLEND_OP_HSL_HUE_EXT-1000148031]
	_ = x[BLEND_OP_HSL_SATURATION_EXT-1000148032]
	_ = x[BLEND_OP_HSL_COLOR_EXT-1000148033]
	_ = x[BLEND_OP_HSL_LUMINOSITY_EXT-1000148034]
	_ = x[BLEND_OP_PLUS_EXT-1000148035]
	_ = x[BLEND_OP_PLUS_CLAMPED_EXT-1000148036]
	_ = x[BLEND_OP_PLUS_CLAMPED_ALPHA_EXT-1000148037]
	_ = x[BLEND_OP_PLUS_DARKER_EXT-1000148038]
	_ = x[BLEND_OP_MINUS_EXT-1000148039]
	_ = x[BLEND_OP_MINUS_CLAMPED_EXT-1000148040]
	_ = x[BLEND_OP_CONTRAST_EXT-1000148041]
	_ = x[BLEND_OP_INVERT_OVG_EXT-1000148042]
	_ = x[BLEND_OP_RED_EXT-1000148043]
	_ = x[BLEND_OP_GREEN_EXT-1000148044]
	_ = x[BLEND_OP_BLUE_EXT-1000148045]
}

const (
	_BlendOp_name_0 = "BLEND_OP_ADDBLEND_OP_SUBTRACTBLEND_OP_REVERSE_SUBTRACTBLEND_OP_MINBLEND_OP_MAX"
	_BlendOp_name_1 = "BLEND_OP_ZERO_EXTBLEND_OP_SRC_EXTBLEND_OP_DST_EXTBLEND_OP_SRC_OVER_EXTBLEND_OP_DST_OVER_EXTBLEND_OP_SRC_IN_EXTBLEND_OP_DST_IN_EXTBLEND_OP_SRC_OUT_EXTBLEND_OP_DST_OUT_EXTBLEND_OP_SRC_ATOP_EXTBLEND_OP_DST_ATOP_EXTBLEND_OP_XOR_EXTBLEND_OP_MULTIPLY_EXTBLEND_OP_SCREEN_EXTBLEND_OP_OVERLAY_EXTBLEND_OP_DARKEN_EXTBLEND_OP_LIGHTEN_EXTBLEND_OP_COLORDODGE_EXTBLEND_OP_COLORBURN_EXTBLEND_OP_HARDLIGHT_EXTBLEND_OP_SOFTLIGHT_EXTBLEND_OP_DIFFERENCE_EXTBLEND_OP_EXCLUSION_EXTBLEND_OP_INVERT_EXTBLEND_OP_INVERT_RGB_EXTBLEND_OP_LINEARDODGE_EXTBLEND_OP_LINEARBURN_EXTBLEND_OP_VIVIDLIGHT_EXTBLEND_OP_LINEARLIGHT_EXTBLEND_OP_PINLIGHT_EXTBLEND_OP_HARDMIX_EXTBLEND_OP_HSL_HUE_EXTBLEND_OP_HSL_SATURATION_EXTBLEND_OP_HSL_COLOR_EXTBLEND_OP_HSL_LUMINOSITY_EXTBLEND_OP_PLUS_EXTBLEND_OP_PLUS_CLAMPED_EXTBLEND_OP_PLUS_CLAMPED_ALPHA_EXTBLEND_OP_PLUS_DARKER_EXTBLEND_OP_MINUS_EXTBLEND_OP_MINUS_CLAMPED_EXTBLEND_OP_CONTRAST_EXTBLEND_OP_INVERT_OVG_EXTBLEND_OP_RED_EXTBLEND_OP_GREEN_EXTBLEND_OP_BLUE_EXT"
)

var (
	_BlendOp_index_0 = [...]uint8{0, 12, 29, 54, 66, 78}
	_BlendOp_index_1 = [...]uint16{0, 17, 33, 49, 70, 91, 110, 129, 149, 169, 190, 211, 227, 248, 267, 287, 306, 326, 349, 371, 393, 415, 438, 460, 479, 502, 526, 549, 572, 596, 617, 637, 657, 684, 706, 733, 750, 775, 806, 830, 848, 874, 895, 918, 934, 952, 969}
)

func (i BlendOp) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _BlendOp_name_0[_BlendOp_index_0[i]:_BlendOp_index_0[i+1]]
	case 1000148000 <= i && i <= 1000148045:
		i -= 1000148000
		return _BlendOp_name_1[_BlendOp_index_1[i]:_BlendOp_index_1[i+1]]
	default:
		return "BlendOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BLEND_OVERLAP_UNCORRELATED_EXT-0]
	_ = x[BLEND_OVERLAP_DISJOINT_EXT-1]
	_ = x[BLEND_OVERLAP_CONJOINT_EXT-2]
}

const _BlendOverlapEXT_name = "BLEND_OVERLAP_UNCORRELATED_EXTBLEND_OVERLAP_DISJOINT_EXTBLEND_OVERLAP_CONJOINT_EXT"

var _BlendOverlapEXT_index = [...]uint8{0, 30, 56, 82}

func (i BlendOverlapEXT) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BlendOverlapEXT_index)-1 {
		return "BlendOverlapEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BlendOverlapEXT_name[_BlendOverlapEXT_index[idx]:_BlendOverlapEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BLOCK_MATCH_WINDOW_COMPARE_MODE_MIN_QCOM-0]
	_ = x[BLOCK_MATCH_WINDOW_COMPARE_MODE_MAX_QCOM-1]
}

const _BlockMatchWindowCompareModeQCOM_name = "BLOCK_MATCH_WINDOW_COMPARE_MODE_MIN_QCOMBLOCK_MATCH_WINDOW_COMPARE_MODE_MAX_QCOM"

var _BlockMatchWindowCompareModeQCOM_index = [...]uint8{0, 40, 80}

func (i BlockMatchWindowCompareModeQCOM) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BlockMatchWindowCompareModeQCOM_index)-1 {
		return "BlockMatchWindowCompareModeQCOM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BlockMatchWindowCompareModeQCOM_name[_BlockMatchWindowCompareModeQCOM_index[idx]:_BlockMatchWindowCompareModeQCOM_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BORDER_COLOR_FLOAT_TRANSPARENT_BLACK-0]
	_ = x[BORDER_COLOR_INT_TRANSPARENT_BLACK-1]
	_ = x[BORDER_COLOR_FLOAT_OPAQUE_BLACK-2]
	_ = x[BORDER_COLOR_INT_OPAQUE_BLACK-3]
	_ = x[BORDER_COLOR_FLOAT_OPAQUE_WHITE-4]
	_ = x[BORDER_COLOR_INT_OPAQUE_WHITE-5]
	_ = x[BORDER_COLOR_FLOAT_CUSTOM_EXT-1000287003]
	_ = x[BORDER_COLOR_INT_CUSTOM_EXT-1000287004]
}

const (
	_BorderColor_name_0 = "BORDER_COLOR_FLOAT_TRANSPARENT_BLACKBORDER_COLOR_INT_TRANSPARENT_BLACKBORDER_COLOR_FLOAT_OPAQUE_BLACKBORDER_COLOR_INT_OPAQUE_BLACKBORDER_COLOR_FLOAT_OPAQUE_WHITEBORDER_COLOR_INT_OPAQUE_WHITE"
	_BorderColor_name_1 = "BORDER_COLOR_FLOAT_CUSTOM_EXTBORDER_COLOR_INT_CUSTOM_EXT"
)

var (
	_BorderColor_index_0 = [...]uint8{0, 36, 70, 101, 130, 161, 190}
	_BorderColor_index_1 = [...]uint8{0, 29, 56}
)

func (i BorderColor) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _BorderColor_name_0[_BorderColor_index_0[i]:_BorderColor_index_0[i+1]]
	case 1000287003 <= i && i <= 1000287004:
		i -= 1000287003
		return _BorderColor_name_1[_BorderColor_index_1[i]:_BorderColor_index_1[i+1]]
	default:
		return "BorderColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BUFFER_CREATE_SPARSE_BINDING_BIT-1]
	_ = x[BUFFER_CREATE_SPARSE_RESIDENCY_BIT-2]
	_ = x[BUFFER_CREATE_SPARSE_ALIASED_BIT-4]
	_ = x[BUFFER_CREATE_PROTECTED_BIT-8]
	_ = x[BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT-16]
	_ = x[BUFFER_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT-32]
	_ = x[BUFFER_CREATE_VIDEO_PROFILE_INDEPENDENT_BIT_KHR-64]
	_ = x[BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_KHR-16]
	_ = x[BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_EXT-16]
}

const (
	_BufferCreateFlagBits_name_0 = "BUFFER_CREATE_SPARSE_BINDING_BITBUFFER_CREATE_SPARSE_RESIDENCY_BIT"
	_BufferCreateFlagBits_name_1 = "BUFFER_CREATE_SPARSE_ALIASED_BIT"
	_BufferCreateFlagBits_name_2 = "BUFFER_CREATE_PROTECTED_BIT"
	_BufferCreateFlagBits_name_3 = "BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT"
	_BufferCreateFlagBits_name_4 = "BUFFER_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT"
	_BufferCreateFlagBits_name_5 = "BUFFER_CREATE_VIDEO_PROFILE_INDEPENDENT_BIT_KHR"
)

var (
	_BufferCreateFlagBits_index_0 = [...]uint8{0, 32, 66}
)

func (i BufferCreateFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _BufferCreateFlagBits_name_0[_BufferCreateFlagBits_index_0[i]:_BufferCreateFlagBits_index_0[i+1]]
	case i == 4:
		return _BufferCreateFlagBits_name_1
	case i == 8:
		return _BufferCreateFlagBits_name_2
	case i == 16:
		return _BufferCreateFlagBits_name_3
	case i == 32:
		return _BufferCreateFlagBits_name_4
	case i == 64:
		return _BufferCreateFlagBits_name_5
	default:
		return "BufferCreateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BUFFER_USAGE_TRANSFER_SRC_BIT-1]
	_ = x[BUFFER_USAGE_TRANSFER_DST_BIT-2]
	_ = x[BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR-1024]
	_ = x[BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT-2048]
	_ = x[BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT-4096]
	_ = x[BUFFER_USAGE_VIDEO_DECODE_SRC_BIT_KHR-8192]
	_ = x[BUFFER_USAGE_VIDEO_DECODE_DST_BIT_KHR-16384]
	_ = x[BUFFER_USAGE_VIDEO_ENCODE_DST_BIT_KHR-32768]
	_ = x[BUFFER_USAGE_VIDEO_ENCODE_SRC_BIT_KHR-65536]
	_ = x[BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT-131072]
	_ = x[BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR-524288]
	_ = x[BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT-4]
	_ = x[BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR-1048576]
	_ = x[BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT-2097152]
	_ = x[BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT-4194304]
	_ = x[BUFFER_USAGE_MICROMAP_BUILD_INPUT_READ_ONLY_BIT_EXT-8388608]
	_ = x[BUFFER_USAGE_MICROMAP_STORAGE_BIT_EXT-16777216]
	_ = x[BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT-67108864]
	_ = x[BUFFER_USAGE_TILE_MEMORY_BIT_QCOM-134217728]
	_ = x[BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT-8]
	_ = x[BUFFER_USAGE_UNIFORM_BUFFER_BIT-16]
	_ = x[BUFFER_USAGE_STORAGE_BUFFER_BIT-32]
	_ = x[BUFFER_USAGE_INDEX_BUFFER_BIT-64]
	_ = x[BUFFER_USAGE_VERTEX_BUFFER_BIT-128]
	_ = x[BUFFER_USAGE_INDIRECT_BUFFER_BIT-256]
	_ = x[BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT-512]
	_ = x[BUFFER_USAGE_RAY_TRACING_BIT_NV-1024]
	_ = x[BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT_KHR-131072]
	_ = x[BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT_EXT-131072]
}

const _BufferUsageFlagBits_name = "BUFFER_USAGE_TRANSFER_SRC_BITBUFFER_USAGE_TRANSFER_DST_BITBUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BITBUFFER_USAGE_STORAGE_TEXEL_BUFFER_BITBUFFER_USAGE_UNIFORM_BUFFER_BITBUFFER_USAGE_STORAGE_BUFFER_BITBUFFER_USAGE_INDEX_BUFFER_BITBUFFER_USAGE_VERTEX_BUFFER_BITBUFFER_USAGE_INDIRECT_BUFFER_BITBUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXTBUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHRBUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXTBUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXTBUFFER_USAGE_VIDEO_DECODE_SRC_BIT_KHRBUFFER_USAGE_VIDEO_DECODE_DST_BIT_KHRBUFFER_USAGE_VIDEO_ENCODE_DST_BIT_KHRBUFFER_USAGE_VIDEO_ENCODE_SRC_BIT_KHRBUFFER_USAGE_SHADER_DEVICE_ADDRESS_BITBUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHRBUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHRBUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXTBUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXTBUFFER_USAGE_MICROMAP_BUILD_INPUT_READ_ONLY_BIT_EXTBUFFER_USAGE_MICROMAP_STORAGE_BIT_EXTBUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXTBUFFER_USAGE_TILE_MEMORY_BIT_QCOM"

var _BufferUsageFlagBits_map = map[BufferUsageFlagBits]string{
	1:         _BufferUsageFlagBits_name[0:29],
	2:         _BufferUsageFlagBits_name[29:58],
	4:         _BufferUsageFlagBits_name[58:95],
	8:         _BufferUsageFlagBits_name[95:132],
	16:        _BufferUsageFlagBits_name[132:163],
	32:        _BufferUsageFlagBits_name[163:194],
	64:        _BufferUsageFlagBits_name[194:223],
	128:       _BufferUsageFlagBits_name[223:253],
	256:       _BufferUsageFlagBits_name[253:285],
	512:       _BufferUsageFlagBits_name[285:327],
	1024:      _BufferUsageFlagBits_name[327:368],
	2048:      _BufferUsageFlagBits_name[368:414],
	4096:      _BufferUsageFlagBits_name[414:468],
	8192:      _BufferUsageFlagBits_name[468:505],
	16384:     _BufferUsageFlagBits_name[505:542],
	32768:     _BufferUsageFlagBits_name[542:579],
	65536:     _BufferUsageFlagBits_name[579:616],
	131072:    _BufferUsageFlagBits_name[616:654],
	524288:    _BufferUsageFlagBits_name[654:719],
	1048576:   _BufferUsageFlagBits_name[719:770],
	2097152:   _BufferUsageFlagBits_name[770:816],
	4194304:   _BufferUsageFlagBits_name[816:863],
	8388608:   _BufferUsageFlagBits_name[863:914],
	16777216:  _BufferUsageFlagBits_name[914:951],
	67108864:  _BufferUsageFlagBits_name[951:1006],
	134217728: _BufferUsageFlagBits_name[1006:1039],
}

func (i BufferUsageFlagBits) String() string {
	if str, ok := _BufferUsageFlagBits_map[i]; ok {
		return str
	}
	return "BufferUsageFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BUFFER_USAGE_2_TRANSFER_SRC_BIT-1]
	_ = x[BUFFER_USAGE_2_TRANSFER_DST_BIT-2]
	_ = x[BUFFER_USAGE_2_SHADER_BINDING_TABLE_BIT_KHR-1024]
	_ = x[BUFFER_USAGE_2_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT-2048]
	_ = x[BUFFER_USAGE_2_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT-4096]
	_ = x[BUFFER_USAGE_2_VIDEO_DECODE_SRC_BIT_KHR-8192]
	_ = x[BUFFER_USAGE_2_VIDEO_DECODE_DST_BIT_KHR-16384]
	_ = x[BUFFER_USAGE_2_VIDEO_ENCODE_DST_BIT_KHR-32768]
	_ = x[BUFFER_USAGE_2_VIDEO_ENCODE_SRC_BIT_KHR-65536]
	_ = x[BUFFER_USAGE_2_SHADER_DEVICE_ADDRESS_BIT-131072]
	_ = x[BUFFER_USAGE_2_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR-524288]
	_ = x[BUFFER_USAGE_2_UNIFORM_TEXEL_BUFFER_BIT-4]
	_ = x[BUFFER_USAGE_2_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR-1048576]
	_ = x[BUFFER_USAGE_2_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT-2097152]
	_ = x[BUFFER_USAGE_2_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT-4194304]
	_ = x[BUFFER_USAGE_2_MICROMAP_BUILD_INPUT_READ_ONLY_BIT_EXT-8388608]
	_ = x[BUFFER_USAGE_2_MICROMAP_STORAGE_BIT_EXT-16777216]
	_ = x[BUFFER_USAGE_2_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT-67108864]
	_ = x[BUFFER_USAGE_2_TILE_MEMORY_BIT_QCOM-134217728]
	_ = x[BUFFER_USAGE_2_DATA_GRAPH_FOREIGN_DESCRIPTOR_BIT_ARM-536870912]
	_ = x[BUFFER_USAGE_2_STORAGE_TEXEL_BUFFER_BIT-8]
	_ = x[BUFFER_USAGE_2_PREPROCESS_BUFFER_BIT_EXT-2147483648]
	_ = x[BUFFER_USAGE_2_UNIFORM_BUFFER_BIT-16]
	_ = x[BUFFER_USAGE_2_STORAGE_BUFFER_BIT-32]
	_ = x[BUFFER_USAGE_2_INDEX_BUFFER_BIT-64]
	_ = x[BUFFER_USAGE_2_VERTEX_BUFFER_BIT-128]
	_ = x[BUFFER_USAGE_2_INDIRECT_BUFFER_BIT-256]
	_ = x[BUFFER_USAGE_2_CONDITIONAL_RENDERING_BIT_EXT-512]
	_ = x[BUFFER_USAGE_2_INDEX_BUFFER_BIT_KHR-64]
	_ = x[BUFFER_USAGE_2_INDIRECT_BUFFER_BIT_KHR-256]
	_ = x[BUFFER_USAGE_2_RAY_TRACING_BIT_NV-1024]
	_ = x[BUFFER_USAGE_2_SHADER_DEVICE_ADDRESS_BIT_KHR-131072]
	_ = x[BUFFER_USAGE_2_STORAGE_BUFFER_BIT_KHR-32]
	_ = x[BUFFER_USAGE_2_STORAGE_TEXEL_BUFFER_BIT_KHR-8]
	_ = x[BUFFER_USAGE_2_TRANSFER_DST_BIT_KHR-2]
	_ = x[BUFFER_USAGE_2_TRANSFER_SRC_BIT_KHR-1]
	_ = x[BUFFER_USAGE_2_UNIFORM_BUFFER_BIT_KHR-16]
	_ = x[BUFFER_USAGE_2_UNIFORM_TEXEL_BUFFER_BIT_KHR-4]
	_ = x[BUFFER_USAGE_2_VERTEX_BUFFER_BIT_KHR-128]
}

const _BufferUsageFlagBits2_name = "BUFFER_USAGE_2_TRANSFER_SRC_BITBUFFER_USAGE_2_TRANSFER_DST_BITBUFFER_USAGE_2_UNIFORM_TEXEL_BUFFER_BITBUFFER_USAGE_2_STORAGE_TEXEL_BUFFER_BITBUFFER_USAGE_2_UNIFORM_BUFFER_BITBUFFER_USAGE_2_STORAGE_BUFFER_BITBUFFER_USAGE_2_INDEX_BUFFER_BITBUFFER_USAGE_2_VERTEX_BUFFER_BITBUFFER_USAGE_2_INDIRECT_BUFFER_BITBUFFER_USAGE_2_CONDITIONAL_RENDERING_BIT_EXTBUFFER_USAGE_2_SHADER_BINDING_TABLE_BIT_KHRBUFFER_USAGE_2_TRANSFORM_FEEDBACK_BUFFER_BIT_EXTBUFFER_USAGE_2_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXTBUFFER_USAGE_2_VIDEO_DECODE_SRC_BIT_KHRBUFFER_USAGE_2_VIDEO_DECODE_DST_BIT_KHRBUFFER_USAGE_2_VIDEO_ENCODE_DST_BIT_KHRBUFFER_USAGE_2_VIDEO_ENCODE_SRC_BIT_KHRBUFFER_USAGE_2_SHADER_DEVICE_ADDRESS_BITBUFFER_USAGE_2_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHRBUFFER_USAGE_2_ACCELERATION_STRUCTURE_STORAGE_BIT_KHRBUFFER_USAGE_2_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXTBUFFER_USAGE_2_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXTBUFFER_USAGE_2_MICROMAP_BUILD_INPUT_READ_ONLY_BIT_EXTBUFFER_USAGE_2_MICROMAP_STORAGE_BIT_EXTBUFFER_USAGE_2_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXTBUFFER_USAGE_2_TILE_MEMORY_BIT_QCOMBUFFER_USAGE_2_DATA_GRAPH_FOREIGN_DESCRIPTOR_BIT_ARMBUFFER_USAGE_2_PREPROCESS_BUFFER_BIT_EXT"

var _BufferUsageFlagBits2_map = map[BufferUsageFlagBits2]string{
	1:          _BufferUsageFlagBits2_name[0:31],
	2:          _BufferUsageFlagBits2_name[31:62],
	4:          _BufferUsageFlagBits2_name[62:101],
	8:          _BufferUsageFlagBits2_name[101:140],
	16:         _BufferUsageFlagBits2_name[140:173],
	32:         _BufferUsageFlagBits2_name[173:206],
	64:         _BufferUsageFlagBits2_name[206:237],
	128:        _BufferUsageFlagBits2_name[237:269],
	256:        _BufferUsageFlagBits2_name[269:303],
	512:        _BufferUsageFlagBits2_name[303:347],
	1024:       _BufferUsageFlagBits2_name[347:390],
	2048:       _BufferUsageFlagBits2_name[390:438],
	4096:       _BufferUsageFlagBits2_name[438:494],
	8192:       _BufferUsageFlagBits2_name[494:533],
	16384:      _BufferUsageFlagBits2_name[533:572],
	32768:      _BufferUsageFlagBits2_name[572:611],
	65536:      _BufferUsageFlagBits2_name[611:650],
	131072:     _BufferUsageFlagBits2_name[650:690],
	524288:     _BufferUsageFlagBits2_name[690:757],
	1048576:    _BufferUsageFlagBits2_name[757:810],
	2097152:    _BufferUsageFlagBits2_name[810:858],
	4194304:    _BufferUsageFlagBits2_name[858:907],
	8388608:    _BufferUsageFlagBits2_name[907:960],
	16777216:   _BufferUsageFlagBits2_name[960:999],
	67108864:   _BufferUsageFlagBits2_name[999:1056],
	134217728:  _BufferUsageFlagBits2_name[1056:1091],
	536870912:  _BufferUsageFlagBits2_name[1091:1143],
	2147483648: _BufferUsageFlagBits2_name[1143:1183],
}

func (i BufferUsageFlagBits2) String() string {
	if str, ok := _BufferUsageFlagBits2_map[i]; ok {
		return str
	}
	return "BufferUsageFlagBits2(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_KHR-1]
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_KHR-2]
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_DATA_ACCESS_BIT_KHR-2048]
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_CLUSTER_OPACITY_MICROMAPS_BIT_NV-4096]
	_ = x[BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_KHR-4]
	_ = x[BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_KHR-8]
	_ = x[BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_KHR-16]
	_ = x[BUILD_ACCELERATION_STRUCTURE_MOTION_BIT_NV-32]
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_UPDATE_BIT_EXT-64]
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_DISABLE_OPACITY_MICROMAPS_BIT_EXT-128]
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_DATA_UPDATE_BIT_EXT-256]
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_NV-2]
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_DATA_ACCESS_KHR-2048]
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_DISABLE_OPACITY_MICROMAPS_EXT-128]
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_DATA_UPDATE_EXT-256]
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_UPDATE_EXT-64]
	_ = x[BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_NV-1]
	_ = x[BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_NV-16]
	_ = x[BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_NV-8]
	_ = x[BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_NV-4]
}

const (
	_BuildAccelerationStructureFlagBitsKHR_name_0 = "BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_KHRBUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_KHR"
	_BuildAccelerationStructureFlagBitsKHR_name_1 = "BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_KHR"
	_BuildAccelerationStructureFlagBitsKHR_name_2 = "BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_KHR"
	_BuildAccelerationStructureFlagBitsKHR_name_3 = "BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_KHR"
	_BuildAccelerationStructureFlagBitsKHR_name_4 = "BUILD_ACCELERATION_STRUCTURE_MOTION_BIT_NV"
	_BuildAccelerationStructureFlagBitsKHR_name_5 = "BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_UPDATE_BIT_EXT"
	_BuildAccelerationStructureFlagBitsKHR_name_6 = "BUILD_ACCELERATION_STRUCTURE_ALLOW_DISABLE_OPACITY_MICROMAPS_BIT_EXT"
	_BuildAccelerationStructureFlagBitsKHR_name_7 = "BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_DATA_UPDATE_BIT_EXT"
	_BuildAccelerationStructureFlagBitsKHR_name_8 = "BUILD_ACCELERATION_STRUCTURE_ALLOW_DATA_ACCESS_BIT_KHR"
	_BuildAccelerationStructureFlagBitsKHR_name_9 = "BUILD_ACCELERATION_STRUCTURE_ALLOW_CLUSTER_OPACITY_MICROMAPS_BIT_NV"
)

var (
	_BuildAccelerationStructureFlagBitsKHR_index_0 = [...]uint8{0, 49, 102}
)

func (i BuildAccelerationStructureFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _BuildAccelerationStructureFlagBitsKHR_name_0[_BuildAccelerationStructureFlagBitsKHR_index_0[i]:_BuildAccelerationStructureFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _BuildAccelerationStructureFlagBitsKHR_name_1
	case i == 8:
		return _BuildAccelerationStructureFlagBitsKHR_name_2
	case i == 16:
		return _BuildAccelerationStructureFlagBitsKHR_name_3
	case i == 32:
		return _BuildAccelerationStructureFlagBitsKHR_name_4
	case i == 64:
		return _BuildAccelerationStructureFlagBitsKHR_name_5
	case i == 128:
		return _BuildAccelerationStructureFlagBitsKHR_name_6
	case i == 256:
		return _BuildAccelerationStructureFlagBitsKHR_name_7
	case i == 2048:
		return _BuildAccelerationStructureFlagBitsKHR_name_8
	case i == 4096:
		return _BuildAccelerationStructureFlagBitsKHR_name_9
	default:
		return "BuildAccelerationStructureFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BUILD_ACCELERATION_STRUCTURE_MODE_BUILD_KHR-0]
	_ = x[BUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR-1]
}

const _BuildAccelerationStructureModeKHR_name = "BUILD_ACCELERATION_STRUCTURE_MODE_BUILD_KHRBUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR"

var _BuildAccelerationStructureModeKHR_index = [...]uint8{0, 43, 87}

func (i BuildAccelerationStructureModeKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BuildAccelerationStructureModeKHR_index)-1 {
		return "BuildAccelerationStructureModeKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BuildAccelerationStructureModeKHR_name[_BuildAccelerationStructureModeKHR_index[idx]:_BuildAccelerationStructureModeKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BUILD_MICROMAP_PREFER_FAST_TRACE_BIT_EXT-1]
	_ = x[BUILD_MICROMAP_PREFER_FAST_BUILD_BIT_EXT-2]
	_ = x[BUILD_MICROMAP_ALLOW_COMPACTION_BIT_EXT-4]
}

const (
	_BuildMicromapFlagBitsEXT_name_0 = "BUILD_MICROMAP_PREFER_FAST_TRACE_BIT_EXTBUILD_MICROMAP_PREFER_FAST_BUILD_BIT_EXT"
	_BuildMicromapFlagBitsEXT_name_1 = "BUILD_MICROMAP_ALLOW_COMPACTION_BIT_EXT"
)

var (
	_BuildMicromapFlagBitsEXT_index_0 = [...]uint8{0, 40, 80}
)

func (i BuildMicromapFlagBitsEXT) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _BuildMicromapFlagBitsEXT_name_0[_BuildMicromapFlagBitsEXT_index_0[i]:_BuildMicromapFlagBitsEXT_index_0[i+1]]
	case i == 4:
		return _BuildMicromapFlagBitsEXT_name_1
	default:
		return "BuildMicromapFlagBitsEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BUILD_MICROMAP_MODE_BUILD_EXT-0]
}

const _BuildMicromapModeEXT_name = "BUILD_MICROMAP_MODE_BUILD_EXT"

var _BuildMicromapModeEXT_index = [...]uint8{0, 29}

func (i BuildMicromapModeEXT) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BuildMicromapModeEXT_index)-1 {
		return "BuildMicromapModeEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BuildMicromapModeEXT_name[_BuildMicromapModeEXT_index[idx]:_BuildMicromapModeEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CHROMA_LOCATION_COSITED_EVEN-0]
	_ = x[CHROMA_LOCATION_MIDPOINT-1]
	_ = x[CHROMA_LOCATION_COSITED_EVEN_KHR-0]
	_ = x[CHROMA_LOCATION_MIDPOINT_KHR-1]
}

const _ChromaLocation_name = "CHROMA_LOCATION_COSITED_EVENCHROMA_LOCATION_MIDPOINT"

var _ChromaLocation_index = [...]uint8{0, 28, 52}

func (i ChromaLocation) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ChromaLocation_index)-1 {
		return "ChromaLocation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChromaLocation_name[_ChromaLocation_index[idx]:_ChromaLocation_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_NONE_NV-0]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_DST_IMPLICIT_DATA_BIT_NV-1]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_SCRATCH_DATA_BIT_NV-2]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_DST_ADDRESS_ARRAY_BIT_NV-4]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_DST_SIZES_ARRAY_BIT_NV-8]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_SRC_INFOS_ARRAY_BIT_NV-16]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_SRC_INFOS_COUNT_BIT_NV-32]
}

const (
	_ClusterAccelerationStructureAddressResolutionFlagBitsNV_name_0 = "CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_NONE_NVCLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_DST_IMPLICIT_DATA_BIT_NVCLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_SCRATCH_DATA_BIT_NV"
	_ClusterAccelerationStructureAddressResolutionFlagBitsNV_name_1 = "CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_DST_ADDRESS_ARRAY_BIT_NV"
	_ClusterAccelerationStructureAddressResolutionFlagBitsNV_name_2 = "CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_DST_SIZES_ARRAY_BIT_NV"
	_ClusterAccelerationStructureAddressResolutionFlagBitsNV_name_3 = "CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_SRC_INFOS_ARRAY_BIT_NV"
	_ClusterAccelerationStructureAddressResolutionFlagBitsNV_name_4 = "CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_SRC_INFOS_COUNT_BIT_NV"
)

var (
	_ClusterAccelerationStructureAddressResolutionFlagBitsNV_index_0 = [...]uint8{0, 57, 142, 222}
)

func (i ClusterAccelerationStructureAddressResolutionFlagBitsNV) String() string {
	switch {
	case i <= 2:
		return _ClusterAccelerationStructureAddressResolutionFlagBitsNV_name_0[_ClusterAccelerationStructureAddressResolutionFlagBitsNV_index_0[i]:_ClusterAccelerationStructureAddressResolutionFlagBitsNV_index_0[i+1]]
	case i == 4:
		return _ClusterAccelerationStructureAddressResolutionFlagBitsNV_name_1
	case i == 8:
		return _ClusterAccelerationStructureAddressResolutionFlagBitsNV_name_2
	case i == 16:
		return _ClusterAccelerationStructureAddressResolutionFlagBitsNV_name_3
	case i == 32:
		return _ClusterAccelerationStructureAddressResolutionFlagBitsNV_name_4
	default:
		return "ClusterAccelerationStructureAddressResolutionFlagBitsNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_CLUSTER_ALLOW_DISABLE_OPACITY_MICROMAPS_NV-1]
}

const _ClusterAccelerationStructureClusterFlagBitsNV_name = "CLUSTER_ACCELERATION_STRUCTURE_CLUSTER_ALLOW_DISABLE_OPACITY_MICROMAPS_NV"

var _ClusterAccelerationStructureClusterFlagBitsNV_index = [...]uint8{0, 73}

func (i ClusterAccelerationStructureClusterFlagBitsNV) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ClusterAccelerationStructureClusterFlagBitsNV_index)-1 {
		return "ClusterAccelerationStructureClusterFlagBitsNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClusterAccelerationStructureClusterFlagBitsNV_name[_ClusterAccelerationStructureClusterFlagBitsNV_index[idx]:_ClusterAccelerationStructureClusterFlagBitsNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_GEOMETRY_CULL_DISABLE_BIT_NV-1]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_GEOMETRY_NO_DUPLICATE_ANYHIT_INVOCATION_BIT_NV-2]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_GEOMETRY_OPAQUE_BIT_NV-4]
}

const (
	_ClusterAccelerationStructureGeometryFlagBitsNV_name_0 = "CLUSTER_ACCELERATION_STRUCTURE_GEOMETRY_CULL_DISABLE_BIT_NVCLUSTER_ACCELERATION_STRUCTURE_GEOMETRY_NO_DUPLICATE_ANYHIT_INVOCATION_BIT_NV"
	_ClusterAccelerationStructureGeometryFlagBitsNV_name_1 = "CLUSTER_ACCELERATION_STRUCTURE_GEOMETRY_OPAQUE_BIT_NV"
)

var (
	_ClusterAccelerationStructureGeometryFlagBitsNV_index_0 = [...]uint8{0, 59, 136}
)

func (i ClusterAccelerationStructureGeometryFlagBitsNV) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ClusterAccelerationStructureGeometryFlagBitsNV_name_0[_ClusterAccelerationStructureGeometryFlagBitsNV_index_0[i]:_ClusterAccelerationStructureGeometryFlagBitsNV_index_0[i+1]]
	case i == 4:
		return _ClusterAccelerationStructureGeometryFlagBitsNV_name_1
	default:
		return "ClusterAccelerationStructureGeometryFlagBitsNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
