// Code generated by go-vk from vk.xml at 2025-10-25 17:30:06.318247773 +0000 UTC m=+7.052581559. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR StructureType = 1000006000
)
