// Code generated by "stringer -output=enum_string_8.go -type=SystemAllocationScope,TensorCreateFlagBitsARM,TensorTilingARM,TensorUsageFlagBitsARM,TensorViewCreateFlagBitsARM,TessellationDomainOrigin,TileShadingRenderPassFlagBitsQCOM,TimeDomainKHR,ToolPurposeFlagBits,ValidationCacheHeaderVersionEXT,ValidationCheckEXT,ValidationFeatureDisableEXT,ValidationFeatureEnableEXT,VendorId,VertexInputRate,VideoCapabilityFlagBitsKHR,VideoChromaSubsamplingFlagBitsKHR,VideoCodecOperationFlagBitsKHR,VideoCodingControlFlagBitsKHR,VideoComponentBitDepthFlagBitsKHR,VideoDecodeCapabilityFlagBitsKHR,VideoDecodeH264PictureLayoutFlagBitsKHR,VideoDecodeUsageFlagBitsKHR,VideoEncodeAV1CapabilityFlagBitsKHR,VideoEncodeAV1PredictionModeKHR,VideoEncodeAV1RateControlFlagBitsKHR,VideoEncodeAV1RateControlGroupKHR,VideoEncodeAV1StdFlagBitsKHR,VideoEncodeAV1SuperblockSizeFlagBitsKHR,VideoEncodeCapabilityFlagBitsKHR,VideoEncodeContentFlagBitsKHR"; DO NOT EDIT.

package vk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SYSTEM_ALLOCATION_SCOPE_COMMAND-0]
	_ = x[SYSTEM_ALLOCATION_SCOPE_OBJECT-1]
	_ = x[SYSTEM_ALLOCATION_SCOPE_CACHE-2]
	_ = x[SYSTEM_ALLOCATION_SCOPE_DEVICE-3]
	_ = x[SYSTEM_ALLOCATION_SCOPE_INSTANCE-4]
}

const _SystemAllocationScope_name = "SYSTEM_ALLOCATION_SCOPE_COMMANDSYSTEM_ALLOCATION_SCOPE_OBJECTSYSTEM_ALLOCATION_SCOPE_CACHESYSTEM_ALLOCATION_SCOPE_DEVICESYSTEM_ALLOCATION_SCOPE_INSTANCE"

var _SystemAllocationScope_index = [...]uint8{0, 31, 61, 90, 120, 152}

func (i SystemAllocationScope) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SystemAllocationScope_index)-1 {
		return "SystemAllocationScope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SystemAllocationScope_name[_SystemAllocationScope_index[idx]:_SystemAllocationScope_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TENSOR_CREATE_MUTABLE_FORMAT_BIT_ARM-1]
	_ = x[TENSOR_CREATE_PROTECTED_BIT_ARM-2]
	_ = x[TENSOR_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_ARM-4]
}

const (
	_TensorCreateFlagBitsARM_name_0 = "TENSOR_CREATE_MUTABLE_FORMAT_BIT_ARMTENSOR_CREATE_PROTECTED_BIT_ARM"
	_TensorCreateFlagBitsARM_name_1 = "TENSOR_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_ARM"
)

var (
	_TensorCreateFlagBitsARM_index_0 = [...]uint8{0, 36, 67}
)

func (i TensorCreateFlagBitsARM) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _TensorCreateFlagBitsARM_name_0[_TensorCreateFlagBitsARM_index_0[i]:_TensorCreateFlagBitsARM_index_0[i+1]]
	case i == 4:
		return _TensorCreateFlagBitsARM_name_1
	default:
		return "TensorCreateFlagBitsARM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TENSOR_TILING_OPTIMAL_ARM-0]
	_ = x[TENSOR_TILING_LINEAR_ARM-1]
}

const _TensorTilingARM_name = "TENSOR_TILING_OPTIMAL_ARMTENSOR_TILING_LINEAR_ARM"

var _TensorTilingARM_index = [...]uint8{0, 25, 49}

func (i TensorTilingARM) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TensorTilingARM_index)-1 {
		return "TensorTilingARM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TensorTilingARM_name[_TensorTilingARM_index[idx]:_TensorTilingARM_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TENSOR_USAGE_SHADER_BIT_ARM-2]
	_ = x[TENSOR_USAGE_TRANSFER_SRC_BIT_ARM-4]
	_ = x[TENSOR_USAGE_TRANSFER_DST_BIT_ARM-8]
	_ = x[TENSOR_USAGE_IMAGE_ALIASING_BIT_ARM-16]
	_ = x[TENSOR_USAGE_DATA_GRAPH_BIT_ARM-32]
}

const (
	_TensorUsageFlagBitsARM_name_0 = "TENSOR_USAGE_SHADER_BIT_ARM"
	_TensorUsageFlagBitsARM_name_1 = "TENSOR_USAGE_TRANSFER_SRC_BIT_ARM"
	_TensorUsageFlagBitsARM_name_2 = "TENSOR_USAGE_TRANSFER_DST_BIT_ARM"
	_TensorUsageFlagBitsARM_name_3 = "TENSOR_USAGE_IMAGE_ALIASING_BIT_ARM"
	_TensorUsageFlagBitsARM_name_4 = "TENSOR_USAGE_DATA_GRAPH_BIT_ARM"
)

func (i TensorUsageFlagBitsARM) String() string {
	switch {
	case i == 2:
		return _TensorUsageFlagBitsARM_name_0
	case i == 4:
		return _TensorUsageFlagBitsARM_name_1
	case i == 8:
		return _TensorUsageFlagBitsARM_name_2
	case i == 16:
		return _TensorUsageFlagBitsARM_name_3
	case i == 32:
		return _TensorUsageFlagBitsARM_name_4
	default:
		return "TensorUsageFlagBitsARM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TENSOR_VIEW_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_ARM-1]
}

const _TensorViewCreateFlagBitsARM_name = "TENSOR_VIEW_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_ARM"

var _TensorViewCreateFlagBitsARM_index = [...]uint8{0, 59}

func (i TensorViewCreateFlagBitsARM) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_TensorViewCreateFlagBitsARM_index)-1 {
		return "TensorViewCreateFlagBitsARM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TensorViewCreateFlagBitsARM_name[_TensorViewCreateFlagBitsARM_index[idx]:_TensorViewCreateFlagBitsARM_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFT-0]
	_ = x[TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT-1]
	_ = x[TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT_KHR-1]
	_ = x[TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFT_KHR-0]
}

const _TessellationDomainOrigin_name = "TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFTTESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT"

var _TessellationDomainOrigin_index = [...]uint8{0, 37, 74}

func (i TessellationDomainOrigin) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TessellationDomainOrigin_index)-1 {
		return "TessellationDomainOrigin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TessellationDomainOrigin_name[_TessellationDomainOrigin_index[idx]:_TessellationDomainOrigin_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TILE_SHADING_RENDER_PASS_ENABLE_BIT_QCOM-1]
	_ = x[TILE_SHADING_RENDER_PASS_PER_TILE_EXECUTION_BIT_QCOM-2]
}

const _TileShadingRenderPassFlagBitsQCOM_name = "TILE_SHADING_RENDER_PASS_ENABLE_BIT_QCOMTILE_SHADING_RENDER_PASS_PER_TILE_EXECUTION_BIT_QCOM"

var _TileShadingRenderPassFlagBitsQCOM_index = [...]uint8{0, 40, 92}

func (i TileShadingRenderPassFlagBitsQCOM) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_TileShadingRenderPassFlagBitsQCOM_index)-1 {
		return "TileShadingRenderPassFlagBitsQCOM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TileShadingRenderPassFlagBitsQCOM_name[_TileShadingRenderPassFlagBitsQCOM_index[idx]:_TileShadingRenderPassFlagBitsQCOM_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TIME_DOMAIN_DEVICE_KHR-0]
	_ = x[TIME_DOMAIN_CLOCK_MONOTONIC_KHR-1]
	_ = x[TIME_DOMAIN_CLOCK_MONOTONIC_RAW_KHR-2]
	_ = x[TIME_DOMAIN_QUERY_PERFORMANCE_COUNTER_KHR-3]
	_ = x[TIME_DOMAIN_CLOCK_MONOTONIC_EXT-1]
	_ = x[TIME_DOMAIN_CLOCK_MONOTONIC_RAW_EXT-2]
	_ = x[TIME_DOMAIN_DEVICE_EXT-0]
	_ = x[TIME_DOMAIN_QUERY_PERFORMANCE_COUNTER_EXT-3]
}

const _TimeDomainKHR_name = "TIME_DOMAIN_DEVICE_KHRTIME_DOMAIN_CLOCK_MONOTONIC_KHRTIME_DOMAIN_CLOCK_MONOTONIC_RAW_KHRTIME_DOMAIN_QUERY_PERFORMANCE_COUNTER_KHR"

var _TimeDomainKHR_index = [...]uint8{0, 22, 53, 88, 129}

func (i TimeDomainKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TimeDomainKHR_index)-1 {
		return "TimeDomainKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimeDomainKHR_name[_TimeDomainKHR_index[idx]:_TimeDomainKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOOL_PURPOSE_VALIDATION_BIT-1]
	_ = x[TOOL_PURPOSE_PROFILING_BIT-2]
	_ = x[TOOL_PURPOSE_TRACING_BIT-4]
	_ = x[TOOL_PURPOSE_ADDITIONAL_FEATURES_BIT-8]
	_ = x[TOOL_PURPOSE_MODIFYING_FEATURES_BIT-16]
	_ = x[TOOL_PURPOSE_DEBUG_REPORTING_BIT_EXT-32]
	_ = x[TOOL_PURPOSE_DEBUG_MARKERS_BIT_EXT-64]
	_ = x[TOOL_PURPOSE_ADDITIONAL_FEATURES_BIT_EXT-8]
	_ = x[TOOL_PURPOSE_MODIFYING_FEATURES_BIT_EXT-16]
	_ = x[TOOL_PURPOSE_PROFILING_BIT_EXT-2]
	_ = x[TOOL_PURPOSE_TRACING_BIT_EXT-4]
	_ = x[TOOL_PURPOSE_VALIDATION_BIT_EXT-1]
}

const (
	_ToolPurposeFlagBits_name_0 = "TOOL_PURPOSE_VALIDATION_BITTOOL_PURPOSE_PROFILING_BIT"
	_ToolPurposeFlagBits_name_1 = "TOOL_PURPOSE_TRACING_BIT"
	_ToolPurposeFlagBits_name_2 = "TOOL_PURPOSE_ADDITIONAL_FEATURES_BIT"
	_ToolPurposeFlagBits_name_3 = "TOOL_PURPOSE_MODIFYING_FEATURES_BIT"
	_ToolPurposeFlagBits_name_4 = "TOOL_PURPOSE_DEBUG_REPORTING_BIT_EXT"
	_ToolPurposeFlagBits_name_5 = "TOOL_PURPOSE_DEBUG_MARKERS_BIT_EXT"
)

var (
	_ToolPurposeFlagBits_index_0 = [...]uint8{0, 27, 53}
)

func (i ToolPurposeFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ToolPurposeFlagBits_name_0[_ToolPurposeFlagBits_index_0[i]:_ToolPurposeFlagBits_index_0[i+1]]
	case i == 4:
		return _ToolPurposeFlagBits_name_1
	case i == 8:
		return _ToolPurposeFlagBits_name_2
	case i == 16:
		return _ToolPurposeFlagBits_name_3
	case i == 32:
		return _ToolPurposeFlagBits_name_4
	case i == 64:
		return _ToolPurposeFlagBits_name_5
	default:
		return "ToolPurposeFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VALIDATION_CACHE_HEADER_VERSION_ONE_EXT-1]
}

const _ValidationCacheHeaderVersionEXT_name = "VALIDATION_CACHE_HEADER_VERSION_ONE_EXT"

var _ValidationCacheHeaderVersionEXT_index = [...]uint8{0, 39}

func (i ValidationCacheHeaderVersionEXT) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ValidationCacheHeaderVersionEXT_index)-1 {
		return "ValidationCacheHeaderVersionEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValidationCacheHeaderVersionEXT_name[_ValidationCacheHeaderVersionEXT_index[idx]:_ValidationCacheHeaderVersionEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VALIDATION_CHECK_ALL_EXT-0]
	_ = x[VALIDATION_CHECK_SHADERS_EXT-1]
}

const _ValidationCheckEXT_name = "VALIDATION_CHECK_ALL_EXTVALIDATION_CHECK_SHADERS_EXT"

var _ValidationCheckEXT_index = [...]uint8{0, 24, 52}

func (i ValidationCheckEXT) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ValidationCheckEXT_index)-1 {
		return "ValidationCheckEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValidationCheckEXT_name[_ValidationCheckEXT_index[idx]:_ValidationCheckEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VALIDATION_FEATURE_DISABLE_ALL_EXT-0]
	_ = x[VALIDATION_FEATURE_DISABLE_SHADERS_EXT-1]
	_ = x[VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT-2]
	_ = x[VALIDATION_FEATURE_DISABLE_API_PARAMETERS_EXT-3]
	_ = x[VALIDATION_FEATURE_DISABLE_OBJECT_LIFETIMES_EXT-4]
	_ = x[VALIDATION_FEATURE_DISABLE_CORE_CHECKS_EXT-5]
	_ = x[VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT-6]
	_ = x[VALIDATION_FEATURE_DISABLE_SHADER_VALIDATION_CACHE_EXT-7]
}

const _ValidationFeatureDisableEXT_name = "VALIDATION_FEATURE_DISABLE_ALL_EXTVALIDATION_FEATURE_DISABLE_SHADERS_EXTVALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXTVALIDATION_FEATURE_DISABLE_API_PARAMETERS_EXTVALIDATION_FEATURE_DISABLE_OBJECT_LIFETIMES_EXTVALIDATION_FEATURE_DISABLE_CORE_CHECKS_EXTVALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXTVALIDATION_FEATURE_DISABLE_SHADER_VALIDATION_CACHE_EXT"

var _ValidationFeatureDisableEXT_index = [...]uint16{0, 34, 72, 116, 161, 208, 250, 295, 349}

func (i ValidationFeatureDisableEXT) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ValidationFeatureDisableEXT_index)-1 {
		return "ValidationFeatureDisableEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValidationFeatureDisableEXT_name[_ValidationFeatureDisableEXT_index[idx]:_ValidationFeatureDisableEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT-0]
	_ = x[VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT-1]
	_ = x[VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT-2]
	_ = x[VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT-3]
	_ = x[VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT-4]
}

const _ValidationFeatureEnableEXT_name = "VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXTVALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXTVALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXTVALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXTVALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT"

var _ValidationFeatureEnableEXT_index = [...]uint8{0, 42, 105, 149, 191, 247}

func (i ValidationFeatureEnableEXT) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ValidationFeatureEnableEXT_index)-1 {
		return "ValidationFeatureEnableEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValidationFeatureEnableEXT_name[_ValidationFeatureEnableEXT_index[idx]:_ValidationFeatureEnableEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VENDOR_ID_KHRONOS-65536]
	_ = x[VENDOR_ID_VIV-65537]
	_ = x[VENDOR_ID_VSI-65538]
	_ = x[VENDOR_ID_KAZAN-65539]
	_ = x[VENDOR_ID_CODEPLAY-65540]
	_ = x[VENDOR_ID_MESA-65541]
	_ = x[VENDOR_ID_POCL-65542]
	_ = x[VENDOR_ID_MOBILEYE-65543]
}

const _VendorId_name = "VENDOR_ID_KHRONOSVENDOR_ID_VIVVENDOR_ID_VSIVENDOR_ID_KAZANVENDOR_ID_CODEPLAYVENDOR_ID_MESAVENDOR_ID_POCLVENDOR_ID_MOBILEYE"

var _VendorId_index = [...]uint8{0, 17, 30, 43, 58, 76, 90, 104, 122}

func (i VendorId) String() string {
	idx := int(i) - 65536
	if i < 65536 || idx >= len(_VendorId_index)-1 {
		return "VendorId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VendorId_name[_VendorId_index[idx]:_VendorId_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VERTEX_INPUT_RATE_VERTEX-0]
	_ = x[VERTEX_INPUT_RATE_INSTANCE-1]
}

const _VertexInputRate_name = "VERTEX_INPUT_RATE_VERTEXVERTEX_INPUT_RATE_INSTANCE"

var _VertexInputRate_index = [...]uint8{0, 24, 50}

func (i VertexInputRate) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_VertexInputRate_index)-1 {
		return "VertexInputRate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VertexInputRate_name[_VertexInputRate_index[idx]:_VertexInputRate_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_CAPABILITY_PROTECTED_CONTENT_BIT_KHR-1]
	_ = x[VIDEO_CAPABILITY_SEPARATE_REFERENCE_IMAGES_BIT_KHR-2]
}

const _VideoCapabilityFlagBitsKHR_name = "VIDEO_CAPABILITY_PROTECTED_CONTENT_BIT_KHRVIDEO_CAPABILITY_SEPARATE_REFERENCE_IMAGES_BIT_KHR"

var _VideoCapabilityFlagBitsKHR_index = [...]uint8{0, 42, 92}

func (i VideoCapabilityFlagBitsKHR) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_VideoCapabilityFlagBitsKHR_index)-1 {
		return "VideoCapabilityFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoCapabilityFlagBitsKHR_name[_VideoCapabilityFlagBitsKHR_index[idx]:_VideoCapabilityFlagBitsKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_CHROMA_SUBSAMPLING_INVALID_KHR-0]
	_ = x[VIDEO_CHROMA_SUBSAMPLING_MONOCHROME_BIT_KHR-1]
	_ = x[VIDEO_CHROMA_SUBSAMPLING_420_BIT_KHR-2]
	_ = x[VIDEO_CHROMA_SUBSAMPLING_422_BIT_KHR-4]
	_ = x[VIDEO_CHROMA_SUBSAMPLING_444_BIT_KHR-8]
}

const (
	_VideoChromaSubsamplingFlagBitsKHR_name_0 = "VIDEO_CHROMA_SUBSAMPLING_INVALID_KHRVIDEO_CHROMA_SUBSAMPLING_MONOCHROME_BIT_KHRVIDEO_CHROMA_SUBSAMPLING_420_BIT_KHR"
	_VideoChromaSubsamplingFlagBitsKHR_name_1 = "VIDEO_CHROMA_SUBSAMPLING_422_BIT_KHR"
	_VideoChromaSubsamplingFlagBitsKHR_name_2 = "VIDEO_CHROMA_SUBSAMPLING_444_BIT_KHR"
)

var (
	_VideoChromaSubsamplingFlagBitsKHR_index_0 = [...]uint8{0, 36, 79, 115}
)

func (i VideoChromaSubsamplingFlagBitsKHR) String() string {
	switch {
	case i <= 2:
		return _VideoChromaSubsamplingFlagBitsKHR_name_0[_VideoChromaSubsamplingFlagBitsKHR_index_0[i]:_VideoChromaSubsamplingFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoChromaSubsamplingFlagBitsKHR_name_1
	case i == 8:
		return _VideoChromaSubsamplingFlagBitsKHR_name_2
	default:
		return "VideoChromaSubsamplingFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_CODEC_OPERATION_NONE_KHR-0]
	_ = x[VIDEO_CODEC_OPERATION_DECODE_H264_BIT_KHR-1]
	_ = x[VIDEO_CODEC_OPERATION_DECODE_H265_BIT_KHR-2]
	_ = x[VIDEO_CODEC_OPERATION_ENCODE_H264_BIT_KHR-65536]
	_ = x[VIDEO_CODEC_OPERATION_ENCODE_H265_BIT_KHR-131072]
	_ = x[VIDEO_CODEC_OPERATION_ENCODE_AV1_BIT_KHR-262144]
	_ = x[VIDEO_CODEC_OPERATION_DECODE_AV1_BIT_KHR-4]
	_ = x[VIDEO_CODEC_OPERATION_DECODE_VP9_BIT_KHR-8]
}

const (
	_VideoCodecOperationFlagBitsKHR_name_0 = "VIDEO_CODEC_OPERATION_NONE_KHRVIDEO_CODEC_OPERATION_DECODE_H264_BIT_KHRVIDEO_CODEC_OPERATION_DECODE_H265_BIT_KHR"
	_VideoCodecOperationFlagBitsKHR_name_1 = "VIDEO_CODEC_OPERATION_DECODE_AV1_BIT_KHR"
	_VideoCodecOperationFlagBitsKHR_name_2 = "VIDEO_CODEC_OPERATION_DECODE_VP9_BIT_KHR"
	_VideoCodecOperationFlagBitsKHR_name_3 = "VIDEO_CODEC_OPERATION_ENCODE_H264_BIT_KHR"
	_VideoCodecOperationFlagBitsKHR_name_4 = "VIDEO_CODEC_OPERATION_ENCODE_H265_BIT_KHR"
	_VideoCodecOperationFlagBitsKHR_name_5 = "VIDEO_CODEC_OPERATION_ENCODE_AV1_BIT_KHR"
)

var (
	_VideoCodecOperationFlagBitsKHR_index_0 = [...]uint8{0, 30, 71, 112}
)

func (i VideoCodecOperationFlagBitsKHR) String() string {
	switch {
	case i <= 2:
		return _VideoCodecOperationFlagBitsKHR_name_0[_VideoCodecOperationFlagBitsKHR_index_0[i]:_VideoCodecOperationFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoCodecOperationFlagBitsKHR_name_1
	case i == 8:
		return _VideoCodecOperationFlagBitsKHR_name_2
	case i == 65536:
		return _VideoCodecOperationFlagBitsKHR_name_3
	case i == 131072:
		return _VideoCodecOperationFlagBitsKHR_name_4
	case i == 262144:
		return _VideoCodecOperationFlagBitsKHR_name_5
	default:
		return "VideoCodecOperationFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_CODING_CONTROL_RESET_BIT_KHR-1]
	_ = x[VIDEO_CODING_CONTROL_ENCODE_RATE_CONTROL_BIT_KHR-2]
	_ = x[VIDEO_CODING_CONTROL_ENCODE_QUALITY_LEVEL_BIT_KHR-4]
}

const (
	_VideoCodingControlFlagBitsKHR_name_0 = "VIDEO_CODING_CONTROL_RESET_BIT_KHRVIDEO_CODING_CONTROL_ENCODE_RATE_CONTROL_BIT_KHR"
	_VideoCodingControlFlagBitsKHR_name_1 = "VIDEO_CODING_CONTROL_ENCODE_QUALITY_LEVEL_BIT_KHR"
)

var (
	_VideoCodingControlFlagBitsKHR_index_0 = [...]uint8{0, 34, 82}
)

func (i VideoCodingControlFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoCodingControlFlagBitsKHR_name_0[_VideoCodingControlFlagBitsKHR_index_0[i]:_VideoCodingControlFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoCodingControlFlagBitsKHR_name_1
	default:
		return "VideoCodingControlFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_COMPONENT_BIT_DEPTH_INVALID_KHR-0]
	_ = x[VIDEO_COMPONENT_BIT_DEPTH_8_BIT_KHR-1]
	_ = x[VIDEO_COMPONENT_BIT_DEPTH_10_BIT_KHR-4]
	_ = x[VIDEO_COMPONENT_BIT_DEPTH_12_BIT_KHR-16]
}

const (
	_VideoComponentBitDepthFlagBitsKHR_name_0 = "VIDEO_COMPONENT_BIT_DEPTH_INVALID_KHRVIDEO_COMPONENT_BIT_DEPTH_8_BIT_KHR"
	_VideoComponentBitDepthFlagBitsKHR_name_1 = "VIDEO_COMPONENT_BIT_DEPTH_10_BIT_KHR"
	_VideoComponentBitDepthFlagBitsKHR_name_2 = "VIDEO_COMPONENT_BIT_DEPTH_12_BIT_KHR"
)

var (
	_VideoComponentBitDepthFlagBitsKHR_index_0 = [...]uint8{0, 37, 72}
)

func (i VideoComponentBitDepthFlagBitsKHR) String() string {
	switch {
	case i <= 1:
		return _VideoComponentBitDepthFlagBitsKHR_name_0[_VideoComponentBitDepthFlagBitsKHR_index_0[i]:_VideoComponentBitDepthFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoComponentBitDepthFlagBitsKHR_name_1
	case i == 16:
		return _VideoComponentBitDepthFlagBitsKHR_name_2
	default:
		return "VideoComponentBitDepthFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_DECODE_CAPABILITY_DPB_AND_OUTPUT_COINCIDE_BIT_KHR-1]
	_ = x[VIDEO_DECODE_CAPABILITY_DPB_AND_OUTPUT_DISTINCT_BIT_KHR-2]
}

const _VideoDecodeCapabilityFlagBitsKHR_name = "VIDEO_DECODE_CAPABILITY_DPB_AND_OUTPUT_COINCIDE_BIT_KHRVIDEO_DECODE_CAPABILITY_DPB_AND_OUTPUT_DISTINCT_BIT_KHR"

var _VideoDecodeCapabilityFlagBitsKHR_index = [...]uint8{0, 55, 110}

func (i VideoDecodeCapabilityFlagBitsKHR) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_VideoDecodeCapabilityFlagBitsKHR_index)-1 {
		return "VideoDecodeCapabilityFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoDecodeCapabilityFlagBitsKHR_name[_VideoDecodeCapabilityFlagBitsKHR_index[idx]:_VideoDecodeCapabilityFlagBitsKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_DECODE_H264_PICTURE_LAYOUT_PROGRESSIVE_KHR-0]
	_ = x[VIDEO_DECODE_H264_PICTURE_LAYOUT_INTERLACED_INTERLEAVED_LINES_BIT_KHR-1]
	_ = x[VIDEO_DECODE_H264_PICTURE_LAYOUT_INTERLACED_SEPARATE_PLANES_BIT_KHR-2]
}

const _VideoDecodeH264PictureLayoutFlagBitsKHR_name = "VIDEO_DECODE_H264_PICTURE_LAYOUT_PROGRESSIVE_KHRVIDEO_DECODE_H264_PICTURE_LAYOUT_INTERLACED_INTERLEAVED_LINES_BIT_KHRVIDEO_DECODE_H264_PICTURE_LAYOUT_INTERLACED_SEPARATE_PLANES_BIT_KHR"

var _VideoDecodeH264PictureLayoutFlagBitsKHR_index = [...]uint8{0, 48, 117, 184}

func (i VideoDecodeH264PictureLayoutFlagBitsKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_VideoDecodeH264PictureLayoutFlagBitsKHR_index)-1 {
		return "VideoDecodeH264PictureLayoutFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoDecodeH264PictureLayoutFlagBitsKHR_name[_VideoDecodeH264PictureLayoutFlagBitsKHR_index[idx]:_VideoDecodeH264PictureLayoutFlagBitsKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_DECODE_USAGE_DEFAULT_KHR-0]
	_ = x[VIDEO_DECODE_USAGE_TRANSCODING_BIT_KHR-1]
	_ = x[VIDEO_DECODE_USAGE_OFFLINE_BIT_KHR-2]
	_ = x[VIDEO_DECODE_USAGE_STREAMING_BIT_KHR-4]
}

const (
	_VideoDecodeUsageFlagBitsKHR_name_0 = "VIDEO_DECODE_USAGE_DEFAULT_KHRVIDEO_DECODE_USAGE_TRANSCODING_BIT_KHRVIDEO_DECODE_USAGE_OFFLINE_BIT_KHR"
	_VideoDecodeUsageFlagBitsKHR_name_1 = "VIDEO_DECODE_USAGE_STREAMING_BIT_KHR"
)

var (
	_VideoDecodeUsageFlagBitsKHR_index_0 = [...]uint8{0, 30, 68, 102}
)

func (i VideoDecodeUsageFlagBitsKHR) String() string {
	switch {
	case i <= 2:
		return _VideoDecodeUsageFlagBitsKHR_name_0[_VideoDecodeUsageFlagBitsKHR_index_0[i]:_VideoDecodeUsageFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoDecodeUsageFlagBitsKHR_name_1
	default:
		return "VideoDecodeUsageFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_AV1_CAPABILITY_PER_RATE_CONTROL_GROUP_MIN_MAX_Q_INDEX_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_AV1_CAPABILITY_GENERATE_OBU_EXTENSION_HEADER_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_AV1_CAPABILITY_PRIMARY_REFERENCE_CDF_ONLY_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_AV1_CAPABILITY_FRAME_SIZE_OVERRIDE_BIT_KHR-8]
	_ = x[VIDEO_ENCODE_AV1_CAPABILITY_MOTION_VECTOR_SCALING_BIT_KHR-16]
	_ = x[VIDEO_ENCODE_AV1_CAPABILITY_COMPOUND_PREDICTION_INTRA_REFRESH_BIT_KHR-32]
}

const (
	_VideoEncodeAV1CapabilityFlagBitsKHR_name_0 = "VIDEO_ENCODE_AV1_CAPABILITY_PER_RATE_CONTROL_GROUP_MIN_MAX_Q_INDEX_BIT_KHRVIDEO_ENCODE_AV1_CAPABILITY_GENERATE_OBU_EXTENSION_HEADER_BIT_KHR"
	_VideoEncodeAV1CapabilityFlagBitsKHR_name_1 = "VIDEO_ENCODE_AV1_CAPABILITY_PRIMARY_REFERENCE_CDF_ONLY_BIT_KHR"
	_VideoEncodeAV1CapabilityFlagBitsKHR_name_2 = "VIDEO_ENCODE_AV1_CAPABILITY_FRAME_SIZE_OVERRIDE_BIT_KHR"
	_VideoEncodeAV1CapabilityFlagBitsKHR_name_3 = "VIDEO_ENCODE_AV1_CAPABILITY_MOTION_VECTOR_SCALING_BIT_KHR"
	_VideoEncodeAV1CapabilityFlagBitsKHR_name_4 = "VIDEO_ENCODE_AV1_CAPABILITY_COMPOUND_PREDICTION_INTRA_REFRESH_BIT_KHR"
)

var (
	_VideoEncodeAV1CapabilityFlagBitsKHR_index_0 = [...]uint8{0, 74, 139}
)

func (i VideoEncodeAV1CapabilityFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoEncodeAV1CapabilityFlagBitsKHR_name_0[_VideoEncodeAV1CapabilityFlagBitsKHR_index_0[i]:_VideoEncodeAV1CapabilityFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeAV1CapabilityFlagBitsKHR_name_1
	case i == 8:
		return _VideoEncodeAV1CapabilityFlagBitsKHR_name_2
	case i == 16:
		return _VideoEncodeAV1CapabilityFlagBitsKHR_name_3
	case i == 32:
		return _VideoEncodeAV1CapabilityFlagBitsKHR_name_4
	default:
		return "VideoEncodeAV1CapabilityFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_AV1_PREDICTION_MODE_INTRA_ONLY_KHR-0]
	_ = x[VIDEO_ENCODE_AV1_PREDICTION_MODE_SINGLE_REFERENCE_KHR-1]
	_ = x[VIDEO_ENCODE_AV1_PREDICTION_MODE_UNIDIRECTIONAL_COMPOUND_KHR-2]
	_ = x[VIDEO_ENCODE_AV1_PREDICTION_MODE_BIDIRECTIONAL_COMPOUND_KHR-3]
}

const _VideoEncodeAV1PredictionModeKHR_name = "VIDEO_ENCODE_AV1_PREDICTION_MODE_INTRA_ONLY_KHRVIDEO_ENCODE_AV1_PREDICTION_MODE_SINGLE_REFERENCE_KHRVIDEO_ENCODE_AV1_PREDICTION_MODE_UNIDIRECTIONAL_COMPOUND_KHRVIDEO_ENCODE_AV1_PREDICTION_MODE_BIDIRECTIONAL_COMPOUND_KHR"

var _VideoEncodeAV1PredictionModeKHR_index = [...]uint8{0, 47, 100, 160, 219}

func (i VideoEncodeAV1PredictionModeKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_VideoEncodeAV1PredictionModeKHR_index)-1 {
		return "VideoEncodeAV1PredictionModeKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoEncodeAV1PredictionModeKHR_name[_VideoEncodeAV1PredictionModeKHR_index[idx]:_VideoEncodeAV1PredictionModeKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_AV1_RATE_CONTROL_REGULAR_GOP_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_AV1_RATE_CONTROL_TEMPORAL_LAYER_PATTERN_DYADIC_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_AV1_RATE_CONTROL_REFERENCE_PATTERN_FLAT_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_AV1_RATE_CONTROL_REFERENCE_PATTERN_DYADIC_BIT_KHR-8]
}

const (
	_VideoEncodeAV1RateControlFlagBitsKHR_name_0 = "VIDEO_ENCODE_AV1_RATE_CONTROL_REGULAR_GOP_BIT_KHRVIDEO_ENCODE_AV1_RATE_CONTROL_TEMPORAL_LAYER_PATTERN_DYADIC_BIT_KHR"
	_VideoEncodeAV1RateControlFlagBitsKHR_name_1 = "VIDEO_ENCODE_AV1_RATE_CONTROL_REFERENCE_PATTERN_FLAT_BIT_KHR"
	_VideoEncodeAV1RateControlFlagBitsKHR_name_2 = "VIDEO_ENCODE_AV1_RATE_CONTROL_REFERENCE_PATTERN_DYADIC_BIT_KHR"
)

var (
	_VideoEncodeAV1RateControlFlagBitsKHR_index_0 = [...]uint8{0, 49, 116}
)

func (i VideoEncodeAV1RateControlFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoEncodeAV1RateControlFlagBitsKHR_name_0[_VideoEncodeAV1RateControlFlagBitsKHR_index_0[i]:_VideoEncodeAV1RateControlFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeAV1RateControlFlagBitsKHR_name_1
	case i == 8:
		return _VideoEncodeAV1RateControlFlagBitsKHR_name_2
	default:
		return "VideoEncodeAV1RateControlFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_AV1_RATE_CONTROL_GROUP_INTRA_KHR-0]
	_ = x[VIDEO_ENCODE_AV1_RATE_CONTROL_GROUP_PREDICTIVE_KHR-1]
	_ = x[VIDEO_ENCODE_AV1_RATE_CONTROL_GROUP_BIPREDICTIVE_KHR-2]
}

const _VideoEncodeAV1RateControlGroupKHR_name = "VIDEO_ENCODE_AV1_RATE_CONTROL_GROUP_INTRA_KHRVIDEO_ENCODE_AV1_RATE_CONTROL_GROUP_PREDICTIVE_KHRVIDEO_ENCODE_AV1_RATE_CONTROL_GROUP_BIPREDICTIVE_KHR"

var _VideoEncodeAV1RateControlGroupKHR_index = [...]uint8{0, 45, 95, 147}

func (i VideoEncodeAV1RateControlGroupKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_VideoEncodeAV1RateControlGroupKHR_index)-1 {
		return "VideoEncodeAV1RateControlGroupKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoEncodeAV1RateControlGroupKHR_name[_VideoEncodeAV1RateControlGroupKHR_index[idx]:_VideoEncodeAV1RateControlGroupKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_AV1_STD_UNIFORM_TILE_SPACING_FLAG_SET_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_AV1_STD_SKIP_MODE_PRESENT_UNSET_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_AV1_STD_PRIMARY_REF_FRAME_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_AV1_STD_DELTA_Q_BIT_KHR-8]
}

const (
	_VideoEncodeAV1StdFlagBitsKHR_name_0 = "VIDEO_ENCODE_AV1_STD_UNIFORM_TILE_SPACING_FLAG_SET_BIT_KHRVIDEO_ENCODE_AV1_STD_SKIP_MODE_PRESENT_UNSET_BIT_KHR"
	_VideoEncodeAV1StdFlagBitsKHR_name_1 = "VIDEO_ENCODE_AV1_STD_PRIMARY_REF_FRAME_BIT_KHR"
	_VideoEncodeAV1StdFlagBitsKHR_name_2 = "VIDEO_ENCODE_AV1_STD_DELTA_Q_BIT_KHR"
)

var (
	_VideoEncodeAV1StdFlagBitsKHR_index_0 = [...]uint8{0, 58, 110}
)

func (i VideoEncodeAV1StdFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoEncodeAV1StdFlagBitsKHR_name_0[_VideoEncodeAV1StdFlagBitsKHR_index_0[i]:_VideoEncodeAV1StdFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeAV1StdFlagBitsKHR_name_1
	case i == 8:
		return _VideoEncodeAV1StdFlagBitsKHR_name_2
	default:
		return "VideoEncodeAV1StdFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_AV1_SUPERBLOCK_SIZE_64_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_AV1_SUPERBLOCK_SIZE_128_BIT_KHR-2]
}

const _VideoEncodeAV1SuperblockSizeFlagBitsKHR_name = "VIDEO_ENCODE_AV1_SUPERBLOCK_SIZE_64_BIT_KHRVIDEO_ENCODE_AV1_SUPERBLOCK_SIZE_128_BIT_KHR"

var _VideoEncodeAV1SuperblockSizeFlagBitsKHR_index = [...]uint8{0, 43, 87}

func (i VideoEncodeAV1SuperblockSizeFlagBitsKHR) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_VideoEncodeAV1SuperblockSizeFlagBitsKHR_index)-1 {
		return "VideoEncodeAV1SuperblockSizeFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoEncodeAV1SuperblockSizeFlagBitsKHR_name[_VideoEncodeAV1SuperblockSizeFlagBitsKHR_index[idx]:_VideoEncodeAV1SuperblockSizeFlagBitsKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_CAPABILITY_PRECEDING_EXTERNALLY_ENCODED_BYTES_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_CAPABILITY_INSUFFICIENT_BITSTREAM_BUFFER_RANGE_DETECTION_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_CAPABILITY_QUANTIZATION_DELTA_MAP_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_CAPABILITY_EMPHASIS_MAP_BIT_KHR-8]
}

const (
	_VideoEncodeCapabilityFlagBitsKHR_name_0 = "VIDEO_ENCODE_CAPABILITY_PRECEDING_EXTERNALLY_ENCODED_BYTES_BIT_KHRVIDEO_ENCODE_CAPABILITY_INSUFFICIENT_BITSTREAM_BUFFER_RANGE_DETECTION_BIT_KHR"
	_VideoEncodeCapabilityFlagBitsKHR_name_1 = "VIDEO_ENCODE_CAPABILITY_QUANTIZATION_DELTA_MAP_BIT_KHR"
	_VideoEncodeCapabilityFlagBitsKHR_name_2 = "VIDEO_ENCODE_CAPABILITY_EMPHASIS_MAP_BIT_KHR"
)

var (
	_VideoEncodeCapabilityFlagBitsKHR_index_0 = [...]uint8{0, 66, 143}
)

func (i VideoEncodeCapabilityFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoEncodeCapabilityFlagBitsKHR_name_0[_VideoEncodeCapabilityFlagBitsKHR_index_0[i]:_VideoEncodeCapabilityFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeCapabilityFlagBitsKHR_name_1
	case i == 8:
		return _VideoEncodeCapabilityFlagBitsKHR_name_2
	default:
		return "VideoEncodeCapabilityFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_CONTENT_DEFAULT_KHR-0]
	_ = x[VIDEO_ENCODE_CONTENT_CAMERA_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_CONTENT_DESKTOP_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_CONTENT_RENDERED_BIT_KHR-4]
}

const (
	_VideoEncodeContentFlagBitsKHR_name_0 = "VIDEO_ENCODE_CONTENT_DEFAULT_KHRVIDEO_ENCODE_CONTENT_CAMERA_BIT_KHRVIDEO_ENCODE_CONTENT_DESKTOP_BIT_KHR"
	_VideoEncodeContentFlagBitsKHR_name_1 = "VIDEO_ENCODE_CONTENT_RENDERED_BIT_KHR"
)

var (
	_VideoEncodeContentFlagBitsKHR_index_0 = [...]uint8{0, 32, 67, 103}
)

func (i VideoEncodeContentFlagBitsKHR) String() string {
	switch {
	case i <= 2:
		return _VideoEncodeContentFlagBitsKHR_name_0[_VideoEncodeContentFlagBitsKHR_index_0[i]:_VideoEncodeContentFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeContentFlagBitsKHR_name_1
	default:
		return "VideoEncodeContentFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
