// Code generated by go-vk from vk.xml at 2025-10-26 13:04:53.118692148 +0000 UTC m=+12.526390406. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_DIRECTFB_SURFACE_CREATE_INFO_EXT StructureType = 1000346000
)
