// Code generated by go-vk from vk.xml at 2025-10-25 17:30:04.65883903 +0000 UTC m=+5.393172876. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR StructureType = 1000004000
)
