// Code generated by go-vk from vk.xml at 2025-10-26 13:04:51.573463128 +0000 UTC m=+10.981161426. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR StructureType = 1000004000
)
