// Code generated by "stringer -output=enum_string_5.go -type=OpticalFlowPerformanceLevelNV,OpticalFlowSessionBindingPointNV,OpticalFlowSessionCreateFlagBitsNV,OpticalFlowUsageFlagBitsNV,OutOfBandQueueTypeNV,PartitionedAccelerationStructureInstanceFlagBitsNV,PartitionedAccelerationStructureOpTypeNV,PeerMemoryFeatureFlagBits,PerformanceConfigurationTypeINTEL,PerformanceCounterDescriptionFlagBitsKHR,PerformanceCounterScopeKHR,PerformanceCounterStorageKHR,PerformanceCounterUnitKHR,PerformanceOverrideTypeINTEL,PerformanceParameterTypeINTEL,PerformanceValueTypeINTEL,PhysicalDeviceDataGraphOperationTypeARM,PhysicalDeviceDataGraphProcessingEngineTypeARM,PhysicalDeviceLayeredApiKHR,PhysicalDeviceSchedulingControlsFlagBitsARM,PhysicalDeviceType,PipelineBindPoint,PipelineCacheCreateFlagBits,PipelineCacheHeaderVersion,PipelineColorBlendStateCreateFlagBits,PipelineCreateFlagBits,PipelineCreateFlagBits2,PipelineCreationFeedbackFlagBits,PipelineDepthStencilStateCreateFlagBits,PipelineExecutableStatisticFormatKHR,PipelineLayoutCreateFlagBits"; DO NOT EDIT.

package vk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OPTICAL_FLOW_PERFORMANCE_LEVEL_UNKNOWN_NV-0]
	_ = x[OPTICAL_FLOW_PERFORMANCE_LEVEL_SLOW_NV-1]
	_ = x[OPTICAL_FLOW_PERFORMANCE_LEVEL_MEDIUM_NV-2]
	_ = x[OPTICAL_FLOW_PERFORMANCE_LEVEL_FAST_NV-3]
}

const _OpticalFlowPerformanceLevelNV_name = "OPTICAL_FLOW_PERFORMANCE_LEVEL_UNKNOWN_NVOPTICAL_FLOW_PERFORMANCE_LEVEL_SLOW_NVOPTICAL_FLOW_PERFORMANCE_LEVEL_MEDIUM_NVOPTICAL_FLOW_PERFORMANCE_LEVEL_FAST_NV"

var _OpticalFlowPerformanceLevelNV_index = [...]uint8{0, 41, 79, 119, 157}

func (i OpticalFlowPerformanceLevelNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpticalFlowPerformanceLevelNV_index)-1 {
		return "OpticalFlowPerformanceLevelNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpticalFlowPerformanceLevelNV_name[_OpticalFlowPerformanceLevelNV_index[idx]:_OpticalFlowPerformanceLevelNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OPTICAL_FLOW_SESSION_BINDING_POINT_UNKNOWN_NV-0]
	_ = x[OPTICAL_FLOW_SESSION_BINDING_POINT_INPUT_NV-1]
	_ = x[OPTICAL_FLOW_SESSION_BINDING_POINT_REFERENCE_NV-2]
	_ = x[OPTICAL_FLOW_SESSION_BINDING_POINT_HINT_NV-3]
	_ = x[OPTICAL_FLOW_SESSION_BINDING_POINT_FLOW_VECTOR_NV-4]
	_ = x[OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_FLOW_VECTOR_NV-5]
	_ = x[OPTICAL_FLOW_SESSION_BINDING_POINT_COST_NV-6]
	_ = x[OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_COST_NV-7]
	_ = x[OPTICAL_FLOW_SESSION_BINDING_POINT_GLOBAL_FLOW_NV-8]
}

const _OpticalFlowSessionBindingPointNV_name = "OPTICAL_FLOW_SESSION_BINDING_POINT_UNKNOWN_NVOPTICAL_FLOW_SESSION_BINDING_POINT_INPUT_NVOPTICAL_FLOW_SESSION_BINDING_POINT_REFERENCE_NVOPTICAL_FLOW_SESSION_BINDING_POINT_HINT_NVOPTICAL_FLOW_SESSION_BINDING_POINT_FLOW_VECTOR_NVOPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_FLOW_VECTOR_NVOPTICAL_FLOW_SESSION_BINDING_POINT_COST_NVOPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_COST_NVOPTICAL_FLOW_SESSION_BINDING_POINT_GLOBAL_FLOW_NV"

var _OpticalFlowSessionBindingPointNV_index = [...]uint16{0, 45, 88, 135, 177, 226, 284, 326, 377, 426}

func (i OpticalFlowSessionBindingPointNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpticalFlowSessionBindingPointNV_index)-1 {
		return "OpticalFlowSessionBindingPointNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpticalFlowSessionBindingPointNV_name[_OpticalFlowSessionBindingPointNV_index[idx]:_OpticalFlowSessionBindingPointNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OPTICAL_FLOW_SESSION_CREATE_ENABLE_HINT_BIT_NV-1]
	_ = x[OPTICAL_FLOW_SESSION_CREATE_ENABLE_COST_BIT_NV-2]
	_ = x[OPTICAL_FLOW_SESSION_CREATE_ENABLE_GLOBAL_FLOW_BIT_NV-4]
	_ = x[OPTICAL_FLOW_SESSION_CREATE_ALLOW_REGIONS_BIT_NV-8]
	_ = x[OPTICAL_FLOW_SESSION_CREATE_BOTH_DIRECTIONS_BIT_NV-16]
}

const (
	_OpticalFlowSessionCreateFlagBitsNV_name_0 = "OPTICAL_FLOW_SESSION_CREATE_ENABLE_HINT_BIT_NVOPTICAL_FLOW_SESSION_CREATE_ENABLE_COST_BIT_NV"
	_OpticalFlowSessionCreateFlagBitsNV_name_1 = "OPTICAL_FLOW_SESSION_CREATE_ENABLE_GLOBAL_FLOW_BIT_NV"
	_OpticalFlowSessionCreateFlagBitsNV_name_2 = "OPTICAL_FLOW_SESSION_CREATE_ALLOW_REGIONS_BIT_NV"
	_OpticalFlowSessionCreateFlagBitsNV_name_3 = "OPTICAL_FLOW_SESSION_CREATE_BOTH_DIRECTIONS_BIT_NV"
)

var (
	_OpticalFlowSessionCreateFlagBitsNV_index_0 = [...]uint8{0, 46, 92}
)

func (i OpticalFlowSessionCreateFlagBitsNV) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _OpticalFlowSessionCreateFlagBitsNV_name_0[_OpticalFlowSessionCreateFlagBitsNV_index_0[i]:_OpticalFlowSessionCreateFlagBitsNV_index_0[i+1]]
	case i == 4:
		return _OpticalFlowSessionCreateFlagBitsNV_name_1
	case i == 8:
		return _OpticalFlowSessionCreateFlagBitsNV_name_2
	case i == 16:
		return _OpticalFlowSessionCreateFlagBitsNV_name_3
	default:
		return "OpticalFlowSessionCreateFlagBitsNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OPTICAL_FLOW_USAGE_UNKNOWN_NV-0]
	_ = x[OPTICAL_FLOW_USAGE_INPUT_BIT_NV-1]
	_ = x[OPTICAL_FLOW_USAGE_OUTPUT_BIT_NV-2]
	_ = x[OPTICAL_FLOW_USAGE_HINT_BIT_NV-4]
	_ = x[OPTICAL_FLOW_USAGE_COST_BIT_NV-8]
	_ = x[OPTICAL_FLOW_USAGE_GLOBAL_FLOW_BIT_NV-16]
}

const (
	_OpticalFlowUsageFlagBitsNV_name_0 = "OPTICAL_FLOW_USAGE_UNKNOWN_NVOPTICAL_FLOW_USAGE_INPUT_BIT_NVOPTICAL_FLOW_USAGE_OUTPUT_BIT_NV"
	_OpticalFlowUsageFlagBitsNV_name_1 = "OPTICAL_FLOW_USAGE_HINT_BIT_NV"
	_OpticalFlowUsageFlagBitsNV_name_2 = "OPTICAL_FLOW_USAGE_COST_BIT_NV"
	_OpticalFlowUsageFlagBitsNV_name_3 = "OPTICAL_FLOW_USAGE_GLOBAL_FLOW_BIT_NV"
)

var (
	_OpticalFlowUsageFlagBitsNV_index_0 = [...]uint8{0, 29, 60, 92}
)

func (i OpticalFlowUsageFlagBitsNV) String() string {
	switch {
	case i <= 2:
		return _OpticalFlowUsageFlagBitsNV_name_0[_OpticalFlowUsageFlagBitsNV_index_0[i]:_OpticalFlowUsageFlagBitsNV_index_0[i+1]]
	case i == 4:
		return _OpticalFlowUsageFlagBitsNV_name_1
	case i == 8:
		return _OpticalFlowUsageFlagBitsNV_name_2
	case i == 16:
		return _OpticalFlowUsageFlagBitsNV_name_3
	default:
		return "OpticalFlowUsageFlagBitsNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OUT_OF_BAND_QUEUE_TYPE_RENDER_NV-0]
	_ = x[OUT_OF_BAND_QUEUE_TYPE_PRESENT_NV-1]
}

const _OutOfBandQueueTypeNV_name = "OUT_OF_BAND_QUEUE_TYPE_RENDER_NVOUT_OF_BAND_QUEUE_TYPE_PRESENT_NV"

var _OutOfBandQueueTypeNV_index = [...]uint8{0, 32, 65}

func (i OutOfBandQueueTypeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OutOfBandQueueTypeNV_index)-1 {
		return "OutOfBandQueueTypeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OutOfBandQueueTypeNV_name[_OutOfBandQueueTypeNV_index[idx]:_OutOfBandQueueTypeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_TRIANGLE_FACING_CULL_DISABLE_BIT_NV-1]
	_ = x[PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_TRIANGLE_FLIP_FACING_BIT_NV-2]
	_ = x[PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_FORCE_OPAQUE_BIT_NV-4]
	_ = x[PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_FORCE_NO_OPAQUE_BIT_NV-8]
	_ = x[PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_ENABLE_EXPLICIT_BOUNDING_BOX_NV-16]
}

const (
	_PartitionedAccelerationStructureInstanceFlagBitsNV_name_0 = "PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_TRIANGLE_FACING_CULL_DISABLE_BIT_NVPARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_TRIANGLE_FLIP_FACING_BIT_NV"
	_PartitionedAccelerationStructureInstanceFlagBitsNV_name_1 = "PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_FORCE_OPAQUE_BIT_NV"
	_PartitionedAccelerationStructureInstanceFlagBitsNV_name_2 = "PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_FORCE_NO_OPAQUE_BIT_NV"
	_PartitionedAccelerationStructureInstanceFlagBitsNV_name_3 = "PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_ENABLE_EXPLICIT_BOUNDING_BOX_NV"
)

var (
	_PartitionedAccelerationStructureInstanceFlagBitsNV_index_0 = [...]uint8{0, 84, 160}
)

func (i PartitionedAccelerationStructureInstanceFlagBitsNV) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _PartitionedAccelerationStructureInstanceFlagBitsNV_name_0[_PartitionedAccelerationStructureInstanceFlagBitsNV_index_0[i]:_PartitionedAccelerationStructureInstanceFlagBitsNV_index_0[i+1]]
	case i == 4:
		return _PartitionedAccelerationStructureInstanceFlagBitsNV_name_1
	case i == 8:
		return _PartitionedAccelerationStructureInstanceFlagBitsNV_name_2
	case i == 16:
		return _PartitionedAccelerationStructureInstanceFlagBitsNV_name_3
	default:
		return "PartitionedAccelerationStructureInstanceFlagBitsNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_WRITE_INSTANCE_NV-0]
	_ = x[PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_UPDATE_INSTANCE_NV-1]
	_ = x[PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_WRITE_PARTITION_TRANSLATION_NV-2]
}

const _PartitionedAccelerationStructureOpTypeNV_name = "PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_WRITE_INSTANCE_NVPARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_UPDATE_INSTANCE_NVPARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_WRITE_PARTITION_TRANSLATION_NV"

var _PartitionedAccelerationStructureOpTypeNV_index = [...]uint8{0, 60, 121, 194}

func (i PartitionedAccelerationStructureOpTypeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PartitionedAccelerationStructureOpTypeNV_index)-1 {
		return "PartitionedAccelerationStructureOpTypeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PartitionedAccelerationStructureOpTypeNV_name[_PartitionedAccelerationStructureOpTypeNV_index[idx]:_PartitionedAccelerationStructureOpTypeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PEER_MEMORY_FEATURE_COPY_SRC_BIT-1]
	_ = x[PEER_MEMORY_FEATURE_COPY_DST_BIT-2]
	_ = x[PEER_MEMORY_FEATURE_GENERIC_SRC_BIT-4]
	_ = x[PEER_MEMORY_FEATURE_GENERIC_DST_BIT-8]
	_ = x[PEER_MEMORY_FEATURE_COPY_DST_BIT_KHR-2]
	_ = x[PEER_MEMORY_FEATURE_COPY_SRC_BIT_KHR-1]
	_ = x[PEER_MEMORY_FEATURE_GENERIC_DST_BIT_KHR-8]
	_ = x[PEER_MEMORY_FEATURE_GENERIC_SRC_BIT_KHR-4]
}

const (
	_PeerMemoryFeatureFlagBits_name_0 = "PEER_MEMORY_FEATURE_COPY_SRC_BITPEER_MEMORY_FEATURE_COPY_DST_BIT"
	_PeerMemoryFeatureFlagBits_name_1 = "PEER_MEMORY_FEATURE_GENERIC_SRC_BIT"
	_PeerMemoryFeatureFlagBits_name_2 = "PEER_MEMORY_FEATURE_GENERIC_DST_BIT"
)

var (
	_PeerMemoryFeatureFlagBits_index_0 = [...]uint8{0, 32, 64}
)

func (i PeerMemoryFeatureFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _PeerMemoryFeatureFlagBits_name_0[_PeerMemoryFeatureFlagBits_index_0[i]:_PeerMemoryFeatureFlagBits_index_0[i+1]]
	case i == 4:
		return _PeerMemoryFeatureFlagBits_name_1
	case i == 8:
		return _PeerMemoryFeatureFlagBits_name_2
	default:
		return "PeerMemoryFeatureFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PERFORMANCE_CONFIGURATION_TYPE_COMMAND_QUEUE_METRICS_DISCOVERY_ACTIVATED_INTEL-0]
}

const _PerformanceConfigurationTypeINTEL_name = "PERFORMANCE_CONFIGURATION_TYPE_COMMAND_QUEUE_METRICS_DISCOVERY_ACTIVATED_INTEL"

var _PerformanceConfigurationTypeINTEL_index = [...]uint8{0, 78}

func (i PerformanceConfigurationTypeINTEL) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PerformanceConfigurationTypeINTEL_index)-1 {
		return "PerformanceConfigurationTypeINTEL(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PerformanceConfigurationTypeINTEL_name[_PerformanceConfigurationTypeINTEL_index[idx]:_PerformanceConfigurationTypeINTEL_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PERFORMANCE_COUNTER_DESCRIPTION_PERFORMANCE_IMPACTING_BIT_KHR-1]
	_ = x[PERFORMANCE_COUNTER_DESCRIPTION_CONCURRENTLY_IMPACTED_BIT_KHR-2]
	_ = x[PERFORMANCE_COUNTER_DESCRIPTION_CONCURRENTLY_IMPACTED_KHR-2]
	_ = x[PERFORMANCE_COUNTER_DESCRIPTION_PERFORMANCE_IMPACTING_KHR-1]
}

const _PerformanceCounterDescriptionFlagBitsKHR_name = "PERFORMANCE_COUNTER_DESCRIPTION_PERFORMANCE_IMPACTING_BIT_KHRPERFORMANCE_COUNTER_DESCRIPTION_CONCURRENTLY_IMPACTED_BIT_KHR"

var _PerformanceCounterDescriptionFlagBitsKHR_index = [...]uint8{0, 61, 122}

func (i PerformanceCounterDescriptionFlagBitsKHR) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_PerformanceCounterDescriptionFlagBitsKHR_index)-1 {
		return "PerformanceCounterDescriptionFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PerformanceCounterDescriptionFlagBitsKHR_name[_PerformanceCounterDescriptionFlagBitsKHR_index[idx]:_PerformanceCounterDescriptionFlagBitsKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PERFORMANCE_COUNTER_SCOPE_COMMAND_BUFFER_KHR-0]
	_ = x[PERFORMANCE_COUNTER_SCOPE_RENDER_PASS_KHR-1]
	_ = x[PERFORMANCE_COUNTER_SCOPE_COMMAND_KHR-2]
	_ = x[QUERY_SCOPE_COMMAND_BUFFER_KHR-0]
	_ = x[QUERY_SCOPE_COMMAND_KHR-2]
	_ = x[QUERY_SCOPE_RENDER_PASS_KHR-1]
}

const _PerformanceCounterScopeKHR_name = "PERFORMANCE_COUNTER_SCOPE_COMMAND_BUFFER_KHRPERFORMANCE_COUNTER_SCOPE_RENDER_PASS_KHRPERFORMANCE_COUNTER_SCOPE_COMMAND_KHR"

var _PerformanceCounterScopeKHR_index = [...]uint8{0, 44, 85, 122}

func (i PerformanceCounterScopeKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PerformanceCounterScopeKHR_index)-1 {
		return "PerformanceCounterScopeKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PerformanceCounterScopeKHR_name[_PerformanceCounterScopeKHR_index[idx]:_PerformanceCounterScopeKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PERFORMANCE_COUNTER_STORAGE_INT32_KHR-0]
	_ = x[PERFORMANCE_COUNTER_STORAGE_INT64_KHR-1]
	_ = x[PERFORMANCE_COUNTER_STORAGE_UINT32_KHR-2]
	_ = x[PERFORMANCE_COUNTER_STORAGE_UINT64_KHR-3]
	_ = x[PERFORMANCE_COUNTER_STORAGE_FLOAT32_KHR-4]
	_ = x[PERFORMANCE_COUNTER_STORAGE_FLOAT64_KHR-5]
}

const _PerformanceCounterStorageKHR_name = "PERFORMANCE_COUNTER_STORAGE_INT32_KHRPERFORMANCE_COUNTER_STORAGE_INT64_KHRPERFORMANCE_COUNTER_STORAGE_UINT32_KHRPERFORMANCE_COUNTER_STORAGE_UINT64_KHRPERFORMANCE_COUNTER_STORAGE_FLOAT32_KHRPERFORMANCE_COUNTER_STORAGE_FLOAT64_KHR"

var _PerformanceCounterStorageKHR_index = [...]uint8{0, 37, 74, 112, 150, 189, 228}

func (i PerformanceCounterStorageKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PerformanceCounterStorageKHR_index)-1 {
		return "PerformanceCounterStorageKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PerformanceCounterStorageKHR_name[_PerformanceCounterStorageKHR_index[idx]:_PerformanceCounterStorageKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PERFORMANCE_COUNTER_UNIT_GENERIC_KHR-0]
	_ = x[PERFORMANCE_COUNTER_UNIT_PERCENTAGE_KHR-1]
	_ = x[PERFORMANCE_COUNTER_UNIT_NANOSECONDS_KHR-2]
	_ = x[PERFORMANCE_COUNTER_UNIT_BYTES_KHR-3]
	_ = x[PERFORMANCE_COUNTER_UNIT_BYTES_PER_SECOND_KHR-4]
	_ = x[PERFORMANCE_COUNTER_UNIT_KELVIN_KHR-5]
	_ = x[PERFORMANCE_COUNTER_UNIT_WATTS_KHR-6]
	_ = x[PERFORMANCE_COUNTER_UNIT_VOLTS_KHR-7]
	_ = x[PERFORMANCE_COUNTER_UNIT_AMPS_KHR-8]
	_ = x[PERFORMANCE_COUNTER_UNIT_HERTZ_KHR-9]
	_ = x[PERFORMANCE_COUNTER_UNIT_CYCLES_KHR-10]
}

const _PerformanceCounterUnitKHR_name = "PERFORMANCE_COUNTER_UNIT_GENERIC_KHRPERFORMANCE_COUNTER_UNIT_PERCENTAGE_KHRPERFORMANCE_COUNTER_UNIT_NANOSECONDS_KHRPERFORMANCE_COUNTER_UNIT_BYTES_KHRPERFORMANCE_COUNTER_UNIT_BYTES_PER_SECOND_KHRPERFORMANCE_COUNTER_UNIT_KELVIN_KHRPERFORMANCE_COUNTER_UNIT_WATTS_KHRPERFORMANCE_COUNTER_UNIT_VOLTS_KHRPERFORMANCE_COUNTER_UNIT_AMPS_KHRPERFORMANCE_COUNTER_UNIT_HERTZ_KHRPERFORMANCE_COUNTER_UNIT_CYCLES_KHR"

var _PerformanceCounterUnitKHR_index = [...]uint16{0, 36, 75, 115, 149, 194, 229, 263, 297, 330, 364, 399}

func (i PerformanceCounterUnitKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PerformanceCounterUnitKHR_index)-1 {
		return "PerformanceCounterUnitKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PerformanceCounterUnitKHR_name[_PerformanceCounterUnitKHR_index[idx]:_PerformanceCounterUnitKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PERFORMANCE_OVERRIDE_TYPE_NULL_HARDWARE_INTEL-0]
	_ = x[PERFORMANCE_OVERRIDE_TYPE_FLUSH_GPU_CACHES_INTEL-1]
}

const _PerformanceOverrideTypeINTEL_name = "PERFORMANCE_OVERRIDE_TYPE_NULL_HARDWARE_INTELPERFORMANCE_OVERRIDE_TYPE_FLUSH_GPU_CACHES_INTEL"

var _PerformanceOverrideTypeINTEL_index = [...]uint8{0, 45, 93}

func (i PerformanceOverrideTypeINTEL) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PerformanceOverrideTypeINTEL_index)-1 {
		return "PerformanceOverrideTypeINTEL(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PerformanceOverrideTypeINTEL_name[_PerformanceOverrideTypeINTEL_index[idx]:_PerformanceOverrideTypeINTEL_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PERFORMANCE_PARAMETER_TYPE_HW_COUNTERS_SUPPORTED_INTEL-0]
	_ = x[PERFORMANCE_PARAMETER_TYPE_STREAM_MARKER_VALID_BITS_INTEL-1]
}

const _PerformanceParameterTypeINTEL_name = "PERFORMANCE_PARAMETER_TYPE_HW_COUNTERS_SUPPORTED_INTELPERFORMANCE_PARAMETER_TYPE_STREAM_MARKER_VALID_BITS_INTEL"

var _PerformanceParameterTypeINTEL_index = [...]uint8{0, 54, 111}

func (i PerformanceParameterTypeINTEL) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PerformanceParameterTypeINTEL_index)-1 {
		return "PerformanceParameterTypeINTEL(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PerformanceParameterTypeINTEL_name[_PerformanceParameterTypeINTEL_index[idx]:_PerformanceParameterTypeINTEL_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PERFORMANCE_VALUE_TYPE_UINT32_INTEL-0]
	_ = x[PERFORMANCE_VALUE_TYPE_UINT64_INTEL-1]
	_ = x[PERFORMANCE_VALUE_TYPE_FLOAT_INTEL-2]
	_ = x[PERFORMANCE_VALUE_TYPE_BOOL_INTEL-3]
	_ = x[PERFORMANCE_VALUE_TYPE_STRING_INTEL-4]
}

const _PerformanceValueTypeINTEL_name = "PERFORMANCE_VALUE_TYPE_UINT32_INTELPERFORMANCE_VALUE_TYPE_UINT64_INTELPERFORMANCE_VALUE_TYPE_FLOAT_INTELPERFORMANCE_VALUE_TYPE_BOOL_INTELPERFORMANCE_VALUE_TYPE_STRING_INTEL"

var _PerformanceValueTypeINTEL_index = [...]uint8{0, 35, 70, 104, 137, 172}

func (i PerformanceValueTypeINTEL) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PerformanceValueTypeINTEL_index)-1 {
		return "PerformanceValueTypeINTEL(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PerformanceValueTypeINTEL_name[_PerformanceValueTypeINTEL_index[idx]:_PerformanceValueTypeINTEL_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PHYSICAL_DEVICE_DATA_GRAPH_OPERATION_TYPE_SPIRV_EXTENDED_INSTRUCTION_SET_ARM-0]
}

const _PhysicalDeviceDataGraphOperationTypeARM_name = "PHYSICAL_DEVICE_DATA_GRAPH_OPERATION_TYPE_SPIRV_EXTENDED_INSTRUCTION_SET_ARM"

var _PhysicalDeviceDataGraphOperationTypeARM_index = [...]uint8{0, 76}

func (i PhysicalDeviceDataGraphOperationTypeARM) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PhysicalDeviceDataGraphOperationTypeARM_index)-1 {
		return "PhysicalDeviceDataGraphOperationTypeARM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PhysicalDeviceDataGraphOperationTypeARM_name[_PhysicalDeviceDataGraphOperationTypeARM_index[idx]:_PhysicalDeviceDataGraphOperationTypeARM_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PHYSICAL_DEVICE_DATA_GRAPH_PROCESSING_ENGINE_TYPE_DEFAULT_ARM-0]
}

const _PhysicalDeviceDataGraphProcessingEngineTypeARM_name = "PHYSICAL_DEVICE_DATA_GRAPH_PROCESSING_ENGINE_TYPE_DEFAULT_ARM"

var _PhysicalDeviceDataGraphProcessingEngineTypeARM_index = [...]uint8{0, 61}

func (i PhysicalDeviceDataGraphProcessingEngineTypeARM) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PhysicalDeviceDataGraphProcessingEngineTypeARM_index)-1 {
		return "PhysicalDeviceDataGraphProcessingEngineTypeARM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PhysicalDeviceDataGraphProcessingEngineTypeARM_name[_PhysicalDeviceDataGraphProcessingEngineTypeARM_index[idx]:_PhysicalDeviceDataGraphProcessingEngineTypeARM_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PHYSICAL_DEVICE_LAYERED_API_VULKAN_KHR-0]
	_ = x[PHYSICAL_DEVICE_LAYERED_API_D3D12_KHR-1]
	_ = x[PHYSICAL_DEVICE_LAYERED_API_METAL_KHR-2]
	_ = x[PHYSICAL_DEVICE_LAYERED_API_OPENGL_KHR-3]
	_ = x[PHYSICAL_DEVICE_LAYERED_API_OPENGLES_KHR-4]
}

const _PhysicalDeviceLayeredApiKHR_name = "PHYSICAL_DEVICE_LAYERED_API_VULKAN_KHRPHYSICAL_DEVICE_LAYERED_API_D3D12_KHRPHYSICAL_DEVICE_LAYERED_API_METAL_KHRPHYSICAL_DEVICE_LAYERED_API_OPENGL_KHRPHYSICAL_DEVICE_LAYERED_API_OPENGLES_KHR"

var _PhysicalDeviceLayeredApiKHR_index = [...]uint8{0, 38, 75, 112, 150, 190}

func (i PhysicalDeviceLayeredApiKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PhysicalDeviceLayeredApiKHR_index)-1 {
		return "PhysicalDeviceLayeredApiKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PhysicalDeviceLayeredApiKHR_name[_PhysicalDeviceLayeredApiKHR_index[idx]:_PhysicalDeviceLayeredApiKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PHYSICAL_DEVICE_SCHEDULING_CONTROLS_SHADER_CORE_COUNT_ARM-1]
}

const _PhysicalDeviceSchedulingControlsFlagBitsARM_name = "PHYSICAL_DEVICE_SCHEDULING_CONTROLS_SHADER_CORE_COUNT_ARM"

var _PhysicalDeviceSchedulingControlsFlagBitsARM_index = [...]uint8{0, 57}

func (i PhysicalDeviceSchedulingControlsFlagBitsARM) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_PhysicalDeviceSchedulingControlsFlagBitsARM_index)-1 {
		return "PhysicalDeviceSchedulingControlsFlagBitsARM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PhysicalDeviceSchedulingControlsFlagBitsARM_name[_PhysicalDeviceSchedulingControlsFlagBitsARM_index[idx]:_PhysicalDeviceSchedulingControlsFlagBitsARM_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PHYSICAL_DEVICE_TYPE_OTHER-0]
	_ = x[PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU-1]
	_ = x[PHYSICAL_DEVICE_TYPE_DISCRETE_GPU-2]
	_ = x[PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU-3]
	_ = x[PHYSICAL_DEVICE_TYPE_CPU-4]
}

const _PhysicalDeviceType_name = "PHYSICAL_DEVICE_TYPE_OTHERPHYSICAL_DEVICE_TYPE_INTEGRATED_GPUPHYSICAL_DEVICE_TYPE_DISCRETE_GPUPHYSICAL_DEVICE_TYPE_VIRTUAL_GPUPHYSICAL_DEVICE_TYPE_CPU"

var _PhysicalDeviceType_index = [...]uint8{0, 26, 61, 94, 126, 150}

func (i PhysicalDeviceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PhysicalDeviceType_index)-1 {
		return "PhysicalDeviceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PhysicalDeviceType_name[_PhysicalDeviceType_index[idx]:_PhysicalDeviceType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_BIND_POINT_GRAPHICS-0]
	_ = x[PIPELINE_BIND_POINT_COMPUTE-1]
	_ = x[PIPELINE_BIND_POINT_RAY_TRACING_KHR-1000347000]
	_ = x[PIPELINE_BIND_POINT_SUBPASS_SHADING_HUAWEI-1000369003]
	_ = x[PIPELINE_BIND_POINT_DATA_GRAPH_ARM-1000507000]
	_ = x[PIPELINE_BIND_POINT_RAY_TRACING_NV-1000347000]
}

const (
	_PipelineBindPoint_name_0 = "PIPELINE_BIND_POINT_GRAPHICSPIPELINE_BIND_POINT_COMPUTE"
	_PipelineBindPoint_name_1 = "PIPELINE_BIND_POINT_RAY_TRACING_KHR"
	_PipelineBindPoint_name_2 = "PIPELINE_BIND_POINT_SUBPASS_SHADING_HUAWEI"
	_PipelineBindPoint_name_3 = "PIPELINE_BIND_POINT_DATA_GRAPH_ARM"
)

var (
	_PipelineBindPoint_index_0 = [...]uint8{0, 28, 55}
)

func (i PipelineBindPoint) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _PipelineBindPoint_name_0[_PipelineBindPoint_index_0[i]:_PipelineBindPoint_index_0[i+1]]
	case i == 1000347000:
		return _PipelineBindPoint_name_1
	case i == 1000369003:
		return _PipelineBindPoint_name_2
	case i == 1000507000:
		return _PipelineBindPoint_name_3
	default:
		return "PipelineBindPoint(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_CACHE_CREATE_EXTERNALLY_SYNCHRONIZED_BIT-1]
	_ = x[PIPELINE_CACHE_CREATE_INTERNALLY_SYNCHRONIZED_MERGE_BIT_KHR-8]
	_ = x[PIPELINE_CACHE_CREATE_EXTERNALLY_SYNCHRONIZED_BIT_EXT-1]
}

const (
	_PipelineCacheCreateFlagBits_name_0 = "PIPELINE_CACHE_CREATE_EXTERNALLY_SYNCHRONIZED_BIT"
	_PipelineCacheCreateFlagBits_name_1 = "PIPELINE_CACHE_CREATE_INTERNALLY_SYNCHRONIZED_MERGE_BIT_KHR"
)

func (i PipelineCacheCreateFlagBits) String() string {
	switch {
	case i == 1:
		return _PipelineCacheCreateFlagBits_name_0
	case i == 8:
		return _PipelineCacheCreateFlagBits_name_1
	default:
		return "PipelineCacheCreateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_CACHE_HEADER_VERSION_ONE-1]
}

const _PipelineCacheHeaderVersion_name = "PIPELINE_CACHE_HEADER_VERSION_ONE"

var _PipelineCacheHeaderVersion_index = [...]uint8{0, 33}

func (i PipelineCacheHeaderVersion) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_PipelineCacheHeaderVersion_index)-1 {
		return "PipelineCacheHeaderVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PipelineCacheHeaderVersion_name[_PipelineCacheHeaderVersion_index[idx]:_PipelineCacheHeaderVersion_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_COLOR_BLEND_STATE_CREATE_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_BIT_EXT-1]
	_ = x[PIPELINE_COLOR_BLEND_STATE_CREATE_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_BIT_ARM-1]
}

const _PipelineColorBlendStateCreateFlagBits_name = "PIPELINE_COLOR_BLEND_STATE_CREATE_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_BIT_EXT"

var _PipelineColorBlendStateCreateFlagBits_index = [...]uint8{0, 79}

func (i PipelineColorBlendStateCreateFlagBits) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_PipelineColorBlendStateCreateFlagBits_index)-1 {
		return "PipelineColorBlendStateCreateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PipelineColorBlendStateCreateFlagBits_name[_PipelineColorBlendStateCreateFlagBits_index[idx]:_PipelineColorBlendStateCreateFlagBits_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT-1]
	_ = x[PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT-2]
	_ = x[PIPELINE_CREATE_LINK_TIME_OPTIMIZATION_BIT_EXT-1024]
	_ = x[PIPELINE_CREATE_LIBRARY_BIT_KHR-2048]
	_ = x[PIPELINE_CREATE_RAY_TRACING_SKIP_TRIANGLES_BIT_KHR-4096]
	_ = x[PIPELINE_CREATE_RAY_TRACING_SKIP_AABBS_BIT_KHR-8192]
	_ = x[PIPELINE_CREATE_RAY_TRACING_NO_NULL_ANY_HIT_SHADERS_BIT_KHR-16384]
	_ = x[PIPELINE_CREATE_RAY_TRACING_NO_NULL_CLOSEST_HIT_SHADERS_BIT_KHR-32768]
	_ = x[PIPELINE_CREATE_RAY_TRACING_NO_NULL_MISS_SHADERS_BIT_KHR-65536]
	_ = x[PIPELINE_CREATE_RAY_TRACING_NO_NULL_INTERSECTION_SHADERS_BIT_KHR-131072]
	_ = x[PIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NV-262144]
	_ = x[PIPELINE_CREATE_RAY_TRACING_SHADER_GROUP_HANDLE_CAPTURE_REPLAY_BIT_KHR-524288]
	_ = x[PIPELINE_CREATE_DERIVATIVE_BIT-4]
	_ = x[PIPELINE_CREATE_RAY_TRACING_ALLOW_MOTION_BIT_NV-1048576]
	_ = x[PIPELINE_CREATE_RENDERING_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR-2097152]
	_ = x[PIPELINE_CREATE_RENDERING_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT-4194304]
	_ = x[PIPELINE_CREATE_RETAIN_LINK_TIME_OPTIMIZATION_INFO_BIT_EXT-8388608]
	_ = x[PIPELINE_CREATE_RAY_TRACING_OPACITY_MICROMAP_BIT_EXT-16777216]
	_ = x[PIPELINE_CREATE_COLOR_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT-33554432]
	_ = x[PIPELINE_CREATE_DEPTH_STENCIL_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT-67108864]
	_ = x[PIPELINE_CREATE_NO_PROTECTED_ACCESS_BIT-134217728]
	_ = x[PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT-536870912]
	_ = x[PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT-8]
	_ = x[PIPELINE_CREATE_PROTECTED_ACCESS_ONLY_BIT-1073741824]
	_ = x[PIPELINE_CREATE_DISPATCH_BASE_BIT-16]
	_ = x[PIPELINE_CREATE_DEFER_COMPILE_BIT_NV-32]
	_ = x[PIPELINE_CREATE_CAPTURE_STATISTICS_BIT_KHR-64]
	_ = x[PIPELINE_CREATE_CAPTURE_INTERNAL_REPRESENTATIONS_BIT_KHR-128]
	_ = x[PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT-256]
	_ = x[PIPELINE_CREATE_EARLY_RETURN_ON_FAILURE_BIT-512]
	_ = x[PIPELINE_CREATE_DISPATCH_BASE-16]
	_ = x[PIPELINE_CREATE_DISPATCH_BASE_BIT_KHR-16]
	_ = x[PIPELINE_CREATE_DISPATCH_BASE_KHR-16]
	_ = x[PIPELINE_CREATE_EARLY_RETURN_ON_FAILURE_BIT_EXT-512]
	_ = x[PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT_EXT-256]
	_ = x[PIPELINE_CREATE_NO_PROTECTED_ACCESS_BIT_EXT-134217728]
	_ = x[PIPELINE_CREATE_PROTECTED_ACCESS_ONLY_BIT_EXT-1073741824]
	_ = x[PIPELINE_RASTERIZATION_STATE_CREATE_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT-4194304]
	_ = x[PIPELINE_RASTERIZATION_STATE_CREATE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR-2097152]
	_ = x[PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT_KHR-8]
}

const _PipelineCreateFlagBits_name = "PIPELINE_CREATE_DISABLE_OPTIMIZATION_BITPIPELINE_CREATE_ALLOW_DERIVATIVES_BITPIPELINE_CREATE_DERIVATIVE_BITPIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BITPIPELINE_CREATE_DISPATCH_BASE_BITPIPELINE_CREATE_DEFER_COMPILE_BIT_NVPIPELINE_CREATE_CAPTURE_STATISTICS_BIT_KHRPIPELINE_CREATE_CAPTURE_INTERNAL_REPRESENTATIONS_BIT_KHRPIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BITPIPELINE_CREATE_EARLY_RETURN_ON_FAILURE_BITPIPELINE_CREATE_LINK_TIME_OPTIMIZATION_BIT_EXTPIPELINE_CREATE_LIBRARY_BIT_KHRPIPELINE_CREATE_RAY_TRACING_SKIP_TRIANGLES_BIT_KHRPIPELINE_CREATE_RAY_TRACING_SKIP_AABBS_BIT_KHRPIPELINE_CREATE_RAY_TRACING_NO_NULL_ANY_HIT_SHADERS_BIT_KHRPIPELINE_CREATE_RAY_TRACING_NO_NULL_CLOSEST_HIT_SHADERS_BIT_KHRPIPELINE_CREATE_RAY_TRACING_NO_NULL_MISS_SHADERS_BIT_KHRPIPELINE_CREATE_RAY_TRACING_NO_NULL_INTERSECTION_SHADERS_BIT_KHRPIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NVPIPELINE_CREATE_RAY_TRACING_SHADER_GROUP_HANDLE_CAPTURE_REPLAY_BIT_KHRPIPELINE_CREATE_RAY_TRACING_ALLOW_MOTION_BIT_NVPIPELINE_CREATE_RENDERING_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHRPIPELINE_CREATE_RENDERING_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXTPIPELINE_CREATE_RETAIN_LINK_TIME_OPTIMIZATION_INFO_BIT_EXTPIPELINE_CREATE_RAY_TRACING_OPACITY_MICROMAP_BIT_EXTPIPELINE_CREATE_COLOR_ATTACHMENT_FEEDBACK_LOOP_BIT_EXTPIPELINE_CREATE_DEPTH_STENCIL_ATTACHMENT_FEEDBACK_LOOP_BIT_EXTPIPELINE_CREATE_NO_PROTECTED_ACCESS_BITPIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXTPIPELINE_CREATE_PROTECTED_ACCESS_ONLY_BIT"

var _PipelineCreateFlagBits_map = map[PipelineCreateFlagBits]string{
	1:          _PipelineCreateFlagBits_name[0:40],
	2:          _PipelineCreateFlagBits_name[40:77],
	4:          _PipelineCreateFlagBits_name[77:107],
	8:          _PipelineCreateFlagBits_name[107:155],
	16:         _PipelineCreateFlagBits_name[155:188],
	32:         _PipelineCreateFlagBits_name[188:224],
	64:         _PipelineCreateFlagBits_name[224:266],
	128:        _PipelineCreateFlagBits_name[266:322],
	256:        _PipelineCreateFlagBits_name[322:375],
	512:        _PipelineCreateFlagBits_name[375:418],
	1024:       _PipelineCreateFlagBits_name[418:464],
	2048:       _PipelineCreateFlagBits_name[464:495],
	4096:       _PipelineCreateFlagBits_name[495:545],
	8192:       _PipelineCreateFlagBits_name[545:591],
	16384:      _PipelineCreateFlagBits_name[591:650],
	32768:      _PipelineCreateFlagBits_name[650:713],
	65536:      _PipelineCreateFlagBits_name[713:769],
	131072:     _PipelineCreateFlagBits_name[769:833],
	262144:     _PipelineCreateFlagBits_name[833:873],
	524288:     _PipelineCreateFlagBits_name[873:943],
	1048576:    _PipelineCreateFlagBits_name[943:990],
	2097152:    _PipelineCreateFlagBits_name[990:1056],
	4194304:    _PipelineCreateFlagBits_name[1056:1121],
	8388608:    _PipelineCreateFlagBits_name[1121:1179],
	16777216:   _PipelineCreateFlagBits_name[1179:1231],
	33554432:   _PipelineCreateFlagBits_name[1231:1285],
	67108864:   _PipelineCreateFlagBits_name[1285:1347],
	134217728:  _PipelineCreateFlagBits_name[1347:1386],
	536870912:  _PipelineCreateFlagBits_name[1386:1427],
	1073741824: _PipelineCreateFlagBits_name[1427:1468],
}

func (i PipelineCreateFlagBits) String() string {
	if str, ok := _PipelineCreateFlagBits_map[i]; ok {
		return str
	}
	return "PipelineCreateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_CREATE_2_DISABLE_OPTIMIZATION_BIT-1]
	_ = x[PIPELINE_CREATE_2_ALLOW_DERIVATIVES_BIT-2]
	_ = x[PIPELINE_CREATE_2_LINK_TIME_OPTIMIZATION_BIT_EXT-1024]
	_ = x[PIPELINE_CREATE_2_LIBRARY_BIT_KHR-2048]
	_ = x[PIPELINE_CREATE_2_RAY_TRACING_SKIP_TRIANGLES_BIT_KHR-4096]
	_ = x[PIPELINE_CREATE_2_RAY_TRACING_SKIP_AABBS_BIT_KHR-8192]
	_ = x[PIPELINE_CREATE_2_RAY_TRACING_NO_NULL_ANY_HIT_SHADERS_BIT_KHR-16384]
	_ = x[PIPELINE_CREATE_2_RAY_TRACING_NO_NULL_CLOSEST_HIT_SHADERS_BIT_KHR-32768]
	_ = x[PIPELINE_CREATE_2_RAY_TRACING_NO_NULL_MISS_SHADERS_BIT_KHR-65536]
	_ = x[PIPELINE_CREATE_2_RAY_TRACING_NO_NULL_INTERSECTION_SHADERS_BIT_KHR-131072]
	_ = x[PIPELINE_CREATE_2_INDIRECT_BINDABLE_BIT_NV-262144]
	_ = x[PIPELINE_CREATE_2_RAY_TRACING_SHADER_GROUP_HANDLE_CAPTURE_REPLAY_BIT_KHR-524288]
	_ = x[PIPELINE_CREATE_2_DERIVATIVE_BIT-4]
	_ = x[PIPELINE_CREATE_2_RAY_TRACING_ALLOW_MOTION_BIT_NV-1048576]
	_ = x[PIPELINE_CREATE_2_RENDERING_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR-2097152]
	_ = x[PIPELINE_CREATE_2_RENDERING_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT-4194304]
	_ = x[PIPELINE_CREATE_2_RETAIN_LINK_TIME_OPTIMIZATION_INFO_BIT_EXT-8388608]
	_ = x[PIPELINE_CREATE_2_RAY_TRACING_OPACITY_MICROMAP_BIT_EXT-16777216]
	_ = x[PIPELINE_CREATE_2_COLOR_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT-33554432]
	_ = x[PIPELINE_CREATE_2_DEPTH_STENCIL_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT-67108864]
	_ = x[PIPELINE_CREATE_2_NO_PROTECTED_ACCESS_BIT-134217728]
	_ = x[PIPELINE_CREATE_2_RAY_TRACING_DISPLACEMENT_MICROMAP_BIT_NV-268435456]
	_ = x[PIPELINE_CREATE_2_DESCRIPTOR_BUFFER_BIT_EXT-536870912]
	_ = x[PIPELINE_CREATE_2_VIEW_INDEX_FROM_DEVICE_INDEX_BIT-8]
	_ = x[PIPELINE_CREATE_2_PROTECTED_ACCESS_ONLY_BIT-1073741824]
	_ = x[PIPELINE_CREATE_2_CAPTURE_DATA_BIT_KHR-2147483648]
	_ = x[PIPELINE_CREATE_2_RAY_TRACING_ALLOW_SPHERES_AND_LINEAR_SWEPT_SPHERES_BIT_NV-8589934592]
	_ = x[PIPELINE_CREATE_2_ENABLE_LEGACY_DITHERING_BIT_EXT-17179869184]
	_ = x[PIPELINE_CREATE_2_DISALLOW_OPACITY_MICROMAP_BIT_ARM-137438953472]
	_ = x[PIPELINE_CREATE_2_INDIRECT_BINDABLE_BIT_EXT-274877906944]
	_ = x[PIPELINE_CREATE_2_DISPATCH_BASE_BIT-16]
	_ = x[PIPELINE_CREATE_2_PER_LAYER_FRAGMENT_DENSITY_BIT_VALVE-1099511627776]
	_ = x[PIPELINE_CREATE_2_DEFER_COMPILE_BIT_NV-32]
	_ = x[PIPELINE_CREATE_2_CAPTURE_STATISTICS_BIT_KHR-64]
	_ = x[PIPELINE_CREATE_2_CAPTURE_INTERNAL_REPRESENTATIONS_BIT_KHR-128]
	_ = x[PIPELINE_CREATE_2_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT-256]
	_ = x[PIPELINE_CREATE_2_EARLY_RETURN_ON_FAILURE_BIT-512]
	_ = x[PIPELINE_CREATE_2_ALLOW_DERIVATIVES_BIT_KHR-2]
	_ = x[PIPELINE_CREATE_2_DERIVATIVE_BIT_KHR-4]
	_ = x[PIPELINE_CREATE_2_DISABLE_OPTIMIZATION_BIT_KHR-1]
	_ = x[PIPELINE_CREATE_2_DISPATCH_BASE_BIT_KHR-16]
	_ = x[PIPELINE_CREATE_2_EARLY_RETURN_ON_FAILURE_BIT_KHR-512]
	_ = x[PIPELINE_CREATE_2_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT_KHR-256]
	_ = x[PIPELINE_CREATE_2_NO_PROTECTED_ACCESS_BIT_EXT-134217728]
	_ = x[PIPELINE_CREATE_2_PROTECTED_ACCESS_ONLY_BIT_EXT-1073741824]
	_ = x[PIPELINE_CREATE_2_RAY_TRACING_SKIP_BUILT_IN_PRIMITIVES_BIT_KHR-4096]
	_ = x[PIPELINE_CREATE_2_VIEW_INDEX_FROM_DEVICE_INDEX_BIT_KHR-8]
}

const _PipelineCreateFlagBits2_name = "PIPELINE_CREATE_2_DISABLE_OPTIMIZATION_BITPIPELINE_CREATE_2_ALLOW_DERIVATIVES_BITPIPELINE_CREATE_2_DERIVATIVE_BITPIPELINE_CREATE_2_VIEW_INDEX_FROM_DEVICE_INDEX_BITPIPELINE_CREATE_2_DISPATCH_BASE_BITPIPELINE_CREATE_2_DEFER_COMPILE_BIT_NVPIPELINE_CREATE_2_CAPTURE_STATISTICS_BIT_KHRPIPELINE_CREATE_2_CAPTURE_INTERNAL_REPRESENTATIONS_BIT_KHRPIPELINE_CREATE_2_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BITPIPELINE_CREATE_2_EARLY_RETURN_ON_FAILURE_BITPIPELINE_CREATE_2_LINK_TIME_OPTIMIZATION_BIT_EXTPIPELINE_CREATE_2_LIBRARY_BIT_KHRPIPELINE_CREATE_2_RAY_TRACING_SKIP_TRIANGLES_BIT_KHRPIPELINE_CREATE_2_RAY_TRACING_SKIP_AABBS_BIT_KHRPIPELINE_CREATE_2_RAY_TRACING_NO_NULL_ANY_HIT_SHADERS_BIT_KHRPIPELINE_CREATE_2_RAY_TRACING_NO_NULL_CLOSEST_HIT_SHADERS_BIT_KHRPIPELINE_CREATE_2_RAY_TRACING_NO_NULL_MISS_SHADERS_BIT_KHRPIPELINE_CREATE_2_RAY_TRACING_NO_NULL_INTERSECTION_SHADERS_BIT_KHRPIPELINE_CREATE_2_INDIRECT_BINDABLE_BIT_NVPIPELINE_CREATE_2_RAY_TRACING_SHADER_GROUP_HANDLE_CAPTURE_REPLAY_BIT_KHRPIPELINE_CREATE_2_RAY_TRACING_ALLOW_MOTION_BIT_NVPIPELINE_CREATE_2_RENDERING_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHRPIPELINE_CREATE_2_RENDERING_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXTPIPELINE_CREATE_2_RETAIN_LINK_TIME_OPTIMIZATION_INFO_BIT_EXTPIPELINE_CREATE_2_RAY_TRACING_OPACITY_MICROMAP_BIT_EXTPIPELINE_CREATE_2_COLOR_ATTACHMENT_FEEDBACK_LOOP_BIT_EXTPIPELINE_CREATE_2_DEPTH_STENCIL_ATTACHMENT_FEEDBACK_LOOP_BIT_EXTPIPELINE_CREATE_2_NO_PROTECTED_ACCESS_BITPIPELINE_CREATE_2_RAY_TRACING_DISPLACEMENT_MICROMAP_BIT_NVPIPELINE_CREATE_2_DESCRIPTOR_BUFFER_BIT_EXTPIPELINE_CREATE_2_PROTECTED_ACCESS_ONLY_BITPIPELINE_CREATE_2_CAPTURE_DATA_BIT_KHRPIPELINE_CREATE_2_RAY_TRACING_ALLOW_SPHERES_AND_LINEAR_SWEPT_SPHERES_BIT_NVPIPELINE_CREATE_2_ENABLE_LEGACY_DITHERING_BIT_EXTPIPELINE_CREATE_2_DISALLOW_OPACITY_MICROMAP_BIT_ARMPIPELINE_CREATE_2_INDIRECT_BINDABLE_BIT_EXTPIPELINE_CREATE_2_PER_LAYER_FRAGMENT_DENSITY_BIT_VALVE"

var _PipelineCreateFlagBits2_map = map[PipelineCreateFlagBits2]string{
	1:             _PipelineCreateFlagBits2_name[0:42],
	2:             _PipelineCreateFlagBits2_name[42:81],
	4:             _PipelineCreateFlagBits2_name[81:113],
	8:             _PipelineCreateFlagBits2_name[113:163],
	16:            _PipelineCreateFlagBits2_name[163:198],
	32:            _PipelineCreateFlagBits2_name[198:236],
	64:            _PipelineCreateFlagBits2_name[236:280],
	128:           _PipelineCreateFlagBits2_name[280:338],
	256:           _PipelineCreateFlagBits2_name[338:393],
	512:           _PipelineCreateFlagBits2_name[393:438],
	1024:          _PipelineCreateFlagBits2_name[438:486],
	2048:          _PipelineCreateFlagBits2_name[486:519],
	4096:          _PipelineCreateFlagBits2_name[519:571],
	8192:          _PipelineCreateFlagBits2_name[571:619],
	16384:         _PipelineCreateFlagBits2_name[619:680],
	32768:         _PipelineCreateFlagBits2_name[680:745],
	65536:         _PipelineCreateFlagBits2_name[745:803],
	131072:        _PipelineCreateFlagBits2_name[803:869],
	262144:        _PipelineCreateFlagBits2_name[869:911],
	524288:        _PipelineCreateFlagBits2_name[911:983],
	1048576:       _PipelineCreateFlagBits2_name[983:1032],
	2097152:       _PipelineCreateFlagBits2_name[1032:1100],
	4194304:       _PipelineCreateFlagBits2_name[1100:1167],
	8388608:       _PipelineCreateFlagBits2_name[1167:1227],
	16777216:      _PipelineCreateFlagBits2_name[1227:1281],
	33554432:      _PipelineCreateFlagBits2_name[1281:1337],
	67108864:      _PipelineCreateFlagBits2_name[1337:1401],
	134217728:     _PipelineCreateFlagBits2_name[1401:1442],
	268435456:     _PipelineCreateFlagBits2_name[1442:1500],
	536870912:     _PipelineCreateFlagBits2_name[1500:1543],
	1073741824:    _PipelineCreateFlagBits2_name[1543:1586],
	2147483648:    _PipelineCreateFlagBits2_name[1586:1624],
	8589934592:    _PipelineCreateFlagBits2_name[1624:1699],
	17179869184:   _PipelineCreateFlagBits2_name[1699:1748],
	137438953472:  _PipelineCreateFlagBits2_name[1748:1799],
	274877906944:  _PipelineCreateFlagBits2_name[1799:1842],
	1099511627776: _PipelineCreateFlagBits2_name[1842:1896],
}

func (i PipelineCreateFlagBits2) String() string {
	if str, ok := _PipelineCreateFlagBits2_map[i]; ok {
		return str
	}
	return "PipelineCreateFlagBits2(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_CREATION_FEEDBACK_VALID_BIT-1]
	_ = x[PIPELINE_CREATION_FEEDBACK_APPLICATION_PIPELINE_CACHE_HIT_BIT-2]
	_ = x[PIPELINE_CREATION_FEEDBACK_BASE_PIPELINE_ACCELERATION_BIT-4]
	_ = x[PIPELINE_CREATION_FEEDBACK_APPLICATION_PIPELINE_CACHE_HIT_BIT_EXT-2]
	_ = x[PIPELINE_CREATION_FEEDBACK_BASE_PIPELINE_ACCELERATION_BIT_EXT-4]
	_ = x[PIPELINE_CREATION_FEEDBACK_VALID_BIT_EXT-1]
}

const (
	_PipelineCreationFeedbackFlagBits_name_0 = "PIPELINE_CREATION_FEEDBACK_VALID_BITPIPELINE_CREATION_FEEDBACK_APPLICATION_PIPELINE_CACHE_HIT_BIT"
	_PipelineCreationFeedbackFlagBits_name_1 = "PIPELINE_CREATION_FEEDBACK_BASE_PIPELINE_ACCELERATION_BIT"
)

var (
	_PipelineCreationFeedbackFlagBits_index_0 = [...]uint8{0, 36, 97}
)

func (i PipelineCreationFeedbackFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _PipelineCreationFeedbackFlagBits_name_0[_PipelineCreationFeedbackFlagBits_index_0[i]:_PipelineCreationFeedbackFlagBits_index_0[i+1]]
	case i == 4:
		return _PipelineCreationFeedbackFlagBits_name_1
	default:
		return "PipelineCreationFeedbackFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_DEPTH_STENCIL_STATE_CREATE_RASTERIZATION_ORDER_ATTACHMENT_DEPTH_ACCESS_BIT_EXT-1]
	_ = x[PIPELINE_DEPTH_STENCIL_STATE_CREATE_RASTERIZATION_ORDER_ATTACHMENT_STENCIL_ACCESS_BIT_EXT-2]
	_ = x[PIPELINE_DEPTH_STENCIL_STATE_CREATE_RASTERIZATION_ORDER_ATTACHMENT_DEPTH_ACCESS_BIT_ARM-1]
	_ = x[PIPELINE_DEPTH_STENCIL_STATE_CREATE_RASTERIZATION_ORDER_ATTACHMENT_STENCIL_ACCESS_BIT_ARM-2]
}

const _PipelineDepthStencilStateCreateFlagBits_name = "PIPELINE_DEPTH_STENCIL_STATE_CREATE_RASTERIZATION_ORDER_ATTACHMENT_DEPTH_ACCESS_BIT_EXTPIPELINE_DEPTH_STENCIL_STATE_CREATE_RASTERIZATION_ORDER_ATTACHMENT_STENCIL_ACCESS_BIT_EXT"

var _PipelineDepthStencilStateCreateFlagBits_index = [...]uint8{0, 87, 176}

func (i PipelineDepthStencilStateCreateFlagBits) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_PipelineDepthStencilStateCreateFlagBits_index)-1 {
		return "PipelineDepthStencilStateCreateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PipelineDepthStencilStateCreateFlagBits_name[_PipelineDepthStencilStateCreateFlagBits_index[idx]:_PipelineDepthStencilStateCreateFlagBits_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_EXECUTABLE_STATISTIC_FORMAT_BOOL32_KHR-0]
	_ = x[PIPELINE_EXECUTABLE_STATISTIC_FORMAT_INT64_KHR-1]
	_ = x[PIPELINE_EXECUTABLE_STATISTIC_FORMAT_UINT64_KHR-2]
	_ = x[PIPELINE_EXECUTABLE_STATISTIC_FORMAT_FLOAT64_KHR-3]
}

const _PipelineExecutableStatisticFormatKHR_name = "PIPELINE_EXECUTABLE_STATISTIC_FORMAT_BOOL32_KHRPIPELINE_EXECUTABLE_STATISTIC_FORMAT_INT64_KHRPIPELINE_EXECUTABLE_STATISTIC_FORMAT_UINT64_KHRPIPELINE_EXECUTABLE_STATISTIC_FORMAT_FLOAT64_KHR"

var _PipelineExecutableStatisticFormatKHR_index = [...]uint8{0, 47, 93, 140, 188}

func (i PipelineExecutableStatisticFormatKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PipelineExecutableStatisticFormatKHR_index)-1 {
		return "PipelineExecutableStatisticFormatKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PipelineExecutableStatisticFormatKHR_name[_PipelineExecutableStatisticFormatKHR_index[idx]:_PipelineExecutableStatisticFormatKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_LAYOUT_CREATE_INDEPENDENT_SETS_BIT_EXT-2]
}

const _PipelineLayoutCreateFlagBits_name = "PIPELINE_LAYOUT_CREATE_INDEPENDENT_SETS_BIT_EXT"

var _PipelineLayoutCreateFlagBits_index = [...]uint8{0, 47}

func (i PipelineLayoutCreateFlagBits) String() string {
	idx := int(i) - 2
	if i < 2 || idx >= len(_PipelineLayoutCreateFlagBits_index)-1 {
		return "PipelineLayoutCreateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PipelineLayoutCreateFlagBits_name[_PipelineLayoutCreateFlagBits_index[idx]:_PipelineLayoutCreateFlagBits_index[idx+1]]
}
