// Code generated by "stringer -output=enum_string_6.go -type=PipelineRobustnessBufferBehavior,PipelineRobustnessImageBehavior,PipelineShaderStageCreateFlagBits,PipelineStageFlagBits,PipelineStageFlagBits2,PointClippingBehavior,PolygonMode,PresentGravityFlagBitsKHR,PresentModeKHR,PresentScalingFlagBitsKHR,PrimitiveTopology,ProvokingVertexModeEXT,QueryControlFlagBits,QueryPipelineStatisticFlagBits,QueryPoolCreateFlagBits,QueryPoolSamplingModeINTEL,QueryResultFlagBits,QueryResultStatusKHR,QueryType,QueueFlagBits,QueueGlobalPriority,RasterizationOrderAMD,RayTracingInvocationReorderModeNV,RayTracingLssIndexingModeNV,RayTracingLssPrimitiveEndCapsModeNV,RayTracingShaderGroupTypeKHR,RenderPassCreateFlagBits,RenderingFlagBits,ResolveModeFlagBits,Result,SampleCountFlagBits"; DO NOT EDIT.

package vk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_DEVICE_DEFAULT-0]
	_ = x[PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_DISABLED-1]
	_ = x[PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_ROBUST_BUFFER_ACCESS-2]
	_ = x[PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_ROBUST_BUFFER_ACCESS_2-3]
	_ = x[PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_DEVICE_DEFAULT_EXT-0]
	_ = x[PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_DISABLED_EXT-1]
	_ = x[PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_ROBUST_BUFFER_ACCESS_EXT-2]
	_ = x[PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_ROBUST_BUFFER_ACCESS_2_EXT-3]
}

const _PipelineRobustnessBufferBehavior_name = "PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_DEVICE_DEFAULTPIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_DISABLEDPIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_ROBUST_BUFFER_ACCESSPIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_ROBUST_BUFFER_ACCESS_2"

var _PipelineRobustnessBufferBehavior_index = [...]uint8{0, 50, 94, 150, 208}

func (i PipelineRobustnessBufferBehavior) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PipelineRobustnessBufferBehavior_index)-1 {
		return "PipelineRobustnessBufferBehavior(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PipelineRobustnessBufferBehavior_name[_PipelineRobustnessBufferBehavior_index[idx]:_PipelineRobustnessBufferBehavior_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_DEVICE_DEFAULT-0]
	_ = x[PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_DISABLED-1]
	_ = x[PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_ROBUST_IMAGE_ACCESS-2]
	_ = x[PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_ROBUST_IMAGE_ACCESS_2-3]
	_ = x[PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_DEVICE_DEFAULT_EXT-0]
	_ = x[PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_DISABLED_EXT-1]
	_ = x[PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_ROBUST_IMAGE_ACCESS_EXT-2]
	_ = x[PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_ROBUST_IMAGE_ACCESS_2_EXT-3]
}

const _PipelineRobustnessImageBehavior_name = "PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_DEVICE_DEFAULTPIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_DISABLEDPIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_ROBUST_IMAGE_ACCESSPIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_ROBUST_IMAGE_ACCESS_2"

var _PipelineRobustnessImageBehavior_index = [...]uint8{0, 49, 92, 146, 202}

func (i PipelineRobustnessImageBehavior) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PipelineRobustnessImageBehavior_index)-1 {
		return "PipelineRobustnessImageBehavior(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PipelineRobustnessImageBehavior_name[_PipelineRobustnessImageBehavior_index[idx]:_PipelineRobustnessImageBehavior_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT-1]
	_ = x[PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT-2]
	_ = x[PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT-1]
	_ = x[PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT-2]
}

const _PipelineShaderStageCreateFlagBits_name = "PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BITPIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT"

var _PipelineShaderStageCreateFlagBits_index = [...]uint8{0, 60, 115}

func (i PipelineShaderStageCreateFlagBits) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_PipelineShaderStageCreateFlagBits_index)-1 {
		return "PipelineShaderStageCreateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PipelineShaderStageCreateFlagBits_name[_PipelineShaderStageCreateFlagBits_index[idx]:_PipelineShaderStageCreateFlagBits_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_STAGE_NONE-0]
	_ = x[PIPELINE_STAGE_TOP_OF_PIPE_BIT-1]
	_ = x[PIPELINE_STAGE_DRAW_INDIRECT_BIT-2]
	_ = x[PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT-1024]
	_ = x[PIPELINE_STAGE_COMPUTE_SHADER_BIT-2048]
	_ = x[PIPELINE_STAGE_TRANSFER_BIT-4096]
	_ = x[PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT-8192]
	_ = x[PIPELINE_STAGE_HOST_BIT-16384]
	_ = x[PIPELINE_STAGE_ALL_GRAPHICS_BIT-32768]
	_ = x[PIPELINE_STAGE_ALL_COMMANDS_BIT-65536]
	_ = x[PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_EXT-131072]
	_ = x[PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT-262144]
	_ = x[PIPELINE_STAGE_TASK_SHADER_BIT_EXT-524288]
	_ = x[PIPELINE_STAGE_VERTEX_INPUT_BIT-4]
	_ = x[PIPELINE_STAGE_MESH_SHADER_BIT_EXT-1048576]
	_ = x[PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR-2097152]
	_ = x[PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR-4194304]
	_ = x[PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT-8388608]
	_ = x[PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT-16777216]
	_ = x[PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR-33554432]
	_ = x[PIPELINE_STAGE_VERTEX_SHADER_BIT-8]
	_ = x[PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT-16]
	_ = x[PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT-32]
	_ = x[PIPELINE_STAGE_GEOMETRY_SHADER_BIT-64]
	_ = x[PIPELINE_STAGE_FRAGMENT_SHADER_BIT-128]
	_ = x[PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT-256]
	_ = x[PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT-512]
	_ = x[PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_NV-33554432]
	_ = x[PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_NV-131072]
	_ = x[PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV-4194304]
	_ = x[PIPELINE_STAGE_MESH_SHADER_BIT_NV-1048576]
	_ = x[PIPELINE_STAGE_NONE_KHR-0]
	_ = x[PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_NV-2097152]
	_ = x[PIPELINE_STAGE_TASK_SHADER_BIT_NV-524288]
}

const _PipelineStageFlagBits_name = "PIPELINE_STAGE_NONEPIPELINE_STAGE_TOP_OF_PIPE_BITPIPELINE_STAGE_DRAW_INDIRECT_BITPIPELINE_STAGE_VERTEX_INPUT_BITPIPELINE_STAGE_VERTEX_SHADER_BITPIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BITPIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BITPIPELINE_STAGE_GEOMETRY_SHADER_BITPIPELINE_STAGE_FRAGMENT_SHADER_BITPIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BITPIPELINE_STAGE_LATE_FRAGMENT_TESTS_BITPIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BITPIPELINE_STAGE_COMPUTE_SHADER_BITPIPELINE_STAGE_TRANSFER_BITPIPELINE_STAGE_BOTTOM_OF_PIPE_BITPIPELINE_STAGE_HOST_BITPIPELINE_STAGE_ALL_GRAPHICS_BITPIPELINE_STAGE_ALL_COMMANDS_BITPIPELINE_STAGE_COMMAND_PREPROCESS_BIT_EXTPIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXTPIPELINE_STAGE_TASK_SHADER_BIT_EXTPIPELINE_STAGE_MESH_SHADER_BIT_EXTPIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHRPIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHRPIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXTPIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXTPIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR"

var _PipelineStageFlagBits_map = map[PipelineStageFlagBits]string{
	0:        _PipelineStageFlagBits_name[0:19],
	1:        _PipelineStageFlagBits_name[19:49],
	2:        _PipelineStageFlagBits_name[49:81],
	4:        _PipelineStageFlagBits_name[81:112],
	8:        _PipelineStageFlagBits_name[112:144],
	16:       _PipelineStageFlagBits_name[144:190],
	32:       _PipelineStageFlagBits_name[190:239],
	64:       _PipelineStageFlagBits_name[239:273],
	128:      _PipelineStageFlagBits_name[273:307],
	256:      _PipelineStageFlagBits_name[307:346],
	512:      _PipelineStageFlagBits_name[346:384],
	1024:     _PipelineStageFlagBits_name[384:426],
	2048:     _PipelineStageFlagBits_name[426:459],
	4096:     _PipelineStageFlagBits_name[459:486],
	8192:     _PipelineStageFlagBits_name[486:519],
	16384:    _PipelineStageFlagBits_name[519:542],
	32768:    _PipelineStageFlagBits_name[542:573],
	65536:    _PipelineStageFlagBits_name[573:604],
	131072:   _PipelineStageFlagBits_name[604:645],
	262144:   _PipelineStageFlagBits_name[645:689],
	524288:   _PipelineStageFlagBits_name[689:723],
	1048576:  _PipelineStageFlagBits_name[723:757],
	2097152:  _PipelineStageFlagBits_name[757:798],
	4194304:  _PipelineStageFlagBits_name[798:853],
	8388608:  _PipelineStageFlagBits_name[853:900],
	16777216: _PipelineStageFlagBits_name[900:941],
	33554432: _PipelineStageFlagBits_name[941:992],
}

func (i PipelineStageFlagBits) String() string {
	if str, ok := _PipelineStageFlagBits_map[i]; ok {
		return str
	}
	return "PipelineStageFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PIPELINE_STAGE_2_NONE-0]
	_ = x[PIPELINE_STAGE_2_TOP_OF_PIPE_BIT-1]
	_ = x[PIPELINE_STAGE_2_DRAW_INDIRECT_BIT-2]
	_ = x[PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT-1024]
	_ = x[PIPELINE_STAGE_2_COMPUTE_SHADER_BIT-2048]
	_ = x[PIPELINE_STAGE_2_ALL_TRANSFER_BIT-4096]
	_ = x[PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT-8192]
	_ = x[PIPELINE_STAGE_2_HOST_BIT-16384]
	_ = x[PIPELINE_STAGE_2_ALL_GRAPHICS_BIT-32768]
	_ = x[PIPELINE_STAGE_2_ALL_COMMANDS_BIT-65536]
	_ = x[PIPELINE_STAGE_2_COMMAND_PREPROCESS_BIT_EXT-131072]
	_ = x[PIPELINE_STAGE_2_CONDITIONAL_RENDERING_BIT_EXT-262144]
	_ = x[PIPELINE_STAGE_2_TASK_SHADER_BIT_EXT-524288]
	_ = x[PIPELINE_STAGE_2_VERTEX_INPUT_BIT-4]
	_ = x[PIPELINE_STAGE_2_MESH_SHADER_BIT_EXT-1048576]
	_ = x[PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_KHR-2097152]
	_ = x[PIPELINE_STAGE_2_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR-4194304]
	_ = x[PIPELINE_STAGE_2_FRAGMENT_DENSITY_PROCESS_BIT_EXT-8388608]
	_ = x[PIPELINE_STAGE_2_TRANSFORM_FEEDBACK_BIT_EXT-16777216]
	_ = x[PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR-33554432]
	_ = x[PIPELINE_STAGE_2_VIDEO_DECODE_BIT_KHR-67108864]
	_ = x[PIPELINE_STAGE_2_VIDEO_ENCODE_BIT_KHR-134217728]
	_ = x[PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR-268435456]
	_ = x[PIPELINE_STAGE_2_OPTICAL_FLOW_BIT_NV-536870912]
	_ = x[PIPELINE_STAGE_2_VERTEX_SHADER_BIT-8]
	_ = x[PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT-1073741824]
	_ = x[PIPELINE_STAGE_2_COPY_BIT-4294967296]
	_ = x[PIPELINE_STAGE_2_RESOLVE_BIT-8589934592]
	_ = x[PIPELINE_STAGE_2_BLIT_BIT-17179869184]
	_ = x[PIPELINE_STAGE_2_CLEAR_BIT-34359738368]
	_ = x[PIPELINE_STAGE_2_INDEX_INPUT_BIT-68719476736]
	_ = x[PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT-137438953472]
	_ = x[PIPELINE_STAGE_2_PRE_RASTERIZATION_SHADERS_BIT-274877906944]
	_ = x[PIPELINE_STAGE_2_SUBPASS_SHADER_BIT_HUAWEI-549755813888]
	_ = x[PIPELINE_STAGE_2_TESSELLATION_CONTROL_SHADER_BIT-16]
	_ = x[PIPELINE_STAGE_2_INVOCATION_MASK_BIT_HUAWEI-1099511627776]
	_ = x[PIPELINE_STAGE_2_CLUSTER_CULLING_SHADER_BIT_HUAWEI-2199023255552]
	_ = x[PIPELINE_STAGE_2_DATA_GRAPH_BIT_ARM-4398046511104]
	_ = x[PIPELINE_STAGE_2_CONVERT_COOPERATIVE_VECTOR_MATRIX_BIT_NV-17592186044416]
	_ = x[PIPELINE_STAGE_2_COPY_INDIRECT_BIT_KHR-70368744177664]
	_ = x[PIPELINE_STAGE_2_TESSELLATION_EVALUATION_SHADER_BIT-32]
	_ = x[PIPELINE_STAGE_2_GEOMETRY_SHADER_BIT-64]
	_ = x[PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT-128]
	_ = x[PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT-256]
	_ = x[PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT-512]
	_ = x[PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_NV-33554432]
	_ = x[PIPELINE_STAGE_2_ALL_COMMANDS_BIT_KHR-65536]
	_ = x[PIPELINE_STAGE_2_ALL_GRAPHICS_BIT_KHR-32768]
	_ = x[PIPELINE_STAGE_2_TRANSFER_BIT-4096]
	_ = x[PIPELINE_STAGE_2_TRANSFER_BIT_KHR-4096]
	_ = x[PIPELINE_STAGE_2_ALL_TRANSFER_BIT_KHR-4096]
	_ = x[PIPELINE_STAGE_2_BLIT_BIT_KHR-17179869184]
	_ = x[PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT_KHR-8192]
	_ = x[PIPELINE_STAGE_2_CLEAR_BIT_KHR-34359738368]
	_ = x[PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT_KHR-1024]
	_ = x[PIPELINE_STAGE_2_COMMAND_PREPROCESS_BIT_NV-131072]
	_ = x[PIPELINE_STAGE_2_COMPUTE_SHADER_BIT_KHR-2048]
	_ = x[PIPELINE_STAGE_2_COPY_BIT_KHR-4294967296]
	_ = x[PIPELINE_STAGE_2_DRAW_INDIRECT_BIT_KHR-2]
	_ = x[PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT_KHR-256]
	_ = x[PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT_KHR-128]
	_ = x[PIPELINE_STAGE_2_SHADING_RATE_IMAGE_BIT_NV-4194304]
	_ = x[PIPELINE_STAGE_2_GEOMETRY_SHADER_BIT_KHR-64]
	_ = x[PIPELINE_STAGE_2_HOST_BIT_KHR-16384]
	_ = x[PIPELINE_STAGE_2_INDEX_INPUT_BIT_KHR-68719476736]
	_ = x[PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT_KHR-512]
	_ = x[PIPELINE_STAGE_2_MESH_SHADER_BIT_NV-1048576]
	_ = x[PIPELINE_STAGE_2_NONE_KHR-0]
	_ = x[PIPELINE_STAGE_2_PRE_RASTERIZATION_SHADERS_BIT_KHR-274877906944]
	_ = x[PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_NV-2097152]
	_ = x[PIPELINE_STAGE_2_RESOLVE_BIT_KHR-8589934592]
	_ = x[PIPELINE_STAGE_2_SUBPASS_SHADING_BIT_HUAWEI-549755813888]
	_ = x[PIPELINE_STAGE_2_TASK_SHADER_BIT_NV-524288]
	_ = x[PIPELINE_STAGE_2_TESSELLATION_CONTROL_SHADER_BIT_KHR-16]
	_ = x[PIPELINE_STAGE_2_TESSELLATION_EVALUATION_SHADER_BIT_KHR-32]
	_ = x[PIPELINE_STAGE_2_TOP_OF_PIPE_BIT_KHR-1]
	_ = x[PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT_KHR-137438953472]
	_ = x[PIPELINE_STAGE_2_VERTEX_INPUT_BIT_KHR-4]
	_ = x[PIPELINE_STAGE_2_VERTEX_SHADER_BIT_KHR-8]
}

const _PipelineStageFlagBits2_name = "PIPELINE_STAGE_2_NONEPIPELINE_STAGE_2_TOP_OF_PIPE_BITPIPELINE_STAGE_2_DRAW_INDIRECT_BITPIPELINE_STAGE_2_VERTEX_INPUT_BITPIPELINE_STAGE_2_VERTEX_SHADER_BITPIPELINE_STAGE_2_TESSELLATION_CONTROL_SHADER_BITPIPELINE_STAGE_2_TESSELLATION_EVALUATION_SHADER_BITPIPELINE_STAGE_2_GEOMETRY_SHADER_BITPIPELINE_STAGE_2_FRAGMENT_SHADER_BITPIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BITPIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BITPIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BITPIPELINE_STAGE_2_COMPUTE_SHADER_BITPIPELINE_STAGE_2_ALL_TRANSFER_BITPIPELINE_STAGE_2_BOTTOM_OF_PIPE_BITPIPELINE_STAGE_2_HOST_BITPIPELINE_STAGE_2_ALL_GRAPHICS_BITPIPELINE_STAGE_2_ALL_COMMANDS_BITPIPELINE_STAGE_2_COMMAND_PREPROCESS_BIT_EXTPIPELINE_STAGE_2_CONDITIONAL_RENDERING_BIT_EXTPIPELINE_STAGE_2_TASK_SHADER_BIT_EXTPIPELINE_STAGE_2_MESH_SHADER_BIT_EXTPIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_KHRPIPELINE_STAGE_2_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHRPIPELINE_STAGE_2_FRAGMENT_DENSITY_PROCESS_BIT_EXTPIPELINE_STAGE_2_TRANSFORM_FEEDBACK_BIT_EXTPIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHRPIPELINE_STAGE_2_VIDEO_DECODE_BIT_KHRPIPELINE_STAGE_2_VIDEO_ENCODE_BIT_KHRPIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHRPIPELINE_STAGE_2_OPTICAL_FLOW_BIT_NVPIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXTPIPELINE_STAGE_2_COPY_BITPIPELINE_STAGE_2_RESOLVE_BITPIPELINE_STAGE_2_BLIT_BITPIPELINE_STAGE_2_CLEAR_BITPIPELINE_STAGE_2_INDEX_INPUT_BITPIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BITPIPELINE_STAGE_2_PRE_RASTERIZATION_SHADERS_BITPIPELINE_STAGE_2_SUBPASS_SHADER_BIT_HUAWEIPIPELINE_STAGE_2_INVOCATION_MASK_BIT_HUAWEIPIPELINE_STAGE_2_CLUSTER_CULLING_SHADER_BIT_HUAWEIPIPELINE_STAGE_2_DATA_GRAPH_BIT_ARMPIPELINE_STAGE_2_CONVERT_COOPERATIVE_VECTOR_MATRIX_BIT_NVPIPELINE_STAGE_2_COPY_INDIRECT_BIT_KHR"

var _PipelineStageFlagBits2_map = map[PipelineStageFlagBits2]string{
	0:              _PipelineStageFlagBits2_name[0:21],
	1:              _PipelineStageFlagBits2_name[21:53],
	2:              _PipelineStageFlagBits2_name[53:87],
	4:              _PipelineStageFlagBits2_name[87:120],
	8:              _PipelineStageFlagBits2_name[120:154],
	16:             _PipelineStageFlagBits2_name[154:202],
	32:             _PipelineStageFlagBits2_name[202:253],
	64:             _PipelineStageFlagBits2_name[253:289],
	128:            _PipelineStageFlagBits2_name[289:325],
	256:            _PipelineStageFlagBits2_name[325:366],
	512:            _PipelineStageFlagBits2_name[366:406],
	1024:           _PipelineStageFlagBits2_name[406:450],
	2048:           _PipelineStageFlagBits2_name[450:485],
	4096:           _PipelineStageFlagBits2_name[485:518],
	8192:           _PipelineStageFlagBits2_name[518:553],
	16384:          _PipelineStageFlagBits2_name[553:578],
	32768:          _PipelineStageFlagBits2_name[578:611],
	65536:          _PipelineStageFlagBits2_name[611:644],
	131072:         _PipelineStageFlagBits2_name[644:687],
	262144:         _PipelineStageFlagBits2_name[687:733],
	524288:         _PipelineStageFlagBits2_name[733:769],
	1048576:        _PipelineStageFlagBits2_name[769:805],
	2097152:        _PipelineStageFlagBits2_name[805:848],
	4194304:        _PipelineStageFlagBits2_name[848:905],
	8388608:        _PipelineStageFlagBits2_name[905:954],
	16777216:       _PipelineStageFlagBits2_name[954:997],
	33554432:       _PipelineStageFlagBits2_name[997:1050],
	67108864:       _PipelineStageFlagBits2_name[1050:1087],
	134217728:      _PipelineStageFlagBits2_name[1087:1124],
	268435456:      _PipelineStageFlagBits2_name[1124:1176],
	536870912:      _PipelineStageFlagBits2_name[1176:1212],
	1073741824:     _PipelineStageFlagBits2_name[1212:1251],
	4294967296:     _PipelineStageFlagBits2_name[1251:1276],
	8589934592:     _PipelineStageFlagBits2_name[1276:1304],
	17179869184:    _PipelineStageFlagBits2_name[1304:1329],
	34359738368:    _PipelineStageFlagBits2_name[1329:1355],
	68719476736:    _PipelineStageFlagBits2_name[1355:1387],
	137438953472:   _PipelineStageFlagBits2_name[1387:1430],
	274877906944:   _PipelineStageFlagBits2_name[1430:1476],
	549755813888:   _PipelineStageFlagBits2_name[1476:1518],
	1099511627776:  _PipelineStageFlagBits2_name[1518:1561],
	2199023255552:  _PipelineStageFlagBits2_name[1561:1611],
	4398046511104:  _PipelineStageFlagBits2_name[1611:1646],
	17592186044416: _PipelineStageFlagBits2_name[1646:1703],
	70368744177664: _PipelineStageFlagBits2_name[1703:1741],
}

func (i PipelineStageFlagBits2) String() string {
	if str, ok := _PipelineStageFlagBits2_map[i]; ok {
		return str
	}
	return "PipelineStageFlagBits2(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANES-0]
	_ = x[POINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY-1]
	_ = x[POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANES_KHR-0]
	_ = x[POINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY_KHR-1]
}

const _PointClippingBehavior_name = "POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANESPOINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY"

var _PointClippingBehavior_index = [...]uint8{0, 39, 84}

func (i PointClippingBehavior) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PointClippingBehavior_index)-1 {
		return "PointClippingBehavior(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PointClippingBehavior_name[_PointClippingBehavior_index[idx]:_PointClippingBehavior_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[POLYGON_MODE_FILL-0]
	_ = x[POLYGON_MODE_LINE-1]
	_ = x[POLYGON_MODE_POINT-2]
	_ = x[POLYGON_MODE_FILL_RECTANGLE_NV-1000153000]
}

const (
	_PolygonMode_name_0 = "POLYGON_MODE_FILLPOLYGON_MODE_LINEPOLYGON_MODE_POINT"
	_PolygonMode_name_1 = "POLYGON_MODE_FILL_RECTANGLE_NV"
)

var (
	_PolygonMode_index_0 = [...]uint8{0, 17, 34, 52}
)

func (i PolygonMode) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _PolygonMode_name_0[_PolygonMode_index_0[i]:_PolygonMode_index_0[i+1]]
	case i == 1000153000:
		return _PolygonMode_name_1
	default:
		return "PolygonMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PRESENT_GRAVITY_MIN_BIT_KHR-1]
	_ = x[PRESENT_GRAVITY_MAX_BIT_KHR-2]
	_ = x[PRESENT_GRAVITY_CENTERED_BIT_KHR-4]
	_ = x[PRESENT_GRAVITY_CENTERED_BIT_EXT-4]
	_ = x[PRESENT_GRAVITY_MAX_BIT_EXT-2]
	_ = x[PRESENT_GRAVITY_MIN_BIT_EXT-1]
}

const (
	_PresentGravityFlagBitsKHR_name_0 = "PRESENT_GRAVITY_MIN_BIT_KHRPRESENT_GRAVITY_MAX_BIT_KHR"
	_PresentGravityFlagBitsKHR_name_1 = "PRESENT_GRAVITY_CENTERED_BIT_KHR"
)

var (
	_PresentGravityFlagBitsKHR_index_0 = [...]uint8{0, 27, 54}
)

func (i PresentGravityFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _PresentGravityFlagBitsKHR_name_0[_PresentGravityFlagBitsKHR_index_0[i]:_PresentGravityFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _PresentGravityFlagBitsKHR_name_1
	default:
		return "PresentGravityFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PRESENT_MODE_IMMEDIATE_KHR-0]
	_ = x[PRESENT_MODE_MAILBOX_KHR-1]
	_ = x[PRESENT_MODE_FIFO_KHR-2]
	_ = x[PRESENT_MODE_FIFO_RELAXED_KHR-3]
	_ = x[PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR-1000111000]
	_ = x[PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR-1000111001]
	_ = x[PRESENT_MODE_FIFO_LATEST_READY_KHR-1000621000]
	_ = x[PRESENT_MODE_FIFO_LATEST_READY_EXT-1000621000]
}

const (
	_PresentModeKHR_name_0 = "PRESENT_MODE_IMMEDIATE_KHRPRESENT_MODE_MAILBOX_KHRPRESENT_MODE_FIFO_KHRPRESENT_MODE_FIFO_RELAXED_KHR"
	_PresentModeKHR_name_1 = "PRESENT_MODE_SHARED_DEMAND_REFRESH_KHRPRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR"
	_PresentModeKHR_name_2 = "PRESENT_MODE_FIFO_LATEST_READY_KHR"
)

var (
	_PresentModeKHR_index_0 = [...]uint8{0, 26, 50, 71, 100}
	_PresentModeKHR_index_1 = [...]uint8{0, 38, 80}
)

func (i PresentModeKHR) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _PresentModeKHR_name_0[_PresentModeKHR_index_0[i]:_PresentModeKHR_index_0[i+1]]
	case 1000111000 <= i && i <= 1000111001:
		i -= 1000111000
		return _PresentModeKHR_name_1[_PresentModeKHR_index_1[i]:_PresentModeKHR_index_1[i+1]]
	case i == 1000621000:
		return _PresentModeKHR_name_2
	default:
		return "PresentModeKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PRESENT_SCALING_ONE_TO_ONE_BIT_KHR-1]
	_ = x[PRESENT_SCALING_ASPECT_RATIO_STRETCH_BIT_KHR-2]
	_ = x[PRESENT_SCALING_STRETCH_BIT_KHR-4]
	_ = x[PRESENT_SCALING_ASPECT_RATIO_STRETCH_BIT_EXT-2]
	_ = x[PRESENT_SCALING_ONE_TO_ONE_BIT_EXT-1]
	_ = x[PRESENT_SCALING_STRETCH_BIT_EXT-4]
}

const (
	_PresentScalingFlagBitsKHR_name_0 = "PRESENT_SCALING_ONE_TO_ONE_BIT_KHRPRESENT_SCALING_ASPECT_RATIO_STRETCH_BIT_KHR"
	_PresentScalingFlagBitsKHR_name_1 = "PRESENT_SCALING_STRETCH_BIT_KHR"
)

var (
	_PresentScalingFlagBitsKHR_index_0 = [...]uint8{0, 34, 78}
)

func (i PresentScalingFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _PresentScalingFlagBitsKHR_name_0[_PresentScalingFlagBitsKHR_index_0[i]:_PresentScalingFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _PresentScalingFlagBitsKHR_name_1
	default:
		return "PresentScalingFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PRIMITIVE_TOPOLOGY_POINT_LIST-0]
	_ = x[PRIMITIVE_TOPOLOGY_LINE_LIST-1]
	_ = x[PRIMITIVE_TOPOLOGY_LINE_STRIP-2]
	_ = x[PRIMITIVE_TOPOLOGY_TRIANGLE_LIST-3]
	_ = x[PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP-4]
	_ = x[PRIMITIVE_TOPOLOGY_TRIANGLE_FAN-5]
	_ = x[PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY-6]
	_ = x[PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY-7]
	_ = x[PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY-8]
	_ = x[PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY-9]
	_ = x[PRIMITIVE_TOPOLOGY_PATCH_LIST-10]
}

const _PrimitiveTopology_name = "PRIMITIVE_TOPOLOGY_POINT_LISTPRIMITIVE_TOPOLOGY_LINE_LISTPRIMITIVE_TOPOLOGY_LINE_STRIPPRIMITIVE_TOPOLOGY_TRIANGLE_LISTPRIMITIVE_TOPOLOGY_TRIANGLE_STRIPPRIMITIVE_TOPOLOGY_TRIANGLE_FANPRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCYPRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCYPRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCYPRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCYPRIMITIVE_TOPOLOGY_PATCH_LIST"

var _PrimitiveTopology_index = [...]uint16{0, 29, 57, 86, 118, 151, 182, 225, 269, 316, 364, 393}

func (i PrimitiveTopology) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PrimitiveTopology_index)-1 {
		return "PrimitiveTopology(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrimitiveTopology_name[_PrimitiveTopology_index[idx]:_PrimitiveTopology_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PROVOKING_VERTEX_MODE_FIRST_VERTEX_EXT-0]
	_ = x[PROVOKING_VERTEX_MODE_LAST_VERTEX_EXT-1]
}

const _ProvokingVertexModeEXT_name = "PROVOKING_VERTEX_MODE_FIRST_VERTEX_EXTPROVOKING_VERTEX_MODE_LAST_VERTEX_EXT"

var _ProvokingVertexModeEXT_index = [...]uint8{0, 38, 75}

func (i ProvokingVertexModeEXT) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ProvokingVertexModeEXT_index)-1 {
		return "ProvokingVertexModeEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProvokingVertexModeEXT_name[_ProvokingVertexModeEXT_index[idx]:_ProvokingVertexModeEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QUERY_CONTROL_PRECISE_BIT-1]
}

const _QueryControlFlagBits_name = "QUERY_CONTROL_PRECISE_BIT"

var _QueryControlFlagBits_index = [...]uint8{0, 25}

func (i QueryControlFlagBits) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_QueryControlFlagBits_index)-1 {
		return "QueryControlFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QueryControlFlagBits_name[_QueryControlFlagBits_index[idx]:_QueryControlFlagBits_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT-1]
	_ = x[QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT-2]
	_ = x[QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT-1024]
	_ = x[QUERY_PIPELINE_STATISTIC_TASK_SHADER_INVOCATIONS_BIT_EXT-2048]
	_ = x[QUERY_PIPELINE_STATISTIC_MESH_SHADER_INVOCATIONS_BIT_EXT-4096]
	_ = x[QUERY_PIPELINE_STATISTIC_CLUSTER_CULLING_SHADER_INVOCATIONS_BIT_HUAWEI-8192]
	_ = x[QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT-4]
	_ = x[QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT-8]
	_ = x[QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT-16]
	_ = x[QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT-32]
	_ = x[QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT-64]
	_ = x[QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT-128]
	_ = x[QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT-256]
	_ = x[QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT-512]
}

const _QueryPipelineStatisticFlagBits_name = "QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BITQUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BITQUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BITQUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BITQUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BITQUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BITQUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BITQUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BITQUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BITQUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BITQUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BITQUERY_PIPELINE_STATISTIC_TASK_SHADER_INVOCATIONS_BIT_EXTQUERY_PIPELINE_STATISTIC_MESH_SHADER_INVOCATIONS_BIT_EXTQUERY_PIPELINE_STATISTIC_CLUSTER_CULLING_SHADER_INVOCATIONS_BIT_HUAWEI"

var _QueryPipelineStatisticFlagBits_map = map[QueryPipelineStatisticFlagBits]string{
	1:    _QueryPipelineStatisticFlagBits_name[0:52],
	2:    _QueryPipelineStatisticFlagBits_name[52:106],
	4:    _QueryPipelineStatisticFlagBits_name[106:160],
	8:    _QueryPipelineStatisticFlagBits_name[160:216],
	16:   _QueryPipelineStatisticFlagBits_name[216:271],
	32:   _QueryPipelineStatisticFlagBits_name[271:320],
	64:   _QueryPipelineStatisticFlagBits_name[320:368],
	128:  _QueryPipelineStatisticFlagBits_name[368:424],
	256:  _QueryPipelineStatisticFlagBits_name[424:488],
	512:  _QueryPipelineStatisticFlagBits_name[488:559],
	1024: _QueryPipelineStatisticFlagBits_name[559:614],
	2048: _QueryPipelineStatisticFlagBits_name[614:670],
	4096: _QueryPipelineStatisticFlagBits_name[670:726],
	8192: _QueryPipelineStatisticFlagBits_name[726:796],
}

func (i QueryPipelineStatisticFlagBits) String() string {
	if str, ok := _QueryPipelineStatisticFlagBits_map[i]; ok {
		return str
	}
	return "QueryPipelineStatisticFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QUERY_POOL_CREATE_RESET_BIT_KHR-1]
}

const _QueryPoolCreateFlagBits_name = "QUERY_POOL_CREATE_RESET_BIT_KHR"

var _QueryPoolCreateFlagBits_index = [...]uint8{0, 31}

func (i QueryPoolCreateFlagBits) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_QueryPoolCreateFlagBits_index)-1 {
		return "QueryPoolCreateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QueryPoolCreateFlagBits_name[_QueryPoolCreateFlagBits_index[idx]:_QueryPoolCreateFlagBits_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QUERY_POOL_SAMPLING_MODE_MANUAL_INTEL-0]
}

const _QueryPoolSamplingModeINTEL_name = "QUERY_POOL_SAMPLING_MODE_MANUAL_INTEL"

var _QueryPoolSamplingModeINTEL_index = [...]uint8{0, 37}

func (i QueryPoolSamplingModeINTEL) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_QueryPoolSamplingModeINTEL_index)-1 {
		return "QueryPoolSamplingModeINTEL(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QueryPoolSamplingModeINTEL_name[_QueryPoolSamplingModeINTEL_index[idx]:_QueryPoolSamplingModeINTEL_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QUERY_RESULT_64_BIT-1]
	_ = x[QUERY_RESULT_WAIT_BIT-2]
	_ = x[QUERY_RESULT_WITH_AVAILABILITY_BIT-4]
	_ = x[QUERY_RESULT_PARTIAL_BIT-8]
	_ = x[QUERY_RESULT_WITH_STATUS_BIT_KHR-16]
}

const (
	_QueryResultFlagBits_name_0 = "QUERY_RESULT_64_BITQUERY_RESULT_WAIT_BIT"
	_QueryResultFlagBits_name_1 = "QUERY_RESULT_WITH_AVAILABILITY_BIT"
	_QueryResultFlagBits_name_2 = "QUERY_RESULT_PARTIAL_BIT"
	_QueryResultFlagBits_name_3 = "QUERY_RESULT_WITH_STATUS_BIT_KHR"
)

var (
	_QueryResultFlagBits_index_0 = [...]uint8{0, 19, 40}
)

func (i QueryResultFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _QueryResultFlagBits_name_0[_QueryResultFlagBits_index_0[i]:_QueryResultFlagBits_index_0[i+1]]
	case i == 4:
		return _QueryResultFlagBits_name_1
	case i == 8:
		return _QueryResultFlagBits_name_2
	case i == 16:
		return _QueryResultFlagBits_name_3
	default:
		return "QueryResultFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QUERY_RESULT_STATUS_INSUFFICIENT_BITSTREAM_BUFFER_RANGE_KHR - -1000299000]
	_ = x[QUERY_RESULT_STATUS_ERROR_KHR - -1]
	_ = x[QUERY_RESULT_STATUS_NOT_READY_KHR-0]
	_ = x[QUERY_RESULT_STATUS_COMPLETE_KHR-1]
}

const (
	_QueryResultStatusKHR_name_0 = "QUERY_RESULT_STATUS_INSUFFICIENT_BITSTREAM_BUFFER_RANGE_KHR"
	_QueryResultStatusKHR_name_1 = "QUERY_RESULT_STATUS_ERROR_KHRQUERY_RESULT_STATUS_NOT_READY_KHRQUERY_RESULT_STATUS_COMPLETE_KHR"
)

var (
	_QueryResultStatusKHR_index_1 = [...]uint8{0, 29, 62, 94}
)

func (i QueryResultStatusKHR) String() string {
	switch {
	case i == -1000299000:
		return _QueryResultStatusKHR_name_0
	case -1 <= i && i <= 1:
		i -= -1
		return _QueryResultStatusKHR_name_1[_QueryResultStatusKHR_index_1[i]:_QueryResultStatusKHR_index_1[i+1]]
	default:
		return "QueryResultStatusKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QUERY_TYPE_OCCLUSION-0]
	_ = x[QUERY_TYPE_PIPELINE_STATISTICS-1]
	_ = x[QUERY_TYPE_TIMESTAMP-2]
	_ = x[QUERY_TYPE_RESULT_STATUS_ONLY_KHR-1000023000]
	_ = x[QUERY_TYPE_TRANSFORM_FEEDBACK_STREAM_EXT-1000028004]
	_ = x[QUERY_TYPE_PERFORMANCE_QUERY_KHR-1000116000]
	_ = x[QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR-1000150000]
	_ = x[QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR-1000150001]
	_ = x[QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_NV-1000165000]
	_ = x[QUERY_TYPE_PERFORMANCE_QUERY_INTEL-1000210000]
	_ = x[QUERY_TYPE_VIDEO_ENCODE_FEEDBACK_KHR-1000299000]
	_ = x[QUERY_TYPE_MESH_PRIMITIVES_GENERATED_EXT-1000328000]
	_ = x[QUERY_TYPE_PRIMITIVES_GENERATED_EXT-1000382000]
	_ = x[QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_BOTTOM_LEVEL_POINTERS_KHR-1000386000]
	_ = x[QUERY_TYPE_ACCELERATION_STRUCTURE_SIZE_KHR-1000386001]
	_ = x[QUERY_TYPE_MICROMAP_SERIALIZATION_SIZE_EXT-1000396000]
	_ = x[QUERY_TYPE_MICROMAP_COMPACTED_SIZE_EXT-1000396001]
}

const _QueryType_name = "QUERY_TYPE_OCCLUSIONQUERY_TYPE_PIPELINE_STATISTICSQUERY_TYPE_TIMESTAMPQUERY_TYPE_RESULT_STATUS_ONLY_KHRQUERY_TYPE_TRANSFORM_FEEDBACK_STREAM_EXTQUERY_TYPE_PERFORMANCE_QUERY_KHRQUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHRQUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHRQUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_NVQUERY_TYPE_PERFORMANCE_QUERY_INTELQUERY_TYPE_VIDEO_ENCODE_FEEDBACK_KHRQUERY_TYPE_MESH_PRIMITIVES_GENERATED_EXTQUERY_TYPE_PRIMITIVES_GENERATED_EXTQUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_BOTTOM_LEVEL_POINTERS_KHRQUERY_TYPE_ACCELERATION_STRUCTURE_SIZE_KHRQUERY_TYPE_MICROMAP_SERIALIZATION_SIZE_EXTQUERY_TYPE_MICROMAP_COMPACTED_SIZE_EXT"

var _QueryType_map = map[QueryType]string{
	0:          _QueryType_name[0:20],
	1:          _QueryType_name[20:50],
	2:          _QueryType_name[50:70],
	1000023000: _QueryType_name[70:103],
	1000028004: _QueryType_name[103:143],
	1000116000: _QueryType_name[143:175],
	1000150000: _QueryType_name[175:227],
	1000150001: _QueryType_name[227:283],
	1000165000: _QueryType_name[283:334],
	1000210000: _QueryType_name[334:368],
	1000299000: _QueryType_name[368:404],
	1000328000: _QueryType_name[404:444],
	1000382000: _QueryType_name[444:479],
	1000386000: _QueryType_name[479:552],
	1000386001: _QueryType_name[552:594],
	1000396000: _QueryType_name[594:636],
	1000396001: _QueryType_name[636:674],
}

func (i QueryType) String() string {
	if str, ok := _QueryType_map[i]; ok {
		return str
	}
	return "QueryType(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QUEUE_GRAPHICS_BIT-1]
	_ = x[QUEUE_COMPUTE_BIT-2]
	_ = x[QUEUE_DATA_GRAPH_BIT_ARM-1024]
	_ = x[QUEUE_TRANSFER_BIT-4]
	_ = x[QUEUE_SPARSE_BINDING_BIT-8]
	_ = x[QUEUE_PROTECTED_BIT-16]
	_ = x[QUEUE_VIDEO_DECODE_BIT_KHR-32]
	_ = x[QUEUE_VIDEO_ENCODE_BIT_KHR-64]
	_ = x[QUEUE_OPTICAL_FLOW_BIT_NV-256]
}

const (
	_QueueFlagBits_name_0 = "QUEUE_GRAPHICS_BITQUEUE_COMPUTE_BIT"
	_QueueFlagBits_name_1 = "QUEUE_TRANSFER_BIT"
	_QueueFlagBits_name_2 = "QUEUE_SPARSE_BINDING_BIT"
	_QueueFlagBits_name_3 = "QUEUE_PROTECTED_BIT"
	_QueueFlagBits_name_4 = "QUEUE_VIDEO_DECODE_BIT_KHR"
	_QueueFlagBits_name_5 = "QUEUE_VIDEO_ENCODE_BIT_KHR"
	_QueueFlagBits_name_6 = "QUEUE_OPTICAL_FLOW_BIT_NV"
	_QueueFlagBits_name_7 = "QUEUE_DATA_GRAPH_BIT_ARM"
)

var (
	_QueueFlagBits_index_0 = [...]uint8{0, 18, 35}
)

func (i QueueFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _QueueFlagBits_name_0[_QueueFlagBits_index_0[i]:_QueueFlagBits_index_0[i+1]]
	case i == 4:
		return _QueueFlagBits_name_1
	case i == 8:
		return _QueueFlagBits_name_2
	case i == 16:
		return _QueueFlagBits_name_3
	case i == 32:
		return _QueueFlagBits_name_4
	case i == 64:
		return _QueueFlagBits_name_5
	case i == 256:
		return _QueueFlagBits_name_6
	case i == 1024:
		return _QueueFlagBits_name_7
	default:
		return "QueueFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QUEUE_GLOBAL_PRIORITY_LOW-128]
	_ = x[QUEUE_GLOBAL_PRIORITY_MEDIUM-256]
	_ = x[QUEUE_GLOBAL_PRIORITY_HIGH-512]
	_ = x[QUEUE_GLOBAL_PRIORITY_REALTIME-1024]
	_ = x[QUEUE_GLOBAL_PRIORITY_HIGH_KHR-512]
	_ = x[QUEUE_GLOBAL_PRIORITY_HIGH_EXT-512]
	_ = x[QUEUE_GLOBAL_PRIORITY_LOW_KHR-128]
	_ = x[QUEUE_GLOBAL_PRIORITY_LOW_EXT-128]
	_ = x[QUEUE_GLOBAL_PRIORITY_MEDIUM_EXT-256]
	_ = x[QUEUE_GLOBAL_PRIORITY_MEDIUM_KHR-256]
	_ = x[QUEUE_GLOBAL_PRIORITY_REALTIME_EXT-1024]
	_ = x[QUEUE_GLOBAL_PRIORITY_REALTIME_KHR-1024]
}

const (
	_QueueGlobalPriority_name_0 = "QUEUE_GLOBAL_PRIORITY_LOW"
	_QueueGlobalPriority_name_1 = "QUEUE_GLOBAL_PRIORITY_MEDIUM"
	_QueueGlobalPriority_name_2 = "QUEUE_GLOBAL_PRIORITY_HIGH"
	_QueueGlobalPriority_name_3 = "QUEUE_GLOBAL_PRIORITY_REALTIME"
)

func (i QueueGlobalPriority) String() string {
	switch {
	case i == 128:
		return _QueueGlobalPriority_name_0
	case i == 256:
		return _QueueGlobalPriority_name_1
	case i == 512:
		return _QueueGlobalPriority_name_2
	case i == 1024:
		return _QueueGlobalPriority_name_3
	default:
		return "QueueGlobalPriority(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RASTERIZATION_ORDER_STRICT_AMD-0]
	_ = x[RASTERIZATION_ORDER_RELAXED_AMD-1]
}

const _RasterizationOrderAMD_name = "RASTERIZATION_ORDER_STRICT_AMDRASTERIZATION_ORDER_RELAXED_AMD"

var _RasterizationOrderAMD_index = [...]uint8{0, 30, 61}

func (i RasterizationOrderAMD) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RasterizationOrderAMD_index)-1 {
		return "RasterizationOrderAMD(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RasterizationOrderAMD_name[_RasterizationOrderAMD_index[idx]:_RasterizationOrderAMD_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RAY_TRACING_INVOCATION_REORDER_MODE_NONE_NV-0]
	_ = x[RAY_TRACING_INVOCATION_REORDER_MODE_REORDER_NV-1]
}

const _RayTracingInvocationReorderModeNV_name = "RAY_TRACING_INVOCATION_REORDER_MODE_NONE_NVRAY_TRACING_INVOCATION_REORDER_MODE_REORDER_NV"

var _RayTracingInvocationReorderModeNV_index = [...]uint8{0, 43, 89}

func (i RayTracingInvocationReorderModeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RayTracingInvocationReorderModeNV_index)-1 {
		return "RayTracingInvocationReorderModeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RayTracingInvocationReorderModeNV_name[_RayTracingInvocationReorderModeNV_index[idx]:_RayTracingInvocationReorderModeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RAY_TRACING_LSS_INDEXING_MODE_LIST_NV-0]
	_ = x[RAY_TRACING_LSS_INDEXING_MODE_SUCCESSIVE_NV-1]
}

const _RayTracingLssIndexingModeNV_name = "RAY_TRACING_LSS_INDEXING_MODE_LIST_NVRAY_TRACING_LSS_INDEXING_MODE_SUCCESSIVE_NV"

var _RayTracingLssIndexingModeNV_index = [...]uint8{0, 37, 80}

func (i RayTracingLssIndexingModeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RayTracingLssIndexingModeNV_index)-1 {
		return "RayTracingLssIndexingModeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RayTracingLssIndexingModeNV_name[_RayTracingLssIndexingModeNV_index[idx]:_RayTracingLssIndexingModeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RAY_TRACING_LSS_PRIMITIVE_END_CAPS_MODE_NONE_NV-0]
	_ = x[RAY_TRACING_LSS_PRIMITIVE_END_CAPS_MODE_CHAINED_NV-1]
}

const _RayTracingLssPrimitiveEndCapsModeNV_name = "RAY_TRACING_LSS_PRIMITIVE_END_CAPS_MODE_NONE_NVRAY_TRACING_LSS_PRIMITIVE_END_CAPS_MODE_CHAINED_NV"

var _RayTracingLssPrimitiveEndCapsModeNV_index = [...]uint8{0, 47, 97}

func (i RayTracingLssPrimitiveEndCapsModeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RayTracingLssPrimitiveEndCapsModeNV_index)-1 {
		return "RayTracingLssPrimitiveEndCapsModeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RayTracingLssPrimitiveEndCapsModeNV_name[_RayTracingLssPrimitiveEndCapsModeNV_index[idx]:_RayTracingLssPrimitiveEndCapsModeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_KHR-0]
	_ = x[RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_KHR-1]
	_ = x[RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_KHR-2]
	_ = x[RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV-0]
	_ = x[RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_NV-2]
	_ = x[RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_NV-1]
}

const _RayTracingShaderGroupTypeKHR_name = "RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_KHRRAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_KHRRAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_KHR"

var _RayTracingShaderGroupTypeKHR_index = [...]uint8{0, 41, 94, 148}

func (i RayTracingShaderGroupTypeKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RayTracingShaderGroupTypeKHR_index)-1 {
		return "RayTracingShaderGroupTypeKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RayTracingShaderGroupTypeKHR_name[_RayTracingShaderGroupTypeKHR_index[idx]:_RayTracingShaderGroupTypeKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RENDER_PASS_CREATE_TRANSFORM_BIT_QCOM-2]
	_ = x[RENDER_PASS_CREATE_PER_LAYER_FRAGMENT_DENSITY_BIT_VALVE-4]
}

const (
	_RenderPassCreateFlagBits_name_0 = "RENDER_PASS_CREATE_TRANSFORM_BIT_QCOM"
	_RenderPassCreateFlagBits_name_1 = "RENDER_PASS_CREATE_PER_LAYER_FRAGMENT_DENSITY_BIT_VALVE"
)

func (i RenderPassCreateFlagBits) String() string {
	switch {
	case i == 2:
		return _RenderPassCreateFlagBits_name_0
	case i == 4:
		return _RenderPassCreateFlagBits_name_1
	default:
		return "RenderPassCreateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RENDERING_CONTENTS_SECONDARY_COMMAND_BUFFERS_BIT-1]
	_ = x[RENDERING_SUSPENDING_BIT-2]
	_ = x[RENDERING_RESUMING_BIT-4]
	_ = x[RENDERING_ENABLE_LEGACY_DITHERING_BIT_EXT-8]
	_ = x[RENDERING_CONTENTS_INLINE_BIT_KHR-16]
	_ = x[RENDERING_PER_LAYER_FRAGMENT_DENSITY_BIT_VALVE-32]
	_ = x[RENDERING_CONTENTS_INLINE_BIT_EXT-16]
	_ = x[RENDERING_CONTENTS_SECONDARY_COMMAND_BUFFERS_BIT_KHR-1]
	_ = x[RENDERING_RESUMING_BIT_KHR-4]
	_ = x[RENDERING_SUSPENDING_BIT_KHR-2]
}

const (
	_RenderingFlagBits_name_0 = "RENDERING_CONTENTS_SECONDARY_COMMAND_BUFFERS_BITRENDERING_SUSPENDING_BIT"
	_RenderingFlagBits_name_1 = "RENDERING_RESUMING_BIT"
	_RenderingFlagBits_name_2 = "RENDERING_ENABLE_LEGACY_DITHERING_BIT_EXT"
	_RenderingFlagBits_name_3 = "RENDERING_CONTENTS_INLINE_BIT_KHR"
	_RenderingFlagBits_name_4 = "RENDERING_PER_LAYER_FRAGMENT_DENSITY_BIT_VALVE"
)

var (
	_RenderingFlagBits_index_0 = [...]uint8{0, 48, 72}
)

func (i RenderingFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _RenderingFlagBits_name_0[_RenderingFlagBits_index_0[i]:_RenderingFlagBits_index_0[i+1]]
	case i == 4:
		return _RenderingFlagBits_name_1
	case i == 8:
		return _RenderingFlagBits_name_2
	case i == 16:
		return _RenderingFlagBits_name_3
	case i == 32:
		return _RenderingFlagBits_name_4
	default:
		return "RenderingFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RESOLVE_MODE_NONE-0]
	_ = x[RESOLVE_MODE_SAMPLE_ZERO_BIT-1]
	_ = x[RESOLVE_MODE_AVERAGE_BIT-2]
	_ = x[RESOLVE_MODE_MIN_BIT-4]
	_ = x[RESOLVE_MODE_MAX_BIT-8]
	_ = x[RESOLVE_MODE_AVERAGE_BIT_KHR-2]
	_ = x[RESOLVE_MODE_MAX_BIT_KHR-8]
	_ = x[RESOLVE_MODE_MIN_BIT_KHR-4]
	_ = x[RESOLVE_MODE_NONE_KHR-0]
	_ = x[RESOLVE_MODE_SAMPLE_ZERO_BIT_KHR-1]
}

const (
	_ResolveModeFlagBits_name_0 = "RESOLVE_MODE_NONERESOLVE_MODE_SAMPLE_ZERO_BITRESOLVE_MODE_AVERAGE_BIT"
	_ResolveModeFlagBits_name_1 = "RESOLVE_MODE_MIN_BIT"
	_ResolveModeFlagBits_name_2 = "RESOLVE_MODE_MAX_BIT"
)

var (
	_ResolveModeFlagBits_index_0 = [...]uint8{0, 17, 45, 69}
)

func (i ResolveModeFlagBits) String() string {
	switch {
	case i <= 2:
		return _ResolveModeFlagBits_name_0[_ResolveModeFlagBits_index_0[i]:_ResolveModeFlagBits_index_0[i+1]]
	case i == 4:
		return _ResolveModeFlagBits_name_1
	case i == 8:
		return _ResolveModeFlagBits_name_2
	default:
		return "ResolveModeFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERROR_NOT_ENOUGH_SPACE_KHR - -1000483000]
	_ = x[ERROR_COMPRESSION_EXHAUSTED_EXT - -1000338000]
	_ = x[ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR - -1000299000]
	_ = x[ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS - -1000257000]
	_ = x[ERROR_NOT_PERMITTED - -1000174001]
	_ = x[ERROR_FRAGMENTATION - -1000161000]
	_ = x[ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT - -1000158000]
	_ = x[ERROR_INVALID_EXTERNAL_HANDLE - -1000072003]
	_ = x[ERROR_OUT_OF_POOL_MEMORY - -1000069000]
	_ = x[ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR - -1000023005]
	_ = x[ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR - -1000023004]
	_ = x[ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR - -1000023003]
	_ = x[ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR - -1000023002]
	_ = x[ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR - -1000023001]
	_ = x[ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR - -1000023000]
	_ = x[ERROR_INVALID_SHADER_NV - -1000012000]
	_ = x[ERROR_VALIDATION_FAILED - -1000011001]
	_ = x[ERROR_INCOMPATIBLE_DISPLAY_KHR - -1000003001]
	_ = x[ERROR_OUT_OF_DATE_KHR - -1000001004]
	_ = x[ERROR_NATIVE_WINDOW_IN_USE_KHR - -1000000001]
	_ = x[ERROR_SURFACE_LOST_KHR - -1000000000]
	_ = x[ERROR_UNKNOWN - -13]
	_ = x[ERROR_FRAGMENTED_POOL - -12]
	_ = x[ERROR_FORMAT_NOT_SUPPORTED - -11]
	_ = x[ERROR_TOO_MANY_OBJECTS - -10]
	_ = x[ERROR_INCOMPATIBLE_DRIVER - -9]
	_ = x[ERROR_FEATURE_NOT_PRESENT - -8]
	_ = x[ERROR_EXTENSION_NOT_PRESENT - -7]
	_ = x[ERROR_LAYER_NOT_PRESENT - -6]
	_ = x[ERROR_MEMORY_MAP_FAILED - -5]
	_ = x[ERROR_DEVICE_LOST - -4]
	_ = x[ERROR_INITIALIZATION_FAILED - -3]
	_ = x[ERROR_OUT_OF_DEVICE_MEMORY - -2]
	_ = x[ERROR_OUT_OF_HOST_MEMORY - -1]
	_ = x[NOT_READY-1]
	_ = x[TIMEOUT-2]
	_ = x[EVENT_SET-3]
	_ = x[EVENT_RESET-4]
	_ = x[INCOMPLETE-5]
	_ = x[SUBOPTIMAL_KHR-1000001003]
	_ = x[THREAD_IDLE_KHR-1000268000]
	_ = x[THREAD_DONE_KHR-1000268001]
	_ = x[OPERATION_DEFERRED_KHR-1000268002]
	_ = x[OPERATION_NOT_DEFERRED_KHR-1000268003]
	_ = x[PIPELINE_COMPILE_REQUIRED-1000297000]
	_ = x[INCOMPATIBLE_SHADER_BINARY_EXT-1000482000]
	_ = x[PIPELINE_BINARY_MISSING_KHR-1000483000]
	_ = x[ERROR_FRAGMENTATION_EXT - -1000161000]
	_ = x[ERROR_INVALID_EXTERNAL_HANDLE_KHR - -1000072003]
	_ = x[ERROR_INVALID_DEVICE_ADDRESS_EXT - -1000257000]
	_ = x[ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS_KHR - -1000257000]
	_ = x[ERROR_NOT_PERMITTED_EXT - -1000174001]
	_ = x[ERROR_NOT_PERMITTED_KHR - -1000174001]
	_ = x[ERROR_OUT_OF_POOL_MEMORY_KHR - -1000069000]
	_ = x[ERROR_VALIDATION_FAILED_EXT - -1000011001]
	_ = x[ERROR_INCOMPATIBLE_SHADER_BINARY_EXT-1000482000]
	_ = x[ERROR_PIPELINE_COMPILE_REQUIRED_EXT-1000297000]
	_ = x[PIPELINE_COMPILE_REQUIRED_EXT-1000297000]
	_ = x[ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT - -1000255000]
}

const _Result_name = "ERROR_NOT_ENOUGH_SPACE_KHRERROR_COMPRESSION_EXHAUSTED_EXTERROR_INVALID_VIDEO_STD_PARAMETERS_KHRERROR_INVALID_OPAQUE_CAPTURE_ADDRESSERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXTERROR_NOT_PERMITTEDERROR_FRAGMENTATIONERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXTERROR_INVALID_EXTERNAL_HANDLEERROR_OUT_OF_POOL_MEMORYERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHRERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHRERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHRERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHRERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHRERROR_IMAGE_USAGE_NOT_SUPPORTED_KHRERROR_INVALID_SHADER_NVERROR_VALIDATION_FAILEDERROR_INCOMPATIBLE_DISPLAY_KHRERROR_OUT_OF_DATE_KHRERROR_NATIVE_WINDOW_IN_USE_KHRERROR_SURFACE_LOST_KHRERROR_UNKNOWNERROR_FRAGMENTED_POOLERROR_FORMAT_NOT_SUPPORTEDERROR_TOO_MANY_OBJECTSERROR_INCOMPATIBLE_DRIVERERROR_FEATURE_NOT_PRESENTERROR_EXTENSION_NOT_PRESENTERROR_LAYER_NOT_PRESENTERROR_MEMORY_MAP_FAILEDERROR_DEVICE_LOSTERROR_INITIALIZATION_FAILEDERROR_OUT_OF_DEVICE_MEMORYERROR_OUT_OF_HOST_MEMORYNOT_READYTIMEOUTEVENT_SETEVENT_RESETINCOMPLETESUBOPTIMAL_KHRTHREAD_IDLE_KHRTHREAD_DONE_KHROPERATION_DEFERRED_KHROPERATION_NOT_DEFERRED_KHRPIPELINE_COMPILE_REQUIREDINCOMPATIBLE_SHADER_BINARY_EXTPIPELINE_BINARY_MISSING_KHR"

var _Result_map = map[Result]string{
	-1000483000: _Result_name[0:26],
	-1000338000: _Result_name[26:57],
	-1000299000: _Result_name[57:95],
	-1000257000: _Result_name[95:131],
	-1000255000: _Result_name[131:172],
	-1000174001: _Result_name[172:191],
	-1000161000: _Result_name[191:210],
	-1000158000: _Result_name[210:260],
	-1000072003: _Result_name[260:289],
	-1000069000: _Result_name[289:313],
	-1000023005: _Result_name[313:354],
	-1000023004: _Result_name[354:397],
	-1000023003: _Result_name[397:441],
	-1000023002: _Result_name[441:488],
	-1000023001: _Result_name[488:532],
	-1000023000: _Result_name[532:567],
	-1000012000: _Result_name[567:590],
	-1000011001: _Result_name[590:613],
	-1000003001: _Result_name[613:643],
	-1000001004: _Result_name[643:664],
	-1000000001: _Result_name[664:694],
	-1000000000: _Result_name[694:716],
	-13:         _Result_name[716:729],
	-12:         _Result_name[729:750],
	-11:         _Result_name[750:776],
	-10:         _Result_name[776:798],
	-9:          _Result_name[798:823],
	-8:          _Result_name[823:848],
	-7:          _Result_name[848:875],
	-6:          _Result_name[875:898],
	-5:          _Result_name[898:921],
	-4:          _Result_name[921:938],
	-3:          _Result_name[938:965],
	-2:          _Result_name[965:991],
	-1:          _Result_name[991:1015],
	1:           _Result_name[1015:1024],
	2:           _Result_name[1024:1031],
	3:           _Result_name[1031:1040],
	4:           _Result_name[1040:1051],
	5:           _Result_name[1051:1061],
	1000001003:  _Result_name[1061:1075],
	1000268000:  _Result_name[1075:1090],
	1000268001:  _Result_name[1090:1105],
	1000268002:  _Result_name[1105:1127],
	1000268003:  _Result_name[1127:1153],
	1000297000:  _Result_name[1153:1178],
	1000482000:  _Result_name[1178:1208],
	1000483000:  _Result_name[1208:1235],
}

func (i Result) String() string {
	if str, ok := _Result_map[i]; ok {
		return str
	}
	return "Result(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SAMPLE_COUNT_1_BIT-1]
	_ = x[SAMPLE_COUNT_2_BIT-2]
	_ = x[SAMPLE_COUNT_4_BIT-4]
	_ = x[SAMPLE_COUNT_8_BIT-8]
	_ = x[SAMPLE_COUNT_16_BIT-16]
	_ = x[SAMPLE_COUNT_32_BIT-32]
	_ = x[SAMPLE_COUNT_64_BIT-64]
}

const (
	_SampleCountFlagBits_name_0 = "SAMPLE_COUNT_1_BITSAMPLE_COUNT_2_BIT"
	_SampleCountFlagBits_name_1 = "SAMPLE_COUNT_4_BIT"
	_SampleCountFlagBits_name_2 = "SAMPLE_COUNT_8_BIT"
	_SampleCountFlagBits_name_3 = "SAMPLE_COUNT_16_BIT"
	_SampleCountFlagBits_name_4 = "SAMPLE_COUNT_32_BIT"
	_SampleCountFlagBits_name_5 = "SAMPLE_COUNT_64_BIT"
)

var (
	_SampleCountFlagBits_index_0 = [...]uint8{0, 18, 36}
)

func (i SampleCountFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _SampleCountFlagBits_name_0[_SampleCountFlagBits_index_0[i]:_SampleCountFlagBits_index_0[i+1]]
	case i == 4:
		return _SampleCountFlagBits_name_1
	case i == 8:
		return _SampleCountFlagBits_name_2
	case i == 16:
		return _SampleCountFlagBits_name_3
	case i == 32:
		return _SampleCountFlagBits_name_4
	case i == 64:
		return _SampleCountFlagBits_name_5
	default:
		return "SampleCountFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
