// Code generated by "stringer -output=enum_string_1.go -type=ClusterAccelerationStructureIndexFormatFlagBitsNV,ClusterAccelerationStructureOpModeNV,ClusterAccelerationStructureOpTypeNV,ClusterAccelerationStructureTypeNV,CoarseSampleOrderTypeNV,ColorComponentFlagBits,ColorSpaceKHR,CommandBufferLevel,CommandBufferResetFlagBits,CommandBufferUsageFlagBits,CommandPoolCreateFlagBits,CommandPoolResetFlagBits,CompareOp,ComponentSwizzle,ComponentTypeKHR,CompositeAlphaFlagBitsKHR,ConditionalRenderingFlagBitsEXT,ConservativeRasterizationModeEXT,CooperativeVectorMatrixLayoutNV,CopyAccelerationStructureModeKHR,CopyMicromapModeEXT,CoverageModulationModeNV,CoverageReductionModeNV,CubicFilterWeightsQCOM,CullModeFlagBits,DataGraphPipelinePropertyARM,DataGraphPipelineSessionBindPointARM,DataGraphPipelineSessionBindPointTypeARM,DataGraphPipelineSessionCreateFlagBitsARM,DebugReportFlagBitsEXT,DebugReportObjectTypeEXT"; DO NOT EDIT.

package vk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_INDEX_FORMAT_8BIT_NV-1]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_INDEX_FORMAT_16BIT_NV-2]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_INDEX_FORMAT_32BIT_NV-4]
}

const (
	_ClusterAccelerationStructureIndexFormatFlagBitsNV_name_0 = "CLUSTER_ACCELERATION_STRUCTURE_INDEX_FORMAT_8BIT_NVCLUSTER_ACCELERATION_STRUCTURE_INDEX_FORMAT_16BIT_NV"
	_ClusterAccelerationStructureIndexFormatFlagBitsNV_name_1 = "CLUSTER_ACCELERATION_STRUCTURE_INDEX_FORMAT_32BIT_NV"
)

var (
	_ClusterAccelerationStructureIndexFormatFlagBitsNV_index_0 = [...]uint8{0, 51, 103}
)

func (i ClusterAccelerationStructureIndexFormatFlagBitsNV) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ClusterAccelerationStructureIndexFormatFlagBitsNV_name_0[_ClusterAccelerationStructureIndexFormatFlagBitsNV_index_0[i]:_ClusterAccelerationStructureIndexFormatFlagBitsNV_index_0[i+1]]
	case i == 4:
		return _ClusterAccelerationStructureIndexFormatFlagBitsNV_name_1
	default:
		return "ClusterAccelerationStructureIndexFormatFlagBitsNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_OP_MODE_IMPLICIT_DESTINATIONS_NV-0]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_OP_MODE_EXPLICIT_DESTINATIONS_NV-1]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_OP_MODE_COMPUTE_SIZES_NV-2]
}

const _ClusterAccelerationStructureOpModeNV_name = "CLUSTER_ACCELERATION_STRUCTURE_OP_MODE_IMPLICIT_DESTINATIONS_NVCLUSTER_ACCELERATION_STRUCTURE_OP_MODE_EXPLICIT_DESTINATIONS_NVCLUSTER_ACCELERATION_STRUCTURE_OP_MODE_COMPUTE_SIZES_NV"

var _ClusterAccelerationStructureOpModeNV_index = [...]uint8{0, 63, 126, 181}

func (i ClusterAccelerationStructureOpModeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ClusterAccelerationStructureOpModeNV_index)-1 {
		return "ClusterAccelerationStructureOpModeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClusterAccelerationStructureOpModeNV_name[_ClusterAccelerationStructureOpModeNV_index[idx]:_ClusterAccelerationStructureOpModeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_MOVE_OBJECTS_NV-0]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_BUILD_CLUSTERS_BOTTOM_LEVEL_NV-1]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_BUILD_TRIANGLE_CLUSTER_NV-2]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_BUILD_TRIANGLE_CLUSTER_TEMPLATE_NV-3]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_INSTANTIATE_TRIANGLE_CLUSTER_NV-4]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_GET_CLUSTER_TEMPLATE_INDICES_NV-5]
}

const _ClusterAccelerationStructureOpTypeNV_name = "CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_MOVE_OBJECTS_NVCLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_BUILD_CLUSTERS_BOTTOM_LEVEL_NVCLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_BUILD_TRIANGLE_CLUSTER_NVCLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_BUILD_TRIANGLE_CLUSTER_TEMPLATE_NVCLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_INSTANTIATE_TRIANGLE_CLUSTER_NVCLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_GET_CLUSTER_TEMPLATE_INDICES_NV"

var _ClusterAccelerationStructureOpTypeNV_index = [...]uint16{0, 54, 123, 187, 260, 330, 400}

func (i ClusterAccelerationStructureOpTypeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ClusterAccelerationStructureOpTypeNV_index)-1 {
		return "ClusterAccelerationStructureOpTypeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClusterAccelerationStructureOpTypeNV_name[_ClusterAccelerationStructureOpTypeNV_index[idx]:_ClusterAccelerationStructureOpTypeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_TYPE_CLUSTERS_BOTTOM_LEVEL_NV-0]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_TYPE_TRIANGLE_CLUSTER_NV-1]
	_ = x[CLUSTER_ACCELERATION_STRUCTURE_TYPE_TRIANGLE_CLUSTER_TEMPLATE_NV-2]
}

const _ClusterAccelerationStructureTypeNV_name = "CLUSTER_ACCELERATION_STRUCTURE_TYPE_CLUSTERS_BOTTOM_LEVEL_NVCLUSTER_ACCELERATION_STRUCTURE_TYPE_TRIANGLE_CLUSTER_NVCLUSTER_ACCELERATION_STRUCTURE_TYPE_TRIANGLE_CLUSTER_TEMPLATE_NV"

var _ClusterAccelerationStructureTypeNV_index = [...]uint8{0, 60, 115, 179}

func (i ClusterAccelerationStructureTypeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ClusterAccelerationStructureTypeNV_index)-1 {
		return "ClusterAccelerationStructureTypeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClusterAccelerationStructureTypeNV_name[_ClusterAccelerationStructureTypeNV_index[idx]:_ClusterAccelerationStructureTypeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COARSE_SAMPLE_ORDER_TYPE_DEFAULT_NV-0]
	_ = x[COARSE_SAMPLE_ORDER_TYPE_CUSTOM_NV-1]
	_ = x[COARSE_SAMPLE_ORDER_TYPE_PIXEL_MAJOR_NV-2]
	_ = x[COARSE_SAMPLE_ORDER_TYPE_SAMPLE_MAJOR_NV-3]
}

const _CoarseSampleOrderTypeNV_name = "COARSE_SAMPLE_ORDER_TYPE_DEFAULT_NVCOARSE_SAMPLE_ORDER_TYPE_CUSTOM_NVCOARSE_SAMPLE_ORDER_TYPE_PIXEL_MAJOR_NVCOARSE_SAMPLE_ORDER_TYPE_SAMPLE_MAJOR_NV"

var _CoarseSampleOrderTypeNV_index = [...]uint8{0, 35, 69, 108, 148}

func (i CoarseSampleOrderTypeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CoarseSampleOrderTypeNV_index)-1 {
		return "CoarseSampleOrderTypeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CoarseSampleOrderTypeNV_name[_CoarseSampleOrderTypeNV_index[idx]:_CoarseSampleOrderTypeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COLOR_COMPONENT_R_BIT-1]
	_ = x[COLOR_COMPONENT_G_BIT-2]
	_ = x[COLOR_COMPONENT_B_BIT-4]
	_ = x[COLOR_COMPONENT_A_BIT-8]
}

const (
	_ColorComponentFlagBits_name_0 = "COLOR_COMPONENT_R_BITCOLOR_COMPONENT_G_BIT"
	_ColorComponentFlagBits_name_1 = "COLOR_COMPONENT_B_BIT"
	_ColorComponentFlagBits_name_2 = "COLOR_COMPONENT_A_BIT"
)

var (
	_ColorComponentFlagBits_index_0 = [...]uint8{0, 21, 42}
)

func (i ColorComponentFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ColorComponentFlagBits_name_0[_ColorComponentFlagBits_index_0[i]:_ColorComponentFlagBits_index_0[i+1]]
	case i == 4:
		return _ColorComponentFlagBits_name_1
	case i == 8:
		return _ColorComponentFlagBits_name_2
	default:
		return "ColorComponentFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COLOR_SPACE_SRGB_NONLINEAR_KHR-0]
	_ = x[COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT-1000104001]
	_ = x[COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT-1000104002]
	_ = x[COLOR_SPACE_DISPLAY_P3_LINEAR_EXT-1000104003]
	_ = x[COLOR_SPACE_DCI_P3_NONLINEAR_EXT-1000104004]
	_ = x[COLOR_SPACE_BT709_LINEAR_EXT-1000104005]
	_ = x[COLOR_SPACE_BT709_NONLINEAR_EXT-1000104006]
	_ = x[COLOR_SPACE_BT2020_LINEAR_EXT-1000104007]
	_ = x[COLOR_SPACE_HDR10_ST2084_EXT-1000104008]
	_ = x[COLOR_SPACE_DOLBYVISION_EXT-1000104009]
	_ = x[COLOR_SPACE_HDR10_HLG_EXT-1000104010]
	_ = x[COLOR_SPACE_ADOBERGB_LINEAR_EXT-1000104011]
	_ = x[COLOR_SPACE_ADOBERGB_NONLINEAR_EXT-1000104012]
	_ = x[COLOR_SPACE_PASS_THROUGH_EXT-1000104013]
	_ = x[COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT-1000104014]
	_ = x[COLOR_SPACE_DISPLAY_NATIVE_AMD-1000213000]
	_ = x[COLOR_SPACE_DCI_P3_LINEAR_EXT-1000104003]
	_ = x[COLORSPACE_SRGB_NONLINEAR_KHR-0]
}

const (
	_ColorSpaceKHR_name_0 = "COLOR_SPACE_SRGB_NONLINEAR_KHR"
	_ColorSpaceKHR_name_1 = "COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXTCOLOR_SPACE_EXTENDED_SRGB_LINEAR_EXTCOLOR_SPACE_DISPLAY_P3_LINEAR_EXTCOLOR_SPACE_DCI_P3_NONLINEAR_EXTCOLOR_SPACE_BT709_LINEAR_EXTCOLOR_SPACE_BT709_NONLINEAR_EXTCOLOR_SPACE_BT2020_LINEAR_EXTCOLOR_SPACE_HDR10_ST2084_EXTCOLOR_SPACE_DOLBYVISION_EXTCOLOR_SPACE_HDR10_HLG_EXTCOLOR_SPACE_ADOBERGB_LINEAR_EXTCOLOR_SPACE_ADOBERGB_NONLINEAR_EXTCOLOR_SPACE_PASS_THROUGH_EXTCOLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT"
	_ColorSpaceKHR_name_2 = "COLOR_SPACE_DISPLAY_NATIVE_AMD"
)

var (
	_ColorSpaceKHR_index_1 = [...]uint16{0, 36, 72, 105, 137, 165, 196, 225, 253, 280, 305, 336, 370, 398, 437}
)

func (i ColorSpaceKHR) String() string {
	switch {
	case i == 0:
		return _ColorSpaceKHR_name_0
	case 1000104001 <= i && i <= 1000104014:
		i -= 1000104001
		return _ColorSpaceKHR_name_1[_ColorSpaceKHR_index_1[i]:_ColorSpaceKHR_index_1[i+1]]
	case i == 1000213000:
		return _ColorSpaceKHR_name_2
	default:
		return "ColorSpaceKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COMMAND_BUFFER_LEVEL_PRIMARY-0]
	_ = x[COMMAND_BUFFER_LEVEL_SECONDARY-1]
}

const _CommandBufferLevel_name = "COMMAND_BUFFER_LEVEL_PRIMARYCOMMAND_BUFFER_LEVEL_SECONDARY"

var _CommandBufferLevel_index = [...]uint8{0, 28, 58}

func (i CommandBufferLevel) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CommandBufferLevel_index)-1 {
		return "CommandBufferLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandBufferLevel_name[_CommandBufferLevel_index[idx]:_CommandBufferLevel_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT-1]
}

const _CommandBufferResetFlagBits_name = "COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT"

var _CommandBufferResetFlagBits_index = [...]uint8{0, 42}

func (i CommandBufferResetFlagBits) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_CommandBufferResetFlagBits_index)-1 {
		return "CommandBufferResetFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandBufferResetFlagBits_name[_CommandBufferResetFlagBits_index[idx]:_CommandBufferResetFlagBits_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT-1]
	_ = x[COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT-2]
	_ = x[COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT-4]
}

const (
	_CommandBufferUsageFlagBits_name_0 = "COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BITCOMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT"
	_CommandBufferUsageFlagBits_name_1 = "COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT"
)

var (
	_CommandBufferUsageFlagBits_index_0 = [...]uint8{0, 40, 85}
)

func (i CommandBufferUsageFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _CommandBufferUsageFlagBits_name_0[_CommandBufferUsageFlagBits_index_0[i]:_CommandBufferUsageFlagBits_index_0[i+1]]
	case i == 4:
		return _CommandBufferUsageFlagBits_name_1
	default:
		return "CommandBufferUsageFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COMMAND_POOL_CREATE_TRANSIENT_BIT-1]
	_ = x[COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT-2]
	_ = x[COMMAND_POOL_CREATE_PROTECTED_BIT-4]
}

const (
	_CommandPoolCreateFlagBits_name_0 = "COMMAND_POOL_CREATE_TRANSIENT_BITCOMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT"
	_CommandPoolCreateFlagBits_name_1 = "COMMAND_POOL_CREATE_PROTECTED_BIT"
)

var (
	_CommandPoolCreateFlagBits_index_0 = [...]uint8{0, 33, 77}
)

func (i CommandPoolCreateFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _CommandPoolCreateFlagBits_name_0[_CommandPoolCreateFlagBits_index_0[i]:_CommandPoolCreateFlagBits_index_0[i+1]]
	case i == 4:
		return _CommandPoolCreateFlagBits_name_1
	default:
		return "CommandPoolCreateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT-1]
}

const _CommandPoolResetFlagBits_name = "COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT"

var _CommandPoolResetFlagBits_index = [...]uint8{0, 40}

func (i CommandPoolResetFlagBits) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_CommandPoolResetFlagBits_index)-1 {
		return "CommandPoolResetFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandPoolResetFlagBits_name[_CommandPoolResetFlagBits_index[idx]:_CommandPoolResetFlagBits_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COMPARE_OP_NEVER-0]
	_ = x[COMPARE_OP_LESS-1]
	_ = x[COMPARE_OP_EQUAL-2]
	_ = x[COMPARE_OP_LESS_OR_EQUAL-3]
	_ = x[COMPARE_OP_GREATER-4]
	_ = x[COMPARE_OP_NOT_EQUAL-5]
	_ = x[COMPARE_OP_GREATER_OR_EQUAL-6]
	_ = x[COMPARE_OP_ALWAYS-7]
}

const _CompareOp_name = "COMPARE_OP_NEVERCOMPARE_OP_LESSCOMPARE_OP_EQUALCOMPARE_OP_LESS_OR_EQUALCOMPARE_OP_GREATERCOMPARE_OP_NOT_EQUALCOMPARE_OP_GREATER_OR_EQUALCOMPARE_OP_ALWAYS"

var _CompareOp_index = [...]uint8{0, 16, 31, 47, 71, 89, 109, 136, 153}

func (i CompareOp) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CompareOp_index)-1 {
		return "CompareOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompareOp_name[_CompareOp_index[idx]:_CompareOp_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COMPONENT_SWIZZLE_IDENTITY-0]
	_ = x[COMPONENT_SWIZZLE_ZERO-1]
	_ = x[COMPONENT_SWIZZLE_ONE-2]
	_ = x[COMPONENT_SWIZZLE_R-3]
	_ = x[COMPONENT_SWIZZLE_G-4]
	_ = x[COMPONENT_SWIZZLE_B-5]
	_ = x[COMPONENT_SWIZZLE_A-6]
}

const _ComponentSwizzle_name = "COMPONENT_SWIZZLE_IDENTITYCOMPONENT_SWIZZLE_ZEROCOMPONENT_SWIZZLE_ONECOMPONENT_SWIZZLE_RCOMPONENT_SWIZZLE_GCOMPONENT_SWIZZLE_BCOMPONENT_SWIZZLE_A"

var _ComponentSwizzle_index = [...]uint8{0, 26, 48, 69, 88, 107, 126, 145}

func (i ComponentSwizzle) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ComponentSwizzle_index)-1 {
		return "ComponentSwizzle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComponentSwizzle_name[_ComponentSwizzle_index[idx]:_ComponentSwizzle_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COMPONENT_TYPE_FLOAT16_KHR-0]
	_ = x[COMPONENT_TYPE_FLOAT32_KHR-1]
	_ = x[COMPONENT_TYPE_FLOAT64_KHR-2]
	_ = x[COMPONENT_TYPE_SINT8_KHR-3]
	_ = x[COMPONENT_TYPE_SINT16_KHR-4]
	_ = x[COMPONENT_TYPE_SINT32_KHR-5]
	_ = x[COMPONENT_TYPE_SINT64_KHR-6]
	_ = x[COMPONENT_TYPE_UINT8_KHR-7]
	_ = x[COMPONENT_TYPE_UINT16_KHR-8]
	_ = x[COMPONENT_TYPE_UINT32_KHR-9]
	_ = x[COMPONENT_TYPE_UINT64_KHR-10]
	_ = x[COMPONENT_TYPE_BFLOAT16_KHR-1000141000]
	_ = x[COMPONENT_TYPE_SINT8_PACKED_NV-1000491000]
	_ = x[COMPONENT_TYPE_UINT8_PACKED_NV-1000491001]
	_ = x[COMPONENT_TYPE_FLOAT8_E4M3_EXT-1000567002]
	_ = x[COMPONENT_TYPE_FLOAT8_E5M2_EXT-1000567003]
	_ = x[COMPONENT_TYPE_FLOAT16_NV-0]
	_ = x[COMPONENT_TYPE_FLOAT32_NV-1]
	_ = x[COMPONENT_TYPE_FLOAT64_NV-2]
	_ = x[COMPONENT_TYPE_FLOAT_E4M3_NV-1000567002]
	_ = x[COMPONENT_TYPE_FLOAT_E5M2_NV-1000567003]
	_ = x[COMPONENT_TYPE_SINT16_NV-4]
	_ = x[COMPONENT_TYPE_SINT32_NV-5]
	_ = x[COMPONENT_TYPE_SINT64_NV-6]
	_ = x[COMPONENT_TYPE_SINT8_NV-3]
	_ = x[COMPONENT_TYPE_UINT16_NV-8]
	_ = x[COMPONENT_TYPE_UINT32_NV-9]
	_ = x[COMPONENT_TYPE_UINT64_NV-10]
	_ = x[COMPONENT_TYPE_UINT8_NV-7]
}

const (
	_ComponentTypeKHR_name_0 = "COMPONENT_TYPE_FLOAT16_KHRCOMPONENT_TYPE_FLOAT32_KHRCOMPONENT_TYPE_FLOAT64_KHRCOMPONENT_TYPE_SINT8_KHRCOMPONENT_TYPE_SINT16_KHRCOMPONENT_TYPE_SINT32_KHRCOMPONENT_TYPE_SINT64_KHRCOMPONENT_TYPE_UINT8_KHRCOMPONENT_TYPE_UINT16_KHRCOMPONENT_TYPE_UINT32_KHRCOMPONENT_TYPE_UINT64_KHR"
	_ComponentTypeKHR_name_1 = "COMPONENT_TYPE_BFLOAT16_KHR"
	_ComponentTypeKHR_name_2 = "COMPONENT_TYPE_SINT8_PACKED_NVCOMPONENT_TYPE_UINT8_PACKED_NV"
	_ComponentTypeKHR_name_3 = "COMPONENT_TYPE_FLOAT8_E4M3_EXTCOMPONENT_TYPE_FLOAT8_E5M2_EXT"
)

var (
	_ComponentTypeKHR_index_0 = [...]uint16{0, 26, 52, 78, 102, 127, 152, 177, 201, 226, 251, 276}
	_ComponentTypeKHR_index_2 = [...]uint8{0, 30, 60}
	_ComponentTypeKHR_index_3 = [...]uint8{0, 30, 60}
)

func (i ComponentTypeKHR) String() string {
	switch {
	case 0 <= i && i <= 10:
		return _ComponentTypeKHR_name_0[_ComponentTypeKHR_index_0[i]:_ComponentTypeKHR_index_0[i+1]]
	case i == 1000141000:
		return _ComponentTypeKHR_name_1
	case 1000491000 <= i && i <= 1000491001:
		i -= 1000491000
		return _ComponentTypeKHR_name_2[_ComponentTypeKHR_index_2[i]:_ComponentTypeKHR_index_2[i+1]]
	case 1000567002 <= i && i <= 1000567003:
		i -= 1000567002
		return _ComponentTypeKHR_name_3[_ComponentTypeKHR_index_3[i]:_ComponentTypeKHR_index_3[i+1]]
	default:
		return "ComponentTypeKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COMPOSITE_ALPHA_OPAQUE_BIT_KHR-1]
	_ = x[COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR-2]
	_ = x[COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR-4]
	_ = x[COMPOSITE_ALPHA_INHERIT_BIT_KHR-8]
}

const (
	_CompositeAlphaFlagBitsKHR_name_0 = "COMPOSITE_ALPHA_OPAQUE_BIT_KHRCOMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR"
	_CompositeAlphaFlagBitsKHR_name_1 = "COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR"
	_CompositeAlphaFlagBitsKHR_name_2 = "COMPOSITE_ALPHA_INHERIT_BIT_KHR"
)

var (
	_CompositeAlphaFlagBitsKHR_index_0 = [...]uint8{0, 30, 68}
)

func (i CompositeAlphaFlagBitsKHR) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _CompositeAlphaFlagBitsKHR_name_0[_CompositeAlphaFlagBitsKHR_index_0[i]:_CompositeAlphaFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _CompositeAlphaFlagBitsKHR_name_1
	case i == 8:
		return _CompositeAlphaFlagBitsKHR_name_2
	default:
		return "CompositeAlphaFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CONDITIONAL_RENDERING_INVERTED_BIT_EXT-1]
}

const _ConditionalRenderingFlagBitsEXT_name = "CONDITIONAL_RENDERING_INVERTED_BIT_EXT"

var _ConditionalRenderingFlagBitsEXT_index = [...]uint8{0, 38}

func (i ConditionalRenderingFlagBitsEXT) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ConditionalRenderingFlagBitsEXT_index)-1 {
		return "ConditionalRenderingFlagBitsEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConditionalRenderingFlagBitsEXT_name[_ConditionalRenderingFlagBitsEXT_index[idx]:_ConditionalRenderingFlagBitsEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CONSERVATIVE_RASTERIZATION_MODE_DISABLED_EXT-0]
	_ = x[CONSERVATIVE_RASTERIZATION_MODE_OVERESTIMATE_EXT-1]
	_ = x[CONSERVATIVE_RASTERIZATION_MODE_UNDERESTIMATE_EXT-2]
}

const _ConservativeRasterizationModeEXT_name = "CONSERVATIVE_RASTERIZATION_MODE_DISABLED_EXTCONSERVATIVE_RASTERIZATION_MODE_OVERESTIMATE_EXTCONSERVATIVE_RASTERIZATION_MODE_UNDERESTIMATE_EXT"

var _ConservativeRasterizationModeEXT_index = [...]uint8{0, 44, 92, 141}

func (i ConservativeRasterizationModeEXT) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ConservativeRasterizationModeEXT_index)-1 {
		return "ConservativeRasterizationModeEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConservativeRasterizationModeEXT_name[_ConservativeRasterizationModeEXT_index[idx]:_ConservativeRasterizationModeEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COOPERATIVE_VECTOR_MATRIX_LAYOUT_ROW_MAJOR_NV-0]
	_ = x[COOPERATIVE_VECTOR_MATRIX_LAYOUT_COLUMN_MAJOR_NV-1]
	_ = x[COOPERATIVE_VECTOR_MATRIX_LAYOUT_INFERENCING_OPTIMAL_NV-2]
	_ = x[COOPERATIVE_VECTOR_MATRIX_LAYOUT_TRAINING_OPTIMAL_NV-3]
}

const _CooperativeVectorMatrixLayoutNV_name = "COOPERATIVE_VECTOR_MATRIX_LAYOUT_ROW_MAJOR_NVCOOPERATIVE_VECTOR_MATRIX_LAYOUT_COLUMN_MAJOR_NVCOOPERATIVE_VECTOR_MATRIX_LAYOUT_INFERENCING_OPTIMAL_NVCOOPERATIVE_VECTOR_MATRIX_LAYOUT_TRAINING_OPTIMAL_NV"

var _CooperativeVectorMatrixLayoutNV_index = [...]uint8{0, 45, 93, 148, 200}

func (i CooperativeVectorMatrixLayoutNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CooperativeVectorMatrixLayoutNV_index)-1 {
		return "CooperativeVectorMatrixLayoutNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CooperativeVectorMatrixLayoutNV_name[_CooperativeVectorMatrixLayoutNV_index[idx]:_CooperativeVectorMatrixLayoutNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COPY_ACCELERATION_STRUCTURE_MODE_CLONE_KHR-0]
	_ = x[COPY_ACCELERATION_STRUCTURE_MODE_COMPACT_KHR-1]
	_ = x[COPY_ACCELERATION_STRUCTURE_MODE_DESERIALIZE_KHR-1000150000]
	_ = x[COPY_ACCELERATION_STRUCTURE_MODE_SERIALIZE_KHR-1000150000]
	_ = x[COPY_ACCELERATION_STRUCTURE_MODE_CLONE_NV-0]
	_ = x[COPY_ACCELERATION_STRUCTURE_MODE_COMPACT_NV-1]
}

const (
	_CopyAccelerationStructureModeKHR_name_0 = "COPY_ACCELERATION_STRUCTURE_MODE_CLONE_KHRCOPY_ACCELERATION_STRUCTURE_MODE_COMPACT_KHR"
	_CopyAccelerationStructureModeKHR_name_1 = "COPY_ACCELERATION_STRUCTURE_MODE_DESERIALIZE_KHR"
)

var (
	_CopyAccelerationStructureModeKHR_index_0 = [...]uint8{0, 42, 86}
)

func (i CopyAccelerationStructureModeKHR) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _CopyAccelerationStructureModeKHR_name_0[_CopyAccelerationStructureModeKHR_index_0[i]:_CopyAccelerationStructureModeKHR_index_0[i+1]]
	case i == 1000150000:
		return _CopyAccelerationStructureModeKHR_name_1
	default:
		return "CopyAccelerationStructureModeKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COPY_MICROMAP_MODE_CLONE_EXT-0]
	_ = x[COPY_MICROMAP_MODE_SERIALIZE_EXT-1]
	_ = x[COPY_MICROMAP_MODE_DESERIALIZE_EXT-2]
	_ = x[COPY_MICROMAP_MODE_COMPACT_EXT-3]
}

const _CopyMicromapModeEXT_name = "COPY_MICROMAP_MODE_CLONE_EXTCOPY_MICROMAP_MODE_SERIALIZE_EXTCOPY_MICROMAP_MODE_DESERIALIZE_EXTCOPY_MICROMAP_MODE_COMPACT_EXT"

var _CopyMicromapModeEXT_index = [...]uint8{0, 28, 60, 94, 124}

func (i CopyMicromapModeEXT) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CopyMicromapModeEXT_index)-1 {
		return "CopyMicromapModeEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CopyMicromapModeEXT_name[_CopyMicromapModeEXT_index[idx]:_CopyMicromapModeEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COVERAGE_MODULATION_MODE_NONE_NV-0]
	_ = x[COVERAGE_MODULATION_MODE_RGB_NV-1]
	_ = x[COVERAGE_MODULATION_MODE_ALPHA_NV-2]
	_ = x[COVERAGE_MODULATION_MODE_RGBA_NV-3]
}

const _CoverageModulationModeNV_name = "COVERAGE_MODULATION_MODE_NONE_NVCOVERAGE_MODULATION_MODE_RGB_NVCOVERAGE_MODULATION_MODE_ALPHA_NVCOVERAGE_MODULATION_MODE_RGBA_NV"

var _CoverageModulationModeNV_index = [...]uint8{0, 32, 63, 96, 128}

func (i CoverageModulationModeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CoverageModulationModeNV_index)-1 {
		return "CoverageModulationModeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CoverageModulationModeNV_name[_CoverageModulationModeNV_index[idx]:_CoverageModulationModeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COVERAGE_REDUCTION_MODE_MERGE_NV-0]
	_ = x[COVERAGE_REDUCTION_MODE_TRUNCATE_NV-1]
}

const _CoverageReductionModeNV_name = "COVERAGE_REDUCTION_MODE_MERGE_NVCOVERAGE_REDUCTION_MODE_TRUNCATE_NV"

var _CoverageReductionModeNV_index = [...]uint8{0, 32, 67}

func (i CoverageReductionModeNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CoverageReductionModeNV_index)-1 {
		return "CoverageReductionModeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CoverageReductionModeNV_name[_CoverageReductionModeNV_index[idx]:_CoverageReductionModeNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CUBIC_FILTER_WEIGHTS_CATMULL_ROM_QCOM-0]
	_ = x[CUBIC_FILTER_WEIGHTS_ZERO_TANGENT_CARDINAL_QCOM-1]
	_ = x[CUBIC_FILTER_WEIGHTS_B_SPLINE_QCOM-2]
	_ = x[CUBIC_FILTER_WEIGHTS_MITCHELL_NETRAVALI_QCOM-3]
}

const _CubicFilterWeightsQCOM_name = "CUBIC_FILTER_WEIGHTS_CATMULL_ROM_QCOMCUBIC_FILTER_WEIGHTS_ZERO_TANGENT_CARDINAL_QCOMCUBIC_FILTER_WEIGHTS_B_SPLINE_QCOMCUBIC_FILTER_WEIGHTS_MITCHELL_NETRAVALI_QCOM"

var _CubicFilterWeightsQCOM_index = [...]uint8{0, 37, 84, 118, 162}

func (i CubicFilterWeightsQCOM) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CubicFilterWeightsQCOM_index)-1 {
		return "CubicFilterWeightsQCOM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CubicFilterWeightsQCOM_name[_CubicFilterWeightsQCOM_index[idx]:_CubicFilterWeightsQCOM_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CULL_MODE_NONE-0]
	_ = x[CULL_MODE_FRONT_AND_BACK-3]
	_ = x[CULL_MODE_FRONT_BIT-1]
	_ = x[CULL_MODE_BACK_BIT-2]
}

const _CullModeFlagBits_name = "CULL_MODE_NONECULL_MODE_FRONT_BITCULL_MODE_BACK_BITCULL_MODE_FRONT_AND_BACK"

var _CullModeFlagBits_index = [...]uint8{0, 14, 33, 51, 75}

func (i CullModeFlagBits) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CullModeFlagBits_index)-1 {
		return "CullModeFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CullModeFlagBits_name[_CullModeFlagBits_index[idx]:_CullModeFlagBits_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DATA_GRAPH_PIPELINE_PROPERTY_CREATION_LOG_ARM-0]
	_ = x[DATA_GRAPH_PIPELINE_PROPERTY_IDENTIFIER_ARM-1]
}

const _DataGraphPipelinePropertyARM_name = "DATA_GRAPH_PIPELINE_PROPERTY_CREATION_LOG_ARMDATA_GRAPH_PIPELINE_PROPERTY_IDENTIFIER_ARM"

var _DataGraphPipelinePropertyARM_index = [...]uint8{0, 45, 88}

func (i DataGraphPipelinePropertyARM) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DataGraphPipelinePropertyARM_index)-1 {
		return "DataGraphPipelinePropertyARM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataGraphPipelinePropertyARM_name[_DataGraphPipelinePropertyARM_index[idx]:_DataGraphPipelinePropertyARM_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DATA_GRAPH_PIPELINE_SESSION_BIND_POINT_TRANSIENT_ARM-0]
}

const _DataGraphPipelineSessionBindPointARM_name = "DATA_GRAPH_PIPELINE_SESSION_BIND_POINT_TRANSIENT_ARM"

var _DataGraphPipelineSessionBindPointARM_index = [...]uint8{0, 52}

func (i DataGraphPipelineSessionBindPointARM) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DataGraphPipelineSessionBindPointARM_index)-1 {
		return "DataGraphPipelineSessionBindPointARM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataGraphPipelineSessionBindPointARM_name[_DataGraphPipelineSessionBindPointARM_index[idx]:_DataGraphPipelineSessionBindPointARM_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DATA_GRAPH_PIPELINE_SESSION_BIND_POINT_TYPE_MEMORY_ARM-0]
}

const _DataGraphPipelineSessionBindPointTypeARM_name = "DATA_GRAPH_PIPELINE_SESSION_BIND_POINT_TYPE_MEMORY_ARM"

var _DataGraphPipelineSessionBindPointTypeARM_index = [...]uint8{0, 54}

func (i DataGraphPipelineSessionBindPointTypeARM) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DataGraphPipelineSessionBindPointTypeARM_index)-1 {
		return "DataGraphPipelineSessionBindPointTypeARM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataGraphPipelineSessionBindPointTypeARM_name[_DataGraphPipelineSessionBindPointTypeARM_index[idx]:_DataGraphPipelineSessionBindPointTypeARM_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DATA_GRAPH_PIPELINE_SESSION_CREATE_PROTECTED_BIT_ARM-1]
}

const _DataGraphPipelineSessionCreateFlagBitsARM_name = "DATA_GRAPH_PIPELINE_SESSION_CREATE_PROTECTED_BIT_ARM"

var _DataGraphPipelineSessionCreateFlagBitsARM_index = [...]uint8{0, 52}

func (i DataGraphPipelineSessionCreateFlagBitsARM) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_DataGraphPipelineSessionCreateFlagBitsARM_index)-1 {
		return "DataGraphPipelineSessionCreateFlagBitsARM(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataGraphPipelineSessionCreateFlagBitsARM_name[_DataGraphPipelineSessionCreateFlagBitsARM_index[idx]:_DataGraphPipelineSessionCreateFlagBitsARM_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEBUG_REPORT_INFORMATION_BIT_EXT-1]
	_ = x[DEBUG_REPORT_WARNING_BIT_EXT-2]
	_ = x[DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT-4]
	_ = x[DEBUG_REPORT_ERROR_BIT_EXT-8]
	_ = x[DEBUG_REPORT_DEBUG_BIT_EXT-16]
}

const (
	_DebugReportFlagBitsEXT_name_0 = "DEBUG_REPORT_INFORMATION_BIT_EXTDEBUG_REPORT_WARNING_BIT_EXT"
	_DebugReportFlagBitsEXT_name_1 = "DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT"
	_DebugReportFlagBitsEXT_name_2 = "DEBUG_REPORT_ERROR_BIT_EXT"
	_DebugReportFlagBitsEXT_name_3 = "DEBUG_REPORT_DEBUG_BIT_EXT"
)

var (
	_DebugReportFlagBitsEXT_index_0 = [...]uint8{0, 32, 60}
)

func (i DebugReportFlagBitsEXT) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _DebugReportFlagBitsEXT_name_0[_DebugReportFlagBitsEXT_index_0[i]:_DebugReportFlagBitsEXT_index_0[i+1]]
	case i == 4:
		return _DebugReportFlagBitsEXT_name_1
	case i == 8:
		return _DebugReportFlagBitsEXT_name_2
	case i == 16:
		return _DebugReportFlagBitsEXT_name_3
	default:
		return "DebugReportFlagBitsEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT-0]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_INSTANCE_EXT-1]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_PHYSICAL_DEVICE_EXT-2]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_DEVICE_EXT-3]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_QUEUE_EXT-4]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_SEMAPHORE_EXT-5]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT-6]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_FENCE_EXT-7]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_DEVICE_MEMORY_EXT-8]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_BUFFER_EXT-9]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_IMAGE_EXT-10]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_EVENT_EXT-11]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_QUERY_POOL_EXT-12]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_BUFFER_VIEW_EXT-13]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_IMAGE_VIEW_EXT-14]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_SHADER_MODULE_EXT-15]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_PIPELINE_CACHE_EXT-16]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_PIPELINE_LAYOUT_EXT-17]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_RENDER_PASS_EXT-18]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_PIPELINE_EXT-19]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT_EXT-20]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_SAMPLER_EXT-21]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_POOL_EXT-22]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_EXT-23]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_FRAMEBUFFER_EXT-24]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_COMMAND_POOL_EXT-25]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_SURFACE_KHR_EXT-26]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_SWAPCHAIN_KHR_EXT-27]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXT-28]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_DISPLAY_KHR_EXT-29]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_DISPLAY_MODE_KHR_EXT-30]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT-33]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_EXT-1000011000]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_CU_MODULE_NVX_EXT-1000029000]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_CU_FUNCTION_NVX_EXT-1000029001]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_ACCELERATION_STRUCTURE_KHR_EXT-1000150000]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_EXT-1000156000]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_ACCELERATION_STRUCTURE_NV_EXT-1000165000]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_EXT-28]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_KHR_EXT-1000011000]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR_EXT-1000156000]
	_ = x[DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT-33]
}

const (
	_DebugReportObjectTypeEXT_name_0 = "DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXTDEBUG_REPORT_OBJECT_TYPE_INSTANCE_EXTDEBUG_REPORT_OBJECT_TYPE_PHYSICAL_DEVICE_EXTDEBUG_REPORT_OBJECT_TYPE_DEVICE_EXTDEBUG_REPORT_OBJECT_TYPE_QUEUE_EXTDEBUG_REPORT_OBJECT_TYPE_SEMAPHORE_EXTDEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXTDEBUG_REPORT_OBJECT_TYPE_FENCE_EXTDEBUG_REPORT_OBJECT_TYPE_DEVICE_MEMORY_EXTDEBUG_REPORT_OBJECT_TYPE_BUFFER_EXTDEBUG_REPORT_OBJECT_TYPE_IMAGE_EXTDEBUG_REPORT_OBJECT_TYPE_EVENT_EXTDEBUG_REPORT_OBJECT_TYPE_QUERY_POOL_EXTDEBUG_REPORT_OBJECT_TYPE_BUFFER_VIEW_EXTDEBUG_REPORT_OBJECT_TYPE_IMAGE_VIEW_EXTDEBUG_REPORT_OBJECT_TYPE_SHADER_MODULE_EXTDEBUG_REPORT_OBJECT_TYPE_PIPELINE_CACHE_EXTDEBUG_REPORT_OBJECT_TYPE_PIPELINE_LAYOUT_EXTDEBUG_REPORT_OBJECT_TYPE_RENDER_PASS_EXTDEBUG_REPORT_OBJECT_TYPE_PIPELINE_EXTDEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT_EXTDEBUG_REPORT_OBJECT_TYPE_SAMPLER_EXTDEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_POOL_EXTDEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_EXTDEBUG_REPORT_OBJECT_TYPE_FRAMEBUFFER_EXTDEBUG_REPORT_OBJECT_TYPE_COMMAND_POOL_EXTDEBUG_REPORT_OBJECT_TYPE_SURFACE_KHR_EXTDEBUG_REPORT_OBJECT_TYPE_SWAPCHAIN_KHR_EXTDEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXTDEBUG_REPORT_OBJECT_TYPE_DISPLAY_KHR_EXTDEBUG_REPORT_OBJECT_TYPE_DISPLAY_MODE_KHR_EXT"
	_DebugReportObjectTypeEXT_name_1 = "DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT"
	_DebugReportObjectTypeEXT_name_2 = "DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_EXT"
	_DebugReportObjectTypeEXT_name_3 = "DEBUG_REPORT_OBJECT_TYPE_CU_MODULE_NVX_EXTDEBUG_REPORT_OBJECT_TYPE_CU_FUNCTION_NVX_EXT"
	_DebugReportObjectTypeEXT_name_4 = "DEBUG_REPORT_OBJECT_TYPE_ACCELERATION_STRUCTURE_KHR_EXT"
	_DebugReportObjectTypeEXT_name_5 = "DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_EXT"
	_DebugReportObjectTypeEXT_name_6 = "DEBUG_REPORT_OBJECT_TYPE_ACCELERATION_STRUCTURE_NV_EXT"
)

var (
	_DebugReportObjectTypeEXT_index_0 = [...]uint16{0, 36, 73, 117, 152, 186, 224, 267, 301, 343, 378, 412, 446, 485, 525, 564, 606, 649, 693, 733, 770, 820, 856, 900, 943, 983, 1024, 1064, 1106, 1160, 1200, 1245}
	_DebugReportObjectTypeEXT_index_3 = [...]uint8{0, 42, 86}
)

func (i DebugReportObjectTypeEXT) String() string {
	switch {
	case 0 <= i && i <= 30:
		return _DebugReportObjectTypeEXT_name_0[_DebugReportObjectTypeEXT_index_0[i]:_DebugReportObjectTypeEXT_index_0[i+1]]
	case i == 33:
		return _DebugReportObjectTypeEXT_name_1
	case i == 1000011000:
		return _DebugReportObjectTypeEXT_name_2
	case 1000029000 <= i && i <= 1000029001:
		i -= 1000029000
		return _DebugReportObjectTypeEXT_name_3[_DebugReportObjectTypeEXT_index_3[i]:_DebugReportObjectTypeEXT_index_3[i+1]]
	case i == 1000150000:
		return _DebugReportObjectTypeEXT_name_4
	case i == 1000156000:
		return _DebugReportObjectTypeEXT_name_5
	case i == 1000165000:
		return _DebugReportObjectTypeEXT_name_6
	default:
		return "DebugReportObjectTypeEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
