// Code generated by go-vk from vk.xml at 2025-10-25 17:30:05.428766054 +0000 UTC m=+6.163099910. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_DIRECTFB_SURFACE_CREATE_INFO_EXT StructureType = 1000346000
)
