// Code generated by go-vk from vk.xml at 2025-10-25 17:30:05.698160025 +0000 UTC m=+6.432493861. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
