// Code generated by "stringer -output=enum_string_4.go -type=ImageViewCreateFlagBits,ImageViewType,IndexType,IndirectCommandsInputModeFlagBitsEXT,IndirectCommandsLayoutUsageFlagBitsEXT,IndirectCommandsLayoutUsageFlagBitsNV,IndirectCommandsTokenTypeEXT,IndirectCommandsTokenTypeNV,IndirectExecutionSetInfoTypeEXT,IndirectStateFlagBitsNV,InstanceCreateFlagBits,InternalAllocationType,LatencyMarkerNV,LayerSettingTypeEXT,LayeredDriverUnderlyingApiMSFT,LineRasterizationMode,LogicOp,MemoryAllocateFlagBits,MemoryDecompressionMethodFlagBitsNV,MemoryHeapFlagBits,MemoryMapFlagBits,MemoryOverallocationBehaviorAMD,MemoryPropertyFlagBits,MemoryUnmapFlagBits,MicromapCreateFlagBitsEXT,MicromapTypeEXT,ObjectType,OpacityMicromapFormatEXT,OpacityMicromapSpecialIndexEXT,OpticalFlowExecuteFlagBitsNV,OpticalFlowGridSizeFlagBitsNV"; DO NOT EDIT.

package vk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DYNAMIC_BIT_EXT-1]
	_ = x[IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DEFERRED_BIT_EXT-2]
	_ = x[IMAGE_VIEW_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT-4]
}

const (
	_ImageViewCreateFlagBits_name_0 = "IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DYNAMIC_BIT_EXTIMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DEFERRED_BIT_EXT"
	_ImageViewCreateFlagBits_name_1 = "IMAGE_VIEW_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT"
)

var (
	_ImageViewCreateFlagBits_index_0 = [...]uint8{0, 54, 109}
)

func (i ImageViewCreateFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ImageViewCreateFlagBits_name_0[_ImageViewCreateFlagBits_index_0[i]:_ImageViewCreateFlagBits_index_0[i+1]]
	case i == 4:
		return _ImageViewCreateFlagBits_name_1
	default:
		return "ImageViewCreateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IMAGE_VIEW_TYPE_1D-0]
	_ = x[IMAGE_VIEW_TYPE_2D-1]
	_ = x[IMAGE_VIEW_TYPE_3D-2]
	_ = x[IMAGE_VIEW_TYPE_CUBE-3]
	_ = x[IMAGE_VIEW_TYPE_1D_ARRAY-4]
	_ = x[IMAGE_VIEW_TYPE_2D_ARRAY-5]
	_ = x[IMAGE_VIEW_TYPE_CUBE_ARRAY-6]
}

const _ImageViewType_name = "IMAGE_VIEW_TYPE_1DIMAGE_VIEW_TYPE_2DIMAGE_VIEW_TYPE_3DIMAGE_VIEW_TYPE_CUBEIMAGE_VIEW_TYPE_1D_ARRAYIMAGE_VIEW_TYPE_2D_ARRAYIMAGE_VIEW_TYPE_CUBE_ARRAY"

var _ImageViewType_index = [...]uint8{0, 18, 36, 54, 74, 98, 122, 148}

func (i ImageViewType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ImageViewType_index)-1 {
		return "ImageViewType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ImageViewType_name[_ImageViewType_index[idx]:_ImageViewType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INDEX_TYPE_UINT16-0]
	_ = x[INDEX_TYPE_UINT32-1]
	_ = x[INDEX_TYPE_NONE_KHR-1000150000]
	_ = x[INDEX_TYPE_UINT8-1000265000]
	_ = x[INDEX_TYPE_NONE_NV-1000150000]
	_ = x[INDEX_TYPE_UINT8_EXT-1000265000]
	_ = x[INDEX_TYPE_UINT8_KHR-1000265000]
}

const (
	_IndexType_name_0 = "INDEX_TYPE_UINT16INDEX_TYPE_UINT32"
	_IndexType_name_1 = "INDEX_TYPE_NONE_KHR"
	_IndexType_name_2 = "INDEX_TYPE_UINT8"
)

var (
	_IndexType_index_0 = [...]uint8{0, 17, 34}
)

func (i IndexType) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _IndexType_name_0[_IndexType_index_0[i]:_IndexType_index_0[i+1]]
	case i == 1000150000:
		return _IndexType_name_1
	case i == 1000265000:
		return _IndexType_name_2
	default:
		return "IndexType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INDIRECT_COMMANDS_INPUT_MODE_VULKAN_INDEX_BUFFER_EXT-1]
	_ = x[INDIRECT_COMMANDS_INPUT_MODE_DXGI_INDEX_BUFFER_EXT-2]
}

const _IndirectCommandsInputModeFlagBitsEXT_name = "INDIRECT_COMMANDS_INPUT_MODE_VULKAN_INDEX_BUFFER_EXTINDIRECT_COMMANDS_INPUT_MODE_DXGI_INDEX_BUFFER_EXT"

var _IndirectCommandsInputModeFlagBitsEXT_index = [...]uint8{0, 52, 102}

func (i IndirectCommandsInputModeFlagBitsEXT) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_IndirectCommandsInputModeFlagBitsEXT_index)-1 {
		return "IndirectCommandsInputModeFlagBitsEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IndirectCommandsInputModeFlagBitsEXT_name[_IndirectCommandsInputModeFlagBitsEXT_index[idx]:_IndirectCommandsInputModeFlagBitsEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INDIRECT_COMMANDS_LAYOUT_USAGE_EXPLICIT_PREPROCESS_BIT_EXT-1]
	_ = x[INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_EXT-2]
}

const _IndirectCommandsLayoutUsageFlagBitsEXT_name = "INDIRECT_COMMANDS_LAYOUT_USAGE_EXPLICIT_PREPROCESS_BIT_EXTINDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_EXT"

var _IndirectCommandsLayoutUsageFlagBitsEXT_index = [...]uint8{0, 58, 116}

func (i IndirectCommandsLayoutUsageFlagBitsEXT) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_IndirectCommandsLayoutUsageFlagBitsEXT_index)-1 {
		return "IndirectCommandsLayoutUsageFlagBitsEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IndirectCommandsLayoutUsageFlagBitsEXT_name[_IndirectCommandsLayoutUsageFlagBitsEXT_index[idx]:_IndirectCommandsLayoutUsageFlagBitsEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INDIRECT_COMMANDS_LAYOUT_USAGE_EXPLICIT_PREPROCESS_BIT_NV-1]
	_ = x[INDIRECT_COMMANDS_LAYOUT_USAGE_INDEXED_SEQUENCES_BIT_NV-2]
	_ = x[INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_NV-4]
}

const (
	_IndirectCommandsLayoutUsageFlagBitsNV_name_0 = "INDIRECT_COMMANDS_LAYOUT_USAGE_EXPLICIT_PREPROCESS_BIT_NVINDIRECT_COMMANDS_LAYOUT_USAGE_INDEXED_SEQUENCES_BIT_NV"
	_IndirectCommandsLayoutUsageFlagBitsNV_name_1 = "INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_NV"
)

var (
	_IndirectCommandsLayoutUsageFlagBitsNV_index_0 = [...]uint8{0, 57, 112}
)

func (i IndirectCommandsLayoutUsageFlagBitsNV) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _IndirectCommandsLayoutUsageFlagBitsNV_name_0[_IndirectCommandsLayoutUsageFlagBitsNV_index_0[i]:_IndirectCommandsLayoutUsageFlagBitsNV_index_0[i+1]]
	case i == 4:
		return _IndirectCommandsLayoutUsageFlagBitsNV_name_1
	default:
		return "IndirectCommandsLayoutUsageFlagBitsNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT-0]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_EXT-1]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_SEQUENCE_INDEX_EXT-2]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_EXT-3]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_EXT-4]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_EXT-5]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_EXT-6]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_COUNT_EXT-7]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_COUNT_EXT-8]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_EXT-9]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_NV_EXT-1000202002]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_COUNT_NV_EXT-1000202003]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_EXT-1000328000]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_COUNT_EXT-1000328001]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_TRACE_RAYS2_EXT-1000386004]
}

const (
	_IndirectCommandsTokenTypeEXT_name_0 = "INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXTINDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_EXTINDIRECT_COMMANDS_TOKEN_TYPE_SEQUENCE_INDEX_EXTINDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_EXTINDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_EXTINDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_EXTINDIRECT_COMMANDS_TOKEN_TYPE_DRAW_EXTINDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_COUNT_EXTINDIRECT_COMMANDS_TOKEN_TYPE_DRAW_COUNT_EXTINDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_EXT"
	_IndirectCommandsTokenTypeEXT_name_1 = "INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_NV_EXTINDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_COUNT_NV_EXT"
	_IndirectCommandsTokenTypeEXT_name_2 = "INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_EXTINDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_COUNT_EXT"
	_IndirectCommandsTokenTypeEXT_name_3 = "INDIRECT_COMMANDS_TOKEN_TYPE_TRACE_RAYS2_EXT"
)

var (
	_IndirectCommandsTokenTypeEXT_index_0 = [...]uint16{0, 46, 92, 139, 184, 230, 275, 312, 363, 406, 447}
	_IndirectCommandsTokenTypeEXT_index_1 = [...]uint8{0, 51, 108}
	_IndirectCommandsTokenTypeEXT_index_2 = [...]uint8{0, 48, 102}
)

func (i IndirectCommandsTokenTypeEXT) String() string {
	switch {
	case 0 <= i && i <= 9:
		return _IndirectCommandsTokenTypeEXT_name_0[_IndirectCommandsTokenTypeEXT_index_0[i]:_IndirectCommandsTokenTypeEXT_index_0[i+1]]
	case 1000202002 <= i && i <= 1000202003:
		i -= 1000202002
		return _IndirectCommandsTokenTypeEXT_name_1[_IndirectCommandsTokenTypeEXT_index_1[i]:_IndirectCommandsTokenTypeEXT_index_1[i+1]]
	case 1000328000 <= i && i <= 1000328001:
		i -= 1000328000
		return _IndirectCommandsTokenTypeEXT_name_2[_IndirectCommandsTokenTypeEXT_index_2[i]:_IndirectCommandsTokenTypeEXT_index_2[i+1]]
	case i == 1000386004:
		return _IndirectCommandsTokenTypeEXT_name_3
	default:
		return "IndirectCommandsTokenTypeEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_SHADER_GROUP_NV-0]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_STATE_FLAGS_NV-1]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_NV-2]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_NV-3]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_NV-4]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_NV-5]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_NV-6]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_TASKS_NV-7]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_NV-1000328000]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_PIPELINE_NV-1000428003]
	_ = x[INDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_NV-1000428004]
}

const (
	_IndirectCommandsTokenTypeNV_name_0 = "INDIRECT_COMMANDS_TOKEN_TYPE_SHADER_GROUP_NVINDIRECT_COMMANDS_TOKEN_TYPE_STATE_FLAGS_NVINDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_NVINDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_NVINDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_NVINDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_NVINDIRECT_COMMANDS_TOKEN_TYPE_DRAW_NVINDIRECT_COMMANDS_TOKEN_TYPE_DRAW_TASKS_NV"
	_IndirectCommandsTokenTypeNV_name_1 = "INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_NV"
	_IndirectCommandsTokenTypeNV_name_2 = "INDIRECT_COMMANDS_TOKEN_TYPE_PIPELINE_NVINDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_NV"
)

var (
	_IndirectCommandsTokenTypeNV_index_0 = [...]uint16{0, 44, 87, 131, 176, 221, 265, 301, 343}
	_IndirectCommandsTokenTypeNV_index_2 = [...]uint8{0, 40, 80}
)

func (i IndirectCommandsTokenTypeNV) String() string {
	switch {
	case 0 <= i && i <= 7:
		return _IndirectCommandsTokenTypeNV_name_0[_IndirectCommandsTokenTypeNV_index_0[i]:_IndirectCommandsTokenTypeNV_index_0[i+1]]
	case i == 1000328000:
		return _IndirectCommandsTokenTypeNV_name_1
	case 1000428003 <= i && i <= 1000428004:
		i -= 1000428003
		return _IndirectCommandsTokenTypeNV_name_2[_IndirectCommandsTokenTypeNV_index_2[i]:_IndirectCommandsTokenTypeNV_index_2[i+1]]
	default:
		return "IndirectCommandsTokenTypeNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INDIRECT_EXECUTION_SET_INFO_TYPE_PIPELINES_EXT-0]
	_ = x[INDIRECT_EXECUTION_SET_INFO_TYPE_SHADER_OBJECTS_EXT-1]
}

const _IndirectExecutionSetInfoTypeEXT_name = "INDIRECT_EXECUTION_SET_INFO_TYPE_PIPELINES_EXTINDIRECT_EXECUTION_SET_INFO_TYPE_SHADER_OBJECTS_EXT"

var _IndirectExecutionSetInfoTypeEXT_index = [...]uint8{0, 46, 97}

func (i IndirectExecutionSetInfoTypeEXT) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_IndirectExecutionSetInfoTypeEXT_index)-1 {
		return "IndirectExecutionSetInfoTypeEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IndirectExecutionSetInfoTypeEXT_name[_IndirectExecutionSetInfoTypeEXT_index[idx]:_IndirectExecutionSetInfoTypeEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INDIRECT_STATE_FLAG_FRONTFACE_BIT_NV-1]
}

const _IndirectStateFlagBitsNV_name = "INDIRECT_STATE_FLAG_FRONTFACE_BIT_NV"

var _IndirectStateFlagBitsNV_index = [...]uint8{0, 36}

func (i IndirectStateFlagBitsNV) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_IndirectStateFlagBitsNV_index)-1 {
		return "IndirectStateFlagBitsNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IndirectStateFlagBitsNV_name[_IndirectStateFlagBitsNV_index[idx]:_IndirectStateFlagBitsNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR-1]
}

const _InstanceCreateFlagBits_name = "INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR"

var _InstanceCreateFlagBits_index = [...]uint8{0, 45}

func (i InstanceCreateFlagBits) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_InstanceCreateFlagBits_index)-1 {
		return "InstanceCreateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InstanceCreateFlagBits_name[_InstanceCreateFlagBits_index[idx]:_InstanceCreateFlagBits_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INTERNAL_ALLOCATION_TYPE_EXECUTABLE-0]
}

const _InternalAllocationType_name = "INTERNAL_ALLOCATION_TYPE_EXECUTABLE"

var _InternalAllocationType_index = [...]uint8{0, 35}

func (i InternalAllocationType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_InternalAllocationType_index)-1 {
		return "InternalAllocationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InternalAllocationType_name[_InternalAllocationType_index[idx]:_InternalAllocationType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LATENCY_MARKER_SIMULATION_START_NV-0]
	_ = x[LATENCY_MARKER_SIMULATION_END_NV-1]
	_ = x[LATENCY_MARKER_RENDERSUBMIT_START_NV-2]
	_ = x[LATENCY_MARKER_RENDERSUBMIT_END_NV-3]
	_ = x[LATENCY_MARKER_PRESENT_START_NV-4]
	_ = x[LATENCY_MARKER_PRESENT_END_NV-5]
	_ = x[LATENCY_MARKER_INPUT_SAMPLE_NV-6]
	_ = x[LATENCY_MARKER_TRIGGER_FLASH_NV-7]
	_ = x[LATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_START_NV-8]
	_ = x[LATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_END_NV-9]
	_ = x[LATENCY_MARKER_OUT_OF_BAND_PRESENT_START_NV-10]
	_ = x[LATENCY_MARKER_OUT_OF_BAND_PRESENT_END_NV-11]
}

const _LatencyMarkerNV_name = "LATENCY_MARKER_SIMULATION_START_NVLATENCY_MARKER_SIMULATION_END_NVLATENCY_MARKER_RENDERSUBMIT_START_NVLATENCY_MARKER_RENDERSUBMIT_END_NVLATENCY_MARKER_PRESENT_START_NVLATENCY_MARKER_PRESENT_END_NVLATENCY_MARKER_INPUT_SAMPLE_NVLATENCY_MARKER_TRIGGER_FLASH_NVLATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_START_NVLATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_END_NVLATENCY_MARKER_OUT_OF_BAND_PRESENT_START_NVLATENCY_MARKER_OUT_OF_BAND_PRESENT_END_NV"

var _LatencyMarkerNV_index = [...]uint16{0, 34, 66, 102, 136, 167, 196, 226, 257, 305, 351, 394, 435}

func (i LatencyMarkerNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LatencyMarkerNV_index)-1 {
		return "LatencyMarkerNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LatencyMarkerNV_name[_LatencyMarkerNV_index[idx]:_LatencyMarkerNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LAYER_SETTING_TYPE_BOOL32_EXT-0]
	_ = x[LAYER_SETTING_TYPE_INT32_EXT-1]
	_ = x[LAYER_SETTING_TYPE_INT64_EXT-2]
	_ = x[LAYER_SETTING_TYPE_UINT32_EXT-3]
	_ = x[LAYER_SETTING_TYPE_UINT64_EXT-4]
	_ = x[LAYER_SETTING_TYPE_FLOAT32_EXT-5]
	_ = x[LAYER_SETTING_TYPE_FLOAT64_EXT-6]
	_ = x[LAYER_SETTING_TYPE_STRING_EXT-7]
}

const _LayerSettingTypeEXT_name = "LAYER_SETTING_TYPE_BOOL32_EXTLAYER_SETTING_TYPE_INT32_EXTLAYER_SETTING_TYPE_INT64_EXTLAYER_SETTING_TYPE_UINT32_EXTLAYER_SETTING_TYPE_UINT64_EXTLAYER_SETTING_TYPE_FLOAT32_EXTLAYER_SETTING_TYPE_FLOAT64_EXTLAYER_SETTING_TYPE_STRING_EXT"

var _LayerSettingTypeEXT_index = [...]uint8{0, 29, 57, 85, 114, 143, 173, 203, 232}

func (i LayerSettingTypeEXT) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LayerSettingTypeEXT_index)-1 {
		return "LayerSettingTypeEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LayerSettingTypeEXT_name[_LayerSettingTypeEXT_index[idx]:_LayerSettingTypeEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LAYERED_DRIVER_UNDERLYING_API_NONE_MSFT-0]
	_ = x[LAYERED_DRIVER_UNDERLYING_API_D3D12_MSFT-1]
}

const _LayeredDriverUnderlyingApiMSFT_name = "LAYERED_DRIVER_UNDERLYING_API_NONE_MSFTLAYERED_DRIVER_UNDERLYING_API_D3D12_MSFT"

var _LayeredDriverUnderlyingApiMSFT_index = [...]uint8{0, 39, 79}

func (i LayeredDriverUnderlyingApiMSFT) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LayeredDriverUnderlyingApiMSFT_index)-1 {
		return "LayeredDriverUnderlyingApiMSFT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LayeredDriverUnderlyingApiMSFT_name[_LayeredDriverUnderlyingApiMSFT_index[idx]:_LayeredDriverUnderlyingApiMSFT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LINE_RASTERIZATION_MODE_DEFAULT-0]
	_ = x[LINE_RASTERIZATION_MODE_RECTANGULAR-1]
	_ = x[LINE_RASTERIZATION_MODE_BRESENHAM-2]
	_ = x[LINE_RASTERIZATION_MODE_RECTANGULAR_SMOOTH-3]
	_ = x[LINE_RASTERIZATION_MODE_BRESENHAM_EXT-2]
	_ = x[LINE_RASTERIZATION_MODE_BRESENHAM_KHR-2]
	_ = x[LINE_RASTERIZATION_MODE_DEFAULT_EXT-0]
	_ = x[LINE_RASTERIZATION_MODE_DEFAULT_KHR-0]
	_ = x[LINE_RASTERIZATION_MODE_RECTANGULAR_EXT-1]
	_ = x[LINE_RASTERIZATION_MODE_RECTANGULAR_KHR-1]
	_ = x[LINE_RASTERIZATION_MODE_RECTANGULAR_SMOOTH_EXT-3]
	_ = x[LINE_RASTERIZATION_MODE_RECTANGULAR_SMOOTH_KHR-3]
}

const _LineRasterizationMode_name = "LINE_RASTERIZATION_MODE_DEFAULTLINE_RASTERIZATION_MODE_RECTANGULARLINE_RASTERIZATION_MODE_BRESENHAMLINE_RASTERIZATION_MODE_RECTANGULAR_SMOOTH"

var _LineRasterizationMode_index = [...]uint8{0, 31, 66, 99, 141}

func (i LineRasterizationMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LineRasterizationMode_index)-1 {
		return "LineRasterizationMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LineRasterizationMode_name[_LineRasterizationMode_index[idx]:_LineRasterizationMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LOGIC_OP_CLEAR-0]
	_ = x[LOGIC_OP_AND-1]
	_ = x[LOGIC_OP_AND_REVERSE-2]
	_ = x[LOGIC_OP_COPY-3]
	_ = x[LOGIC_OP_AND_INVERTED-4]
	_ = x[LOGIC_OP_NO_OP-5]
	_ = x[LOGIC_OP_XOR-6]
	_ = x[LOGIC_OP_OR-7]
	_ = x[LOGIC_OP_NOR-8]
	_ = x[LOGIC_OP_EQUIVALENT-9]
	_ = x[LOGIC_OP_INVERT-10]
	_ = x[LOGIC_OP_OR_REVERSE-11]
	_ = x[LOGIC_OP_COPY_INVERTED-12]
	_ = x[LOGIC_OP_OR_INVERTED-13]
	_ = x[LOGIC_OP_NAND-14]
	_ = x[LOGIC_OP_SET-15]
}

const _LogicOp_name = "LOGIC_OP_CLEARLOGIC_OP_ANDLOGIC_OP_AND_REVERSELOGIC_OP_COPYLOGIC_OP_AND_INVERTEDLOGIC_OP_NO_OPLOGIC_OP_XORLOGIC_OP_ORLOGIC_OP_NORLOGIC_OP_EQUIVALENTLOGIC_OP_INVERTLOGIC_OP_OR_REVERSELOGIC_OP_COPY_INVERTEDLOGIC_OP_OR_INVERTEDLOGIC_OP_NANDLOGIC_OP_SET"

var _LogicOp_index = [...]uint8{0, 14, 26, 46, 59, 80, 94, 106, 117, 129, 148, 163, 182, 204, 224, 237, 249}

func (i LogicOp) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LogicOp_index)-1 {
		return "LogicOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogicOp_name[_LogicOp_index[idx]:_LogicOp_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MEMORY_ALLOCATE_DEVICE_MASK_BIT-1]
	_ = x[MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT-2]
	_ = x[MEMORY_ALLOCATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT-4]
	_ = x[MEMORY_ALLOCATE_ZERO_INITIALIZE_BIT_EXT-8]
	_ = x[MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT_KHR-2]
	_ = x[MEMORY_ALLOCATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_KHR-4]
	_ = x[MEMORY_ALLOCATE_DEVICE_MASK_BIT_KHR-1]
}

const (
	_MemoryAllocateFlagBits_name_0 = "MEMORY_ALLOCATE_DEVICE_MASK_BITMEMORY_ALLOCATE_DEVICE_ADDRESS_BIT"
	_MemoryAllocateFlagBits_name_1 = "MEMORY_ALLOCATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT"
	_MemoryAllocateFlagBits_name_2 = "MEMORY_ALLOCATE_ZERO_INITIALIZE_BIT_EXT"
)

var (
	_MemoryAllocateFlagBits_index_0 = [...]uint8{0, 31, 65}
)

func (i MemoryAllocateFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _MemoryAllocateFlagBits_name_0[_MemoryAllocateFlagBits_index_0[i]:_MemoryAllocateFlagBits_index_0[i+1]]
	case i == 4:
		return _MemoryAllocateFlagBits_name_1
	case i == 8:
		return _MemoryAllocateFlagBits_name_2
	default:
		return "MemoryAllocateFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MEMORY_DECOMPRESSION_METHOD_GDEFLATE_1_0_BIT_NV-1]
}

const _MemoryDecompressionMethodFlagBitsNV_name = "MEMORY_DECOMPRESSION_METHOD_GDEFLATE_1_0_BIT_NV"

var _MemoryDecompressionMethodFlagBitsNV_index = [...]uint8{0, 47}

func (i MemoryDecompressionMethodFlagBitsNV) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_MemoryDecompressionMethodFlagBitsNV_index)-1 {
		return "MemoryDecompressionMethodFlagBitsNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MemoryDecompressionMethodFlagBitsNV_name[_MemoryDecompressionMethodFlagBitsNV_index[idx]:_MemoryDecompressionMethodFlagBitsNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MEMORY_HEAP_DEVICE_LOCAL_BIT-1]
	_ = x[MEMORY_HEAP_MULTI_INSTANCE_BIT-2]
	_ = x[MEMORY_HEAP_TILE_MEMORY_BIT_QCOM-8]
	_ = x[MEMORY_HEAP_MULTI_INSTANCE_BIT_KHR-2]
}

const (
	_MemoryHeapFlagBits_name_0 = "MEMORY_HEAP_DEVICE_LOCAL_BITMEMORY_HEAP_MULTI_INSTANCE_BIT"
	_MemoryHeapFlagBits_name_1 = "MEMORY_HEAP_TILE_MEMORY_BIT_QCOM"
)

var (
	_MemoryHeapFlagBits_index_0 = [...]uint8{0, 28, 58}
)

func (i MemoryHeapFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _MemoryHeapFlagBits_name_0[_MemoryHeapFlagBits_index_0[i]:_MemoryHeapFlagBits_index_0[i+1]]
	case i == 8:
		return _MemoryHeapFlagBits_name_1
	default:
		return "MemoryHeapFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MEMORY_MAP_PLACED_BIT_EXT-1]
}

const _MemoryMapFlagBits_name = "MEMORY_MAP_PLACED_BIT_EXT"

var _MemoryMapFlagBits_index = [...]uint8{0, 25}

func (i MemoryMapFlagBits) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_MemoryMapFlagBits_index)-1 {
		return "MemoryMapFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MemoryMapFlagBits_name[_MemoryMapFlagBits_index[idx]:_MemoryMapFlagBits_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MEMORY_OVERALLOCATION_BEHAVIOR_DEFAULT_AMD-0]
	_ = x[MEMORY_OVERALLOCATION_BEHAVIOR_ALLOWED_AMD-1]
	_ = x[MEMORY_OVERALLOCATION_BEHAVIOR_DISALLOWED_AMD-2]
}

const _MemoryOverallocationBehaviorAMD_name = "MEMORY_OVERALLOCATION_BEHAVIOR_DEFAULT_AMDMEMORY_OVERALLOCATION_BEHAVIOR_ALLOWED_AMDMEMORY_OVERALLOCATION_BEHAVIOR_DISALLOWED_AMD"

var _MemoryOverallocationBehaviorAMD_index = [...]uint8{0, 42, 84, 129}

func (i MemoryOverallocationBehaviorAMD) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MemoryOverallocationBehaviorAMD_index)-1 {
		return "MemoryOverallocationBehaviorAMD(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MemoryOverallocationBehaviorAMD_name[_MemoryOverallocationBehaviorAMD_index[idx]:_MemoryOverallocationBehaviorAMD_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MEMORY_PROPERTY_DEVICE_LOCAL_BIT-1]
	_ = x[MEMORY_PROPERTY_HOST_VISIBLE_BIT-2]
	_ = x[MEMORY_PROPERTY_HOST_COHERENT_BIT-4]
	_ = x[MEMORY_PROPERTY_HOST_CACHED_BIT-8]
	_ = x[MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT-16]
	_ = x[MEMORY_PROPERTY_PROTECTED_BIT-32]
	_ = x[MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD-64]
	_ = x[MEMORY_PROPERTY_DEVICE_UNCACHED_BIT_AMD-128]
	_ = x[MEMORY_PROPERTY_RDMA_CAPABLE_BIT_NV-256]
}

const (
	_MemoryPropertyFlagBits_name_0 = "MEMORY_PROPERTY_DEVICE_LOCAL_BITMEMORY_PROPERTY_HOST_VISIBLE_BIT"
	_MemoryPropertyFlagBits_name_1 = "MEMORY_PROPERTY_HOST_COHERENT_BIT"
	_MemoryPropertyFlagBits_name_2 = "MEMORY_PROPERTY_HOST_CACHED_BIT"
	_MemoryPropertyFlagBits_name_3 = "MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT"
	_MemoryPropertyFlagBits_name_4 = "MEMORY_PROPERTY_PROTECTED_BIT"
	_MemoryPropertyFlagBits_name_5 = "MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD"
	_MemoryPropertyFlagBits_name_6 = "MEMORY_PROPERTY_DEVICE_UNCACHED_BIT_AMD"
	_MemoryPropertyFlagBits_name_7 = "MEMORY_PROPERTY_RDMA_CAPABLE_BIT_NV"
)

var (
	_MemoryPropertyFlagBits_index_0 = [...]uint8{0, 32, 64}
)

func (i MemoryPropertyFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _MemoryPropertyFlagBits_name_0[_MemoryPropertyFlagBits_index_0[i]:_MemoryPropertyFlagBits_index_0[i+1]]
	case i == 4:
		return _MemoryPropertyFlagBits_name_1
	case i == 8:
		return _MemoryPropertyFlagBits_name_2
	case i == 16:
		return _MemoryPropertyFlagBits_name_3
	case i == 32:
		return _MemoryPropertyFlagBits_name_4
	case i == 64:
		return _MemoryPropertyFlagBits_name_5
	case i == 128:
		return _MemoryPropertyFlagBits_name_6
	case i == 256:
		return _MemoryPropertyFlagBits_name_7
	default:
		return "MemoryPropertyFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MEMORY_UNMAP_RESERVE_BIT_EXT-1]
}

const _MemoryUnmapFlagBits_name = "MEMORY_UNMAP_RESERVE_BIT_EXT"

var _MemoryUnmapFlagBits_index = [...]uint8{0, 28}

func (i MemoryUnmapFlagBits) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_MemoryUnmapFlagBits_index)-1 {
		return "MemoryUnmapFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MemoryUnmapFlagBits_name[_MemoryUnmapFlagBits_index[idx]:_MemoryUnmapFlagBits_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MICROMAP_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_EXT-1]
}

const _MicromapCreateFlagBitsEXT_name = "MICROMAP_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_EXT"

var _MicromapCreateFlagBitsEXT_index = [...]uint8{0, 53}

func (i MicromapCreateFlagBitsEXT) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_MicromapCreateFlagBitsEXT_index)-1 {
		return "MicromapCreateFlagBitsEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MicromapCreateFlagBitsEXT_name[_MicromapCreateFlagBitsEXT_index[idx]:_MicromapCreateFlagBitsEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MICROMAP_TYPE_OPACITY_MICROMAP_EXT-0]
}

const _MicromapTypeEXT_name = "MICROMAP_TYPE_OPACITY_MICROMAP_EXT"

var _MicromapTypeEXT_index = [...]uint8{0, 34}

func (i MicromapTypeEXT) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MicromapTypeEXT_index)-1 {
		return "MicromapTypeEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MicromapTypeEXT_name[_MicromapTypeEXT_index[idx]:_MicromapTypeEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OBJECT_TYPE_UNKNOWN-0]
	_ = x[OBJECT_TYPE_INSTANCE-1]
	_ = x[OBJECT_TYPE_PHYSICAL_DEVICE-2]
	_ = x[OBJECT_TYPE_DEVICE-3]
	_ = x[OBJECT_TYPE_QUEUE-4]
	_ = x[OBJECT_TYPE_SEMAPHORE-5]
	_ = x[OBJECT_TYPE_COMMAND_BUFFER-6]
	_ = x[OBJECT_TYPE_FENCE-7]
	_ = x[OBJECT_TYPE_DEVICE_MEMORY-8]
	_ = x[OBJECT_TYPE_BUFFER-9]
	_ = x[OBJECT_TYPE_IMAGE-10]
	_ = x[OBJECT_TYPE_EVENT-11]
	_ = x[OBJECT_TYPE_QUERY_POOL-12]
	_ = x[OBJECT_TYPE_BUFFER_VIEW-13]
	_ = x[OBJECT_TYPE_IMAGE_VIEW-14]
	_ = x[OBJECT_TYPE_SHADER_MODULE-15]
	_ = x[OBJECT_TYPE_PIPELINE_CACHE-16]
	_ = x[OBJECT_TYPE_PIPELINE_LAYOUT-17]
	_ = x[OBJECT_TYPE_RENDER_PASS-18]
	_ = x[OBJECT_TYPE_PIPELINE-19]
	_ = x[OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT-20]
	_ = x[OBJECT_TYPE_SAMPLER-21]
	_ = x[OBJECT_TYPE_DESCRIPTOR_POOL-22]
	_ = x[OBJECT_TYPE_DESCRIPTOR_SET-23]
	_ = x[OBJECT_TYPE_FRAMEBUFFER-24]
	_ = x[OBJECT_TYPE_COMMAND_POOL-25]
	_ = x[OBJECT_TYPE_SURFACE_KHR-1000000000]
	_ = x[OBJECT_TYPE_SWAPCHAIN_KHR-1000001000]
	_ = x[OBJECT_TYPE_DISPLAY_KHR-1000002000]
	_ = x[OBJECT_TYPE_DISPLAY_MODE_KHR-1000002001]
	_ = x[OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT-1000011000]
	_ = x[OBJECT_TYPE_VIDEO_SESSION_KHR-1000023000]
	_ = x[OBJECT_TYPE_VIDEO_SESSION_PARAMETERS_KHR-1000023001]
	_ = x[OBJECT_TYPE_CU_MODULE_NVX-1000029000]
	_ = x[OBJECT_TYPE_CU_FUNCTION_NVX-1000029001]
	_ = x[OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE-1000085000]
	_ = x[OBJECT_TYPE_DEBUG_UTILS_MESSENGER_EXT-1000128000]
	_ = x[OBJECT_TYPE_ACCELERATION_STRUCTURE_KHR-1000150000]
	_ = x[OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION-1000156000]
	_ = x[OBJECT_TYPE_VALIDATION_CACHE_EXT-1000160000]
	_ = x[OBJECT_TYPE_ACCELERATION_STRUCTURE_NV-1000165000]
	_ = x[OBJECT_TYPE_PERFORMANCE_CONFIGURATION_INTEL-1000210000]
	_ = x[OBJECT_TYPE_DEFERRED_OPERATION_KHR-1000268000]
	_ = x[OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NV-1000277000]
	_ = x[OBJECT_TYPE_PRIVATE_DATA_SLOT-1000295000]
	_ = x[OBJECT_TYPE_MICROMAP_EXT-1000396000]
	_ = x[OBJECT_TYPE_TENSOR_ARM-1000460000]
	_ = x[OBJECT_TYPE_TENSOR_VIEW_ARM-1000460001]
	_ = x[OBJECT_TYPE_OPTICAL_FLOW_SESSION_NV-1000464000]
	_ = x[OBJECT_TYPE_SHADER_EXT-1000482000]
	_ = x[OBJECT_TYPE_PIPELINE_BINARY_KHR-1000483000]
	_ = x[OBJECT_TYPE_DATA_GRAPH_PIPELINE_SESSION_ARM-1000507000]
	_ = x[OBJECT_TYPE_EXTERNAL_COMPUTE_QUEUE_NV-1000556000]
	_ = x[OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_EXT-1000572000]
	_ = x[OBJECT_TYPE_INDIRECT_EXECUTION_SET_EXT-1000572001]
	_ = x[OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_KHR-1000085000]
	_ = x[OBJECT_TYPE_PRIVATE_DATA_SLOT_EXT-1000295000]
	_ = x[OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR-1000156000]
}

const _ObjectType_name = "OBJECT_TYPE_UNKNOWNOBJECT_TYPE_INSTANCEOBJECT_TYPE_PHYSICAL_DEVICEOBJECT_TYPE_DEVICEOBJECT_TYPE_QUEUEOBJECT_TYPE_SEMAPHOREOBJECT_TYPE_COMMAND_BUFFEROBJECT_TYPE_FENCEOBJECT_TYPE_DEVICE_MEMORYOBJECT_TYPE_BUFFEROBJECT_TYPE_IMAGEOBJECT_TYPE_EVENTOBJECT_TYPE_QUERY_POOLOBJECT_TYPE_BUFFER_VIEWOBJECT_TYPE_IMAGE_VIEWOBJECT_TYPE_SHADER_MODULEOBJECT_TYPE_PIPELINE_CACHEOBJECT_TYPE_PIPELINE_LAYOUTOBJECT_TYPE_RENDER_PASSOBJECT_TYPE_PIPELINEOBJECT_TYPE_DESCRIPTOR_SET_LAYOUTOBJECT_TYPE_SAMPLEROBJECT_TYPE_DESCRIPTOR_POOLOBJECT_TYPE_DESCRIPTOR_SETOBJECT_TYPE_FRAMEBUFFEROBJECT_TYPE_COMMAND_POOLOBJECT_TYPE_SURFACE_KHROBJECT_TYPE_SWAPCHAIN_KHROBJECT_TYPE_DISPLAY_KHROBJECT_TYPE_DISPLAY_MODE_KHROBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXTOBJECT_TYPE_VIDEO_SESSION_KHROBJECT_TYPE_VIDEO_SESSION_PARAMETERS_KHROBJECT_TYPE_CU_MODULE_NVXOBJECT_TYPE_CU_FUNCTION_NVXOBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATEOBJECT_TYPE_DEBUG_UTILS_MESSENGER_EXTOBJECT_TYPE_ACCELERATION_STRUCTURE_KHROBJECT_TYPE_SAMPLER_YCBCR_CONVERSIONOBJECT_TYPE_VALIDATION_CACHE_EXTOBJECT_TYPE_ACCELERATION_STRUCTURE_NVOBJECT_TYPE_PERFORMANCE_CONFIGURATION_INTELOBJECT_TYPE_DEFERRED_OPERATION_KHROBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NVOBJECT_TYPE_PRIVATE_DATA_SLOTOBJECT_TYPE_MICROMAP_EXTOBJECT_TYPE_TENSOR_ARMOBJECT_TYPE_TENSOR_VIEW_ARMOBJECT_TYPE_OPTICAL_FLOW_SESSION_NVOBJECT_TYPE_SHADER_EXTOBJECT_TYPE_PIPELINE_BINARY_KHROBJECT_TYPE_DATA_GRAPH_PIPELINE_SESSION_ARMOBJECT_TYPE_EXTERNAL_COMPUTE_QUEUE_NVOBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_EXTOBJECT_TYPE_INDIRECT_EXECUTION_SET_EXT"

var _ObjectType_map = map[ObjectType]string{
	0:          _ObjectType_name[0:19],
	1:          _ObjectType_name[19:39],
	2:          _ObjectType_name[39:66],
	3:          _ObjectType_name[66:84],
	4:          _ObjectType_name[84:101],
	5:          _ObjectType_name[101:122],
	6:          _ObjectType_name[122:148],
	7:          _ObjectType_name[148:165],
	8:          _ObjectType_name[165:190],
	9:          _ObjectType_name[190:208],
	10:         _ObjectType_name[208:225],
	11:         _ObjectType_name[225:242],
	12:         _ObjectType_name[242:264],
	13:         _ObjectType_name[264:287],
	14:         _ObjectType_name[287:309],
	15:         _ObjectType_name[309:334],
	16:         _ObjectType_name[334:360],
	17:         _ObjectType_name[360:387],
	18:         _ObjectType_name[387:410],
	19:         _ObjectType_name[410:430],
	20:         _ObjectType_name[430:463],
	21:         _ObjectType_name[463:482],
	22:         _ObjectType_name[482:509],
	23:         _ObjectType_name[509:535],
	24:         _ObjectType_name[535:558],
	25:         _ObjectType_name[558:582],
	1000000000: _ObjectType_name[582:605],
	1000001000: _ObjectType_name[605:630],
	1000002000: _ObjectType_name[630:653],
	1000002001: _ObjectType_name[653:681],
	1000011000: _ObjectType_name[681:718],
	1000023000: _ObjectType_name[718:747],
	1000023001: _ObjectType_name[747:787],
	1000029000: _ObjectType_name[787:812],
	1000029001: _ObjectType_name[812:839],
	1000085000: _ObjectType_name[839:877],
	1000128000: _ObjectType_name[877:914],
	1000150000: _ObjectType_name[914:952],
	1000156000: _ObjectType_name[952:988],
	1000160000: _ObjectType_name[988:1020],
	1000165000: _ObjectType_name[1020:1057],
	1000210000: _ObjectType_name[1057:1100],
	1000268000: _ObjectType_name[1100:1134],
	1000277000: _ObjectType_name[1134:1173],
	1000295000: _ObjectType_name[1173:1202],
	1000396000: _ObjectType_name[1202:1226],
	1000460000: _ObjectType_name[1226:1248],
	1000460001: _ObjectType_name[1248:1275],
	1000464000: _ObjectType_name[1275:1310],
	1000482000: _ObjectType_name[1310:1332],
	1000483000: _ObjectType_name[1332:1363],
	1000507000: _ObjectType_name[1363:1406],
	1000556000: _ObjectType_name[1406:1443],
	1000572000: _ObjectType_name[1443:1483],
	1000572001: _ObjectType_name[1483:1521],
}

func (i ObjectType) String() string {
	if str, ok := _ObjectType_map[i]; ok {
		return str
	}
	return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OPACITY_MICROMAP_FORMAT_2_STATE_EXT-1]
	_ = x[OPACITY_MICROMAP_FORMAT_4_STATE_EXT-2]
}

const _OpacityMicromapFormatEXT_name = "OPACITY_MICROMAP_FORMAT_2_STATE_EXTOPACITY_MICROMAP_FORMAT_4_STATE_EXT"

var _OpacityMicromapFormatEXT_index = [...]uint8{0, 35, 70}

func (i OpacityMicromapFormatEXT) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_OpacityMicromapFormatEXT_index)-1 {
		return "OpacityMicromapFormatEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpacityMicromapFormatEXT_name[_OpacityMicromapFormatEXT_index[idx]:_OpacityMicromapFormatEXT_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_UNKNOWN_OPAQUE_EXT - -4]
	_ = x[OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_UNKNOWN_TRANSPARENT_EXT - -3]
	_ = x[OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_OPAQUE_EXT - -2]
	_ = x[OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_TRANSPARENT_EXT - -1]
	_ = x[OPACITY_MICROMAP_SPECIAL_INDEX_CLUSTER_GEOMETRY_DISABLE_OPACITY_MICROMAP_NV-1000569000]
}

const (
	_OpacityMicromapSpecialIndexEXT_name_0 = "OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_UNKNOWN_OPAQUE_EXTOPACITY_MICROMAP_SPECIAL_INDEX_FULLY_UNKNOWN_TRANSPARENT_EXTOPACITY_MICROMAP_SPECIAL_INDEX_FULLY_OPAQUE_EXTOPACITY_MICROMAP_SPECIAL_INDEX_FULLY_TRANSPARENT_EXT"
	_OpacityMicromapSpecialIndexEXT_name_1 = "OPACITY_MICROMAP_SPECIAL_INDEX_CLUSTER_GEOMETRY_DISABLE_OPACITY_MICROMAP_NV"
)

var (
	_OpacityMicromapSpecialIndexEXT_index_0 = [...]uint8{0, 55, 115, 162, 214}
)

func (i OpacityMicromapSpecialIndexEXT) String() string {
	switch {
	case -4 <= i && i <= -1:
		i -= -4
		return _OpacityMicromapSpecialIndexEXT_name_0[_OpacityMicromapSpecialIndexEXT_index_0[i]:_OpacityMicromapSpecialIndexEXT_index_0[i+1]]
	case i == 1000569000:
		return _OpacityMicromapSpecialIndexEXT_name_1
	default:
		return "OpacityMicromapSpecialIndexEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OPTICAL_FLOW_EXECUTE_DISABLE_TEMPORAL_HINTS_BIT_NV-1]
}

const _OpticalFlowExecuteFlagBitsNV_name = "OPTICAL_FLOW_EXECUTE_DISABLE_TEMPORAL_HINTS_BIT_NV"

var _OpticalFlowExecuteFlagBitsNV_index = [...]uint8{0, 50}

func (i OpticalFlowExecuteFlagBitsNV) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_OpticalFlowExecuteFlagBitsNV_index)-1 {
		return "OpticalFlowExecuteFlagBitsNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpticalFlowExecuteFlagBitsNV_name[_OpticalFlowExecuteFlagBitsNV_index[idx]:_OpticalFlowExecuteFlagBitsNV_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OPTICAL_FLOW_GRID_SIZE_UNKNOWN_NV-0]
	_ = x[OPTICAL_FLOW_GRID_SIZE_1X1_BIT_NV-1]
	_ = x[OPTICAL_FLOW_GRID_SIZE_2X2_BIT_NV-2]
	_ = x[OPTICAL_FLOW_GRID_SIZE_4X4_BIT_NV-4]
	_ = x[OPTICAL_FLOW_GRID_SIZE_8X8_BIT_NV-8]
}

const (
	_OpticalFlowGridSizeFlagBitsNV_name_0 = "OPTICAL_FLOW_GRID_SIZE_UNKNOWN_NVOPTICAL_FLOW_GRID_SIZE_1X1_BIT_NVOPTICAL_FLOW_GRID_SIZE_2X2_BIT_NV"
	_OpticalFlowGridSizeFlagBitsNV_name_1 = "OPTICAL_FLOW_GRID_SIZE_4X4_BIT_NV"
	_OpticalFlowGridSizeFlagBitsNV_name_2 = "OPTICAL_FLOW_GRID_SIZE_8X8_BIT_NV"
)

var (
	_OpticalFlowGridSizeFlagBitsNV_index_0 = [...]uint8{0, 33, 66, 99}
)

func (i OpticalFlowGridSizeFlagBitsNV) String() string {
	switch {
	case i <= 2:
		return _OpticalFlowGridSizeFlagBitsNV_name_0[_OpticalFlowGridSizeFlagBitsNV_index_0[i]:_OpticalFlowGridSizeFlagBitsNV_index_0[i+1]]
	case i == 4:
		return _OpticalFlowGridSizeFlagBitsNV_name_1
	case i == 8:
		return _OpticalFlowGridSizeFlagBitsNV_name_2
	default:
		return "OpticalFlowGridSizeFlagBitsNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
