// Code generated by go-vk from vk.xml at 2025-10-25 17:30:05.174362041 +0000 UTC m=+5.908695807. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR StructureType = 1000005000
)
