// Code generated by go-vk from vk.xml at 2025-10-26 13:04:52.873265545 +0000 UTC m=+12.280963813. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR StructureType = 1000005000
)
