//go:build darwin

// Code generated by go-vk from vk.xml at 2025-10-25 17:30:05.444774523 +0000 UTC m=+6.179108309. DO NOT EDIT.

package vk

// Extension names and versions
const (
	MVK_MACOS_SURFACE_EXTENSION_NAME = "VK_MVK_macos_surface"
	MVK_MACOS_SURFACE_SPEC_VERSION   = 3
)
