//go:build linux

// Code generated by go-vk from vk.xml at 2025-10-25 17:30:05.183019201 +0000 UTC m=+5.917352977. DO NOT EDIT.

package vk

// Extension names and versions
const (
	KHR_XCB_SURFACE_EXTENSION_NAME = "VK_KHR_xcb_surface"
	KHR_XCB_SURFACE_SPEC_VERSION   = 6
)
