//go:build darwin

// Code generated by go-vk from vk.xml at 2025-10-25 17:30:05.991030975 +0000 UTC m=+6.725364741. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_EXTERNAL_MEMORY_METAL_EXTENSION_NAME = "VK_EXT_external_memory_metal"
	EXT_EXTERNAL_MEMORY_METAL_SPEC_VERSION   = 1
	EXT_METAL_OBJECTS_EXTENSION_NAME         = "VK_EXT_metal_objects"
	EXT_METAL_OBJECTS_SPEC_VERSION           = 2
	EXT_METAL_SURFACE_EXTENSION_NAME         = "VK_EXT_metal_surface"
	EXT_METAL_SURFACE_SPEC_VERSION           = 1
)
