//go:build linux

// Code generated by go-vk from vk.xml at 2025-10-25 17:30:06.31104922 +0000 UTC m=+7.045382996. DO NOT EDIT.

package vk

// Extension names and versions
const (
	KHR_WAYLAND_SURFACE_EXTENSION_NAME = "VK_KHR_wayland_surface"
	KHR_WAYLAND_SURFACE_SPEC_VERSION   = 6
)
