//go:build linux

// Code generated by go-vk from vk.xml at 2025-10-25 17:30:05.437087473 +0000 UTC m=+6.171421309. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_DIRECTFB_SURFACE_EXTENSION_NAME = "VK_EXT_directfb_surface"
	EXT_DIRECTFB_SURFACE_SPEC_VERSION   = 1
)
