//go:build linux

// Code generated by go-vk from vk.xml at 2025-10-26 13:04:51.581050741 +0000 UTC m=+10.988749089. DO NOT EDIT.

package vk

// Extension names and versions
const (
	KHR_XLIB_SURFACE_EXTENSION_NAME = "VK_KHR_xlib_surface"
	KHR_XLIB_SURFACE_SPEC_VERSION   = 6
)
