//go:build linux

// Code generated by go-vk from vk.xml at 2025-10-25 17:30:06.672814345 +0000 UTC m=+7.407148151. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_ACQUIRE_XLIB_DISPLAY_EXTENSION_NAME = "VK_EXT_acquire_xlib_display"
	EXT_ACQUIRE_XLIB_DISPLAY_SPEC_VERSION   = 1
)
