//go:build darwin

// Code generated by go-vk from vk.xml at 2025-10-26 13:04:52.609225587 +0000 UTC m=+12.016923845. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_METAL_OBJECTS_EXTENSION_NAME = "VK_EXT_metal_objects"
	EXT_METAL_OBJECTS_SPEC_VERSION   = 2
	EXT_METAL_SURFACE_EXTENSION_NAME = "VK_EXT_metal_surface"
	EXT_METAL_SURFACE_SPEC_VERSION   = 1
)
