//go:build linux

// Code generated by go-vk from vk.xml at 2025-10-26 13:04:52.887767008 +0000 UTC m=+12.295465296. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_DIRECTFB_SURFACE_EXTENSION_NAME = "VK_EXT_directfb_surface"
	EXT_DIRECTFB_SURFACE_SPEC_VERSION   = 1
)
