//go:build linux

// Code generated by go-vk from vk.xml at 2025-10-25 17:30:06.439724304 +0000 UTC m=+7.174058090. DO NOT EDIT.

package vk

import "unsafe"

// WaylandSurfaceCreateInfoKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWaylandSurfaceCreateInfoKHR.html
type WaylandSurfaceCreateInfoKHR struct {
	// SType = STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR
	PNext   unsafe.Pointer
	Flags   WaylandSurfaceCreateFlagsKHR
	Display *uint32
	Surface *uint32
}

type _vkWaylandSurfaceCreateInfoKHR struct {
	sType   StructureType
	pNext   unsafe.Pointer
	flags   WaylandSurfaceCreateFlagsKHR
	display *uint32
	surface *uint32
}

func (s *_vkWaylandSurfaceCreateInfoKHR) Goify() *WaylandSurfaceCreateInfoKHR {
	rval := &WaylandSurfaceCreateInfoKHR{
		PNext:   (unsafe.Pointer)(s.pNext),
		Flags:   (WaylandSurfaceCreateFlagsKHR)(s.flags),
		Display: (*uint32)(s.display),
		Surface: (*uint32)(s.surface),
	}
	return rval
}
func (s *WaylandSurfaceCreateInfoKHR) Vulkanize() *_vkWaylandSurfaceCreateInfoKHR {
	if s == nil {
		return nil
	}
	rval := &_vkWaylandSurfaceCreateInfoKHR{
		sType:   STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR, /*c1*/
		pNext:   (unsafe.Pointer)(s.PNext),                      /*cb*/
		flags:   (WaylandSurfaceCreateFlagsKHR)(s.Flags),        /*cb*/
		display: (*uint32)(s.Display),                           /*cb*/
		surface: (*uint32)(s.Surface),                           /*cb*/
	}
	return rval
}
